### ISSUE TITLE
Mirror Github activity to public-pointer-events

### ISSUE THREAD

**Issue by AFBarstow** [w3c/pointerevents#10]
@dontcallmedom  @shepazu  - the Pointer Events WG would like all activity at github/w3c/pointerevents (new Issues and subsequent discussion, Pull Requests, commits, etc.) to be mirrored to the group's Public mail list (public-pointer-events). Would you please configure the github/w3c/pointerevents repo to do this or let us know who we should contact to do this mirroring?

**Comment by dontcallmedom** [comment]
done

**Comment by AFBarstow** [comment]
TY @dontcallmedom !
