### ISSUE TITLE
Current draft: the definitions of tiltY and twist is not visible"

### ISSUE THREAD

**Issue by mustaqahmed** [w3c/pointerevents#102]
See the definitions of <code>tiltY</code> and <code>twist</code> around Figure 3 [here](https://w3c.github.io/pointerevents/#pointerevent-interface).

I suspect some problem with HTML tags.

**Comment by patrickhlauke** [comment]
urgh, well spotted. yes, must be some problem in the markup which re-spec then mangles further. i'll have a look
