### ISSUE TITLE
Should DragEvent be upgraded to a PointerEvent?

### ISSUE THREAD

**Issue by RByers** [w3c/pointerevents#106]
Split off from #100.  Unlike `click` etc., Edge still uses `MouseEvent` for `dragstart` etc.

**Comment by smaug----** [comment]
MouseEvent for dragstart? Are you sure about that? Wouldn't dnd be rather broken if DragEvent wasn't used.
Isn't upgrading existing events actually a bit regression risky. That changes the prototype chain.
Though, I guess we want to support dnd somehow using touch.

**Comment by RByers** [comment]
Sorry, what I meant to say is that `DragEvent` inherits just from `MouseEvent`, not `PointerEvent`.

Yes, there's definitely some compat risk here.  Is it much worse than in #100 though (which apparently Edge has already shipped without issue)?

**Comment by NavidZ** [comment]
We talked about this in the call. There are some advantages to this such as having pointerId and pointerType for multiple dragging at the same time but there are also some complications like handling of setPointerCapture. Pushing this to V3 to further discuss this.

**Comment by patrickhlauke** [comment]
Discussed in the PEWG call today https://www.w3.org/2020/08/19-pointerevents-minutes.html. @smaug---- filed issue against HTML spec. Closing issue here.
