### ISSUE TITLE
Configure this repo to use gitbot and the #pointerevents channel

### ISSUE THREAD

**Issue by AFBarstow** [w3c/pointerevents#11]
Want to use gitbot with the #pointerevents channel, so that, f.ex., PRs and commits are dumped to the channel.

**Comment by patrickhlauke** [comment]
Bumping this ... mainly to ask if anybody has experience in setting this sort of thing up.

**Comment by cynthia** [comment]
Setting this up is trivial, but needs to be done by W3C staff or at least someone with admin rights to the repo. I guess @shepazu is the person we should nudge?

**Comment by patrickhlauke** [comment]
I think as we've been doing fine without it (and any github activity is fired to the mailing list), we can probably close this...

**Comment by RByers** [comment]
Yeah SGTM, thanks.
