### ISSUE TITLE
Red text on dark blue background hard to see

### ISSUE THREAD

**Issue by DavidMacDonald** [w3c/pointerevents#112]
It has a colour contrast of 1.3:1 Consider putting  white behind it or something.

![2016-07-19_5-18-36](https://cloud.githubusercontent.com/assets/2365411/16944858/74437974-4d70-11e6-926a-30a2203cb298.png)

**Comment by scottgonzalez** [comment]
I believe this is a change that needs to be made in ReSpec, not in this repo.

**Comment by patrickhlauke** [comment]
indeed, those styles come from/are injected by respec - filed https://github.com/w3c/respec/issues/877
