### ISSUE TITLE
Update tap event order list for single logical mouse pointer

### ISSUE THREAD

**Issue by RByers** [w3c/pointerevents#117]
For #35 I think we didn't update the note in [section 11.3](https://w3c.github.io/pointerevents/#mapping-for-devices-that-do-not-support-hover).  Eg. I think:
- pointerover
- mouseover
- pointerenter
- mouseenter

Should be replaced with:
- pointerover
- pointerenter
- mouseover
- mouseenter

**Comment by patrickhlauke** [comment]
does this also affect the out/leave events in light of https://github.com/w3c/pointerevents/pull/56 ?

**Comment by NavidZ** [comment]
This should be something easy to fix I believe. Right?
