### ISSUE TITLE
Clarify duration of pointer event suppression during a touch action

### ISSUE THREAD

**Issue by RByers** [w3c/pointerevents#118]
[The spec](https://w3c.github.io/pointerevents/#the-touch-action-css-property) says:

> During the execution of a user agent touch behavior, the user agent must not fire subsequent pointer events for the pointer. 

Edge implements this by suppressing all pointer events as long as the touch-action is in progress, including momentum that follows (so repeated flicks on the same element don't send additional pointerdown).  Chrome implements this only until the next time a finger goes down.  Consider something like "subsequent touches that may contribute to that touch behavior will not generate pointer events").

**Comment by RByers** [comment]
Andrew points out that the Edge behavior also generally results in a better user experience.  When you're doing a sequence of many flicks, if you happen to accidentally hit a touch-action:none region you really don't expect the scroll to grind to a stop.

**Comment by RByers** [comment]
[Blink bug to match Edge behavior](https://bugs.chromium.org/p/chromium/issues/detail?id=631899).

**Comment by NavidZ** [comment]
We talked about this and @patrickhlauke is going to add a informative text about this since it is hard to define normatively as underlying gestures are not well defined at this point.
