### ISSUE TITLE
Explore unifying web-platform-test automation logic

### ISSUE THREAD

**Issue by RByers** [w3c/pointerevents#120]
Each PointerEvent implementation relies on it's own set of scripts that define how to automate the "manual" web-platform-tests.  From discussion at [the hackathon](https://docs.google.com/document/d/1b8aJOJcGXakstFJslKl87QwvlFHhHwGbQfJwnUTBBHg/edit) there is interest in trying to define a standard API to unify these and make these tests truly automated without needing per-vendor scripts.
- [chromium](https://cs.chromium.org/chromium/src/third_party/WebKit/LayoutTests/imported/wpt_automation/pointerevents/?q=wpt_automation&sq=package:chromium&dr)
- [Gecko](https://bugzilla.mozilla.org/show_bug.cgi?id=1288799)
- [jQuery PEP](https://github.com/jquery/PEP/tree/master/tests/functional)

Note that this isn't at all a spec issue, but filing here since it's something the PEWG wants to continue to track / discuss.  There are tentative plans for an informal discussion around this space at TPAC - let me know if anyone else is interested in participating.

**Comment by NavidZ** [comment]
Just to give an update here. We managed to get the [click API](https://web-platform-tests.org/writing-tests/testdriver.html) in wpt tests for the starter. I'll work with others to get the pointer action APIs in as well.

**Comment by patrickhlauke** [comment]
Discussed in today's PEWG meeting https://www.w3.org/2020/08/19-pointerevents-minutes.html. The situation has improved with WPT/WebDriver, and there's far less browser-specific work involved. Closing here, and if any issues remain they should be filed against WPT/WebDriver, whichever is more relevant.
