### ISSUE TITLE
Standardize CSS pseudoclass behavior for touch

### ISSUE THREAD

**Issue by RByers** [w3c/pointerevents#123]
`:hover`/`:active` CSS pseudoclasses are well defined and mostly interoperable for mouse input.  But behavior differs radically for touch.

Scenarios that should perhaps be supported across all pointer types with some style:
1. Will the element be clicked on lift.   This is `:hover:active` in Chrome today and in Edge when touch events are disabled, no built-in solution on Edge with touch events enabled).
2. Will the element be clicked if the pointer is moved back into it's bounds and lifted.  I think this is `:active` in Chrome and Edge.
3. Is the pointer over top of the element.  This is `:hover` in Edge, but due to #8 there's no built-in solution in Chrome.  Perhaps we should define a new pseudo-class like `:over` for this? 
4. Did a currently active pointer become active on the element.  This is `:active` in Edge.

Some open questions:
- When (if ever) should `:hover` be sticky - persist after lifting?  It is in Chrome (to support legacy hover menus via touch).  It's not in Edge.  And Safari has some crazy heuristic.  Perhaps we can finally get away with breaking this?
- What should the relationships between these styles and various DOM events be?  It's kind nice for mouse that `enter`/`leave` events correspond exactly to `:hover` for Mouse and in Edge.
- What is the relationship to tap highlights?  If a developer wants to replace the look of the system tap highlight with their own but show it at the same time, can they do that?  This is `:active` for touch in Chrome today.

This will ultimately be a CSS feature (certainly not a PE feature), but should probably be incubated in WICG initially.  Tracking here for now due to the interest of PEWG members and [discussion at the PE hackathon](https://docs.google.com/document/d/1b8aJOJcGXakstFJslKl87QwvlFHhHwGbQfJwnUTBBHg/edit#heading=h.tuf9doa1mr89), but we agreed it's not urgent (something to focus on once PE-level2 is out the door).  Next step is probably to create a WICG GitHub repo with an explainer for a specific proposal and ask on www-style for participation via the WICG.

**Comment by patrickhlauke** [comment]
IANAL, but wondering out loud if any of this is somehow bogged down in proprietary implementation/IPR issues

**Comment by patrickhlauke** [comment]
Discussed in PEWG call today https://www.w3.org/2020/08/19-pointerevents-minutes.html. It's something that should ideally be handled by CSS spec (as it will also apply to touch events, so not just a PE issue). Leaving this open for now to track initial reaction.

**Comment by RByers** [comment]
Anyone know if there's an issue open on any CSS spec for this?
Note [related twitter discussion](https://twitter.com/RickByers/status/1356078914498658306) and 
[open chromium issue](https://bugs.chromium.org/p/chromium/issues/detail?id=306581).

**Comment by patrickhlauke** [comment]
@RByers see above https://github.com/w3c/csswg-drafts/issues/5454
