### ISSUE TITLE
Could we ever do implicit capture for all pointer types?

### ISSUE THREAD

**Issue by RByers** [w3c/pointerevents#125]
In #8 we're discussing doing implicit capture for touch.  At the hackathon we discussed the "crazy" idea of doing implicit capture for all pointer types and agreed it would almost certainly be too breaking to change long-standing mouse event behavior (and any other option we could think of would be fraught with problems).

But I'm still wondering if there might still be some long-term path here (i.e. not something I'd want to couple to shipping pointer events in Chrome in the first place, but a possible transition later).

To help provide some data on this question @scottgonzalez wrote [this Chrome extension](https://github.com/scottgonzalez/implicit-pointer-capture).  You can try it out by using the "download zip" option in GitHub, unzip to a folder, then "load unpacked extension" in chrome://extensions.  After a few minutes of playing on major sites I haven't yet found an issue.  I'm sure there's tons of breakage out there, but still maybe it's not as intractable as we thought?

Note that Chrome doesn't yet [alter hit-testing during capture for mouse](https://bugs.chromium.org/p/chromium/issues/detail?id=629921) - only for touch.  So this isn't a complete test.

One thing that would break for sure is :hover styles during dragging, but maybe some rationalization will come out of #123 that would help.

Long term, if we imagine a world where >80% of web usage is via a phone (we're already at >50% by many measures) then maybe eventually changing the long-standing model of mouse isn't entirely insane?

**Comment by patrickhlauke** [comment]
not tried the extension, but: would this sort of thing not break UA behavior like dragging a link to the desktop on windows to create a shortcut and similar?

**Comment by RByers** [comment]
Not necessarily, I think we could have the built-in drag-and-drop still work when captured.  More challenging is perhaps HTML5 DnD APIs.  [That](http://www.html5rocks.com/en/tutorials/dnd/basics/)  appears to still work with the extension, but probably only because we still have the boundary events (not yet modifying hit-test during capture for mouse).

Here's one possible compromise that's more rational that the touch/mouse split.  We could state that drag and drop has the effect of releasing pointer capture (although we'd have to specify that this is ALL dragging as triggered as the default action of mousedown, not just HTML5 DnD where elements opt-in with `draggable`).  Then mouse dragging by default would not be captured (but would be if you `preventDefault` the `mousedown`), but touch would be.

**Comment by teddink** [comment]
We would have to do the same for touch drag and drop as well - Edge now support touch based cross process drag and drop as well.

**Comment by RByers** [comment]
Yep but you need a long press gesture to trigger that, right?  Just dragging with touch is not enough to trigger drag and drop.

**Comment by teddink** [comment]
Yep - true enough - long press is needed before the draggable item is "captured" to the touch point for dragging.

**Comment by NavidZ** [comment]
Is it safe to give up on this idea because of the mouse event impact?

**Comment by patrickhlauke** [comment]
> Is it safe to give up on this idea because of the mouse event impact?

Personally, I think so, yes

**Comment by scottgonzalez** [comment]
😢 I'll hold on to my dreams that one day this will happen...

**Comment by RByers** [comment]
Personally I was shocked that I didn't come across a single site impacted by this by running with Scott's extension enabled for a month or so.  Maybe it's not so hopeless?  Or at least if we're going to close it, we should perhaps have at least ONE example of a real-world website that's significantly broken by it?  Thoughts?

Regardless it's definitely NOT v2 - more crazy idea to consider for the future.

**Comment by mustaqahmed** [comment]
You are right: without a concrete example of a broken site, I shouldn't have closed the issue. Even though we agreed during the hackathon that the risk seems big, we also agreed that a pointer-type-independent behavior would be a great.

**Comment by patrickhlauke** [comment]
Coming back to this, what about a non-normative note that gives UAs the freedom to choose to do this if they want (i.e. that it's up to the implementations)? Or is that too lax?

**Comment by NavidZ** [comment]
We talked about this issue in the call and decided that we like to have such a feature. But since there might be some compat issues (as observed by the Chrome extension and some Gmail labels) we need to take more time and move more slowly for this.

**Comment by patrickhlauke** [comment]
Discussed at PEWG meeting today. In summary, feels like a breaking change that may be too late to do now. Current implicit capture just for touch makes sense due to touch interface problems of single finger used for activation and scrolling etc. Authors used to it from touch events. But for mouse, this implicit capture would be unusual. Not a big ask for mouse to require authors to explicitly capture, particularly since they're used to having to do horrible hacks to do this with mouse events (attaching handlers for mousemove on body on mousedown, removing on mouseup) at least it makes it nicer in PE.

Consider closing this unless we hear strong support from @NavidZ @mustaqahmed or others

**Comment by mustaqahmed** [comment]
We all suspected this as a risky change, and we seem to have _some_ evidence supporting our suspicion.  It makes perfect sense to trust our indirect knowledge and close this bug now because we couldn't prioritize the investigation in the last 4+ years!  We can always revisit the problem if "no default capture for mouse" ever becomes a problem for developers (I don't think it will happen).

**Comment by patrickhlauke** [comment]
perfect, thanks for confirming @mustaqahmed
