### ISSUE TITLE
How best to inflate hit targets for touch?

### ISSUE THREAD

**Issue by RByers** [w3c/pointerevents#126]
What's our best advice / sample for how to make the hit targets for touch larger than that for mouse?

I'm working with an internal Google customer whose doing this already for `touch`+`mouse` events, it's not clear how much harder `pointer` events make this.  I'll add more details later once I better understand the scenario.  It's also possible that the main problem here is that we don't do any "touch adjustment" in Chrome for the pointer events (just 'click') - we're [talking about changing that](https://bugs.chromium.org/p/chromium/issues/detail?id=625198).

**Comment by patrickhlauke** [comment]
Unless I'm missing something, this doesn't feel like a spec issue, but more a specific implementation (for the web content author, not UA authors)? i.e. integrating things like [what-input.js](https://github.com/ten1seven/what-input) and adapting target sizes?

or is this about spec'ing explicitly how UAs can fake/retarget coarse pointer input automagically? personally, i'm not a fan of automagic behavior...

Possibly related, in the WCAG/WAI Mobile Accessibility Task Force, we've been working on some accessibility-related advice for target sizes https://w3c.github.io/Mobile-A11y-Extension/ (this will, eventually, be rolled into WCAG 2.1 when it comes out)

> Target Size: The size of the target in relation to the visible display at the default viewport size is at least: (Level AA)
> - 44px by 44px for pointer inputs with coarse pointing accuracy (such as a touchscreen)
> - 20px by 20px for pointer inputs with fine pointing accuracy (such as a mouse, trackpad or stylus)
>   where px is a CSS pixel.
> 
> Note: In situations where multiple input mechanisms with both coarse and fine pointing accuracy are present, and where no mechanisms are present to determine the user's current input (either manual - e.g. providing the user with an explicit toggle to switch to a "touch-optimized" interface - or automatic - e.g. an application switching dynamically based on the type of input the user is currently using), targets must follow the larger minimum dimensions for coarse pointer inputs.
> 
> Note: This success criterion applies when platform assistive technology (e.g. magnification) is not turned on.
> 
> Editor's Note: We are researching the 20px value for mouse/pointer and 44px for touch. We are seeking research on this and outside input. We also have to define the difference between a touch event and a mouse event, particularly in html and responsive environments.
> 
> Editor's Note: this criterion borrows the distinction of "coarse" and "fine" pointing devices from [Media Queries Level 4 - Pointing Device Quality: the pointer feature](https://www.w3.org/TR/mediaqueries-4/#descdef-media-pointer)

**Comment by RByers** [comment]
Yeah I'm not sure we'd make much change to the spec for this.  I was thinking maybe we might want an option in the future for explicitly inflating hit targets for touch (maybe as an `eventListenerOption`), but that's out of scope of our charter so this probably isn't the right group.  But I do think our group should have an opinion (perhaps a sample) on the advice we'd give people for how to write such code.

Perhaps the one spec issue here is probably that the spec doesn't state clearly that `click` should be dispatched to the common ancestor of the `pointerdown` and `pointerup` node.  We had previously inherited that from `UIEvents` and the mouse compat model, but with the relaxation there for touch we probably need something specific.  Before we [change blink to do that (https://bugs.chromium.org/p/chromium/issues/detail?id=625198) I guess I'd like to hear from the group if others feel that's a reasonable thing for the spec to require?

**Comment by NavidZ** [comment]
We talked about this issue and agreed that this doesn't quite belong to pointerevents. But let's keep this around and add future-v3 label for now and see what we can do about it in the future.

**Comment by patrickhlauke** [comment]
xref https://github.com/w3c/touch-events/issues/93#issuecomment-384822302

**Comment by patrickhlauke** [comment]
> Perhaps the one spec issue here is probably that the spec doesn't state clearly that `click` should be dispatched to the common ancestor of the `pointerdown` and `pointerup` node. We had previously inherited that from UIEvents and the mouse compat model, but with the relaxation there for touch we probably need something specific. Before we [change blink to do that] (https://bugs.chromium.org/p/chromium/issues/detail?id=625198) I guess I'd like to hear from the group if others feel that's a reasonable thing for the spec to require?

as the referenced chromium bug has been fixed by now, is this aspect still relevant/something we need to do at the PE spec level?

**Comment by patrickhlauke** [comment]
Discussed today at PEWG call https://www.w3.org/2020/08/19-pointerevents-minutes.html. Agreed that this is out of scope for PEWG (and opens a potential can of UA specific / IPR worms). Closing.
