### ISSUE TITLE
Should Element.hasPointerCapture return true or false in the listener of pointerup or pointercancel?

### ISSUE THREAD

**Issue by mingchou** [w3c/pointerevents#132]
Spec says hasPointerCapture return true immediately after call to setPointerCapture. Looks like the return value of hasPointerCapture is determined by current pointer capture override and pending pointer capture override. So can I expect hasPointerCapture return false in the following conditions?
1) immediately after call to releasePointerCapture
2) in the listener of pointerup or pointercancel (which triggers implicit release of pointer capture)

**Comment by NavidZ** [comment]
Return value of hasPointerCapture is only determined by pending pointer capture override.
So that would return false in 1) and true in 2). The reason 2) is true is because implicit capture happens immediately **after** pointercancel/up which means after their handlers return as far as I understand.

**Comment by mustaqahmed** [comment]
Navid is right: implicit release of capture happens [after firing pointerup or pointercancel](https://w3c.github.io/pointerevents/#implicit-release-of-pointer-capture). So at pointerup/cancel handlers, hasPointerCapture has to be true.

@mingchou, does it answer your queries?

**Comment by mingchou** [comment]
Yes, it's clear and thanks.
