### ISSUE TITLE
Should Element.hasPointerCapture return true when set pointer capture to another element and release it immediately?

### ISSUE THREAD

**Issue by mingchou** [w3c/pointerevents#133]
In the case that element A already received gotpointercapture then
B.setPointerCapture
B.releasePointerCapture
Should A.hasPointerCapture return true or false?

I tested Chrome Canary and Edge, hasPointerCapture return false and element A will receive lostpointercapture. Finally no elements capture the pointer. Is it as expected?

**Comment by NavidZ** [comment]
Yes. It is.
After B.setPointerCapture A definitely doesn't have the capture. At this point hasPointerCapture returns true because B is set in pendingPointerCaptureTarget. Having pendingPointerCaptureTarget==B allows B to release the pointer capture. Now that B also released the capture the pendingPointerCaptureTarget is null and as the result hasPointerCapture should return false.

**Comment by mingchou** [comment]
Just a little bit confused when I was thinking about this question and reading the words in spec. For me, [1] looks like setPointerCapture only take effect when firing next pointer event. But now the behavior looks like setPointerCapture take effect immediately but only postpone gotpointercapture and lostpointercapture.

[1] https://w3c.github.io/pointerevents/#process-pending-pointer-capture

**Comment by NavidZ** [comment]
You understanding is correct regarding postponing got/lostpointercapture and immediately taking effect in hasPointerCapture.
As you can see in [this section](https://w3c.github.io/pointerevents/#dom-element-haspointercapture) "hasPointerCapture" returns true or false only based on pendingPointerCaptureTarget which immediately gets updates as the result of call to setPointerCapture and releasePointerCapture. So the return value of the function immediately takes effect when calling set/releasePointerCapture. But whether an element received got/lostpointercapture is a delayed notion defined in [process pending point](url) and will be processed before the next pointerevent.

If you are confused with why hasPointerCapture is defined in a way that takes effect immediately as oppose to the got/lostpointercapture delayed model maybe it helps to read the related issue #121 . There are some justifications for this behavior.

**Comment by mustaqahmed** [comment]
@mingchou, closing the issue assuming the clarification answers your query. Feel free to reopen if not.
