### ISSUE TITLE
Some tests don't work properly with mobile-sized viewports

### ISSUE THREAD

**Issue by RByers** [w3c/pointerevents#139]
Due to `position:absolute` boxes.  Eg. [this test](http://w3c-test.org/pointerevents/pointerevent_attributes_mouse-manual.html):

![w3c-test org-pointerevents-pointerevent_attributes_mouse-manual html nexus 5x](https://cloud.githubusercontent.com/assets/1280419/18284613/a4bed2e4-7438-11e6-8681-28c47b34fc10.png)

**Comment by patrickhlauke** [comment]
anybody got some availability to look at this issue? maybe do at least an initial list of which tests specifically have problems (so they can be tackled separately)?

**Comment by patrickhlauke** [comment]
@NavidZ @mustaqahmed any news on this? is it still relevant?

**Comment by patrickhlauke** [comment]
Is this still valid?

**Comment by mustaqahmed** [comment]
Looks like the test mentioned here was replaced by pointerevent_attributes_hoverable_pointers.html, which doesn't have "position: absolute".

**Comment by patrickhlauke** [comment]
Perfect, thanks for checking @mustaqahmed
