### ISSUE TITLE
Support hovering button states

### ISSUE THREAD

**Issue by jacobrossi** [w3c/pointerevents#14]
[Originating thread](http://lists.w3.org/Archives/Public/public-pointer-events/2015AprJun/0080.html)

The latest proposal looks something like this:
- Allow `buttons` to change while hovering
- Restrict pointerdown/up to only be for left buttton, touch, and stylus tip on screen (e.g. `button` value of 0)

We should also consider:
- should `click` fire for hovering button presses?
- should there be a new event, e.g. `pointerbuttonschange` that fires in this case?

Note that the latter point could also be useful for chorded button scenarios where you want an easy way to know another button changed even if the pointer is down.

**Comment by patrickhlauke** [comment]
Expanding the thought, though, we could also consider a hovering left-click or menu/context click (but not an erase button press) as an actual (faked) sequence of `pointerdown` > `pointerup` > `focus` > `click` sequence, i.e. making it equivalent to the user actually tapping the screen surface briefly. I assume that this would improve compatibility for scripts that are listening out for (some of) those events, making a hovered button press functionally equivalent to an actual button press with screen contact.

To avoid going into too much detail, we could make an non-normative/informative boxout right after the table in https://w3c.github.io/pointerevents/#button-states which suggests that some stylus devices also register a hovering stylus, and that UAs on those devices _MAY_ (or _SHOULD_ ?) do the above (treat a hovering button press as an actual tap on the screen, firing the relevant event sequences) ? This would have the least impact on the spec (though would still be a substantive change, I guess).

**Comment by jacobrossi** [comment]
See me last mail to the list. But hover barrel button presses don't map to right-click usually (at least they don't in Windows).  For that reason and for compatibility, I don't think we fire click in this scenario.  But a new event, like `pointerbuttonschange` might be a good addition.

I don't want to add a non-normative note of that type as it just promotes browser behaving differently. We should just agree how it works and then write that in with normative language.  This is Level 2 - we can (and have already) make substantive changes.

**Comment by patrickhlauke** [comment]
> But hover barrel button presses don't map to right-click usually

oh, my mistake...I could have sworn in some of my early testing on Surface 3 it did, but rechecking it now you're of course right.

Wondering though about the Wacom Bamboo, which does seem (at least from its documentation) to have both left- and right-click when hovered, and whether or not this sort of feature would be expected/desired - which brings us back to the original question, I guess

**Comment by patrickhlauke** [comment]
Regarding `pointerbuttonschange` type event - would that then supercede the

> Additionally, when a pointer changes button state, pressure, tilt, or contact geometry (e.g. width and height) and the circumstances produce no other pointer events defined in this specification then a user agent must fire a pointer event named pointermove.

bit in https://w3c.github.io/pointerevents/#the-pointermove-event ?

**Comment by jacobrossi** [comment]
Probably not just out of the sake of compat. I think we could fire both
without issue.

**Comment by RByers** [comment]
In our call today @scottgonzalez argued that the simplest thing is to treat stylus like mouse - send `pointerdown` / `pointerup` on hovering button press.  We'd update the spec for this by removing the "pen contact" conditions in [chorded button interactions](https://w3c.github.io/pointerevents/#chorded-button-interactions).  Some devices / OSes may not support such hovering button presses, and that's fine.

Alternate proposal is to just send `pointermove` with changed `buttons` value.  This requires more spec special cases - eg. to allow non-active pointers with non-zero `buttons`, redefine "active buttons state", etc.

The key difference is in the behavior of naive applications (eg. those changing UI just on `pointerdown` events without consulting the `button`/`buttons` values).

**Comment by RByers** [comment]
Action: @teddink to check with Jacob (and Windows pen folks) to see if this behavior would be OK to them.  @scottgonzalez to add any details I missed in his proposal.

**Comment by scottgonzalez** [comment]
I believe that is a complete description, and it's such a small change :-)

**Comment by RByers** [comment]
In call today @teddink confirmed that treating the pen as we would a mouse in this case is reasonable.  Mustaq will write a PR for the [tweaks discussed](https://github.com/w3c/pointerevents/issues/14#issuecomment-223039867).

**Comment by mustaqahmed** [comment]
ptal. The change in "active button state" needs a careful look: I think I covered all corner cases, but there could be some subtleties.
