### ISSUE TITLE
Define ordering of lostpointercapture and pointerout/leave for touch

### ISSUE THREAD

**Issue by RByers** [w3c/pointerevents#142]
Current Chrome (55.0.2865.0): pointerup lostpointercapture pointerout pointerleave
Edge: pointerup pointerout pointerleave lostpointercapture

Spec (and tests) should say which it should be.
One benefit of the Chrome model is that it's consistent with what web developers would expect for a hovering pointer (like mouse).
But Edge has probably always done it this way for touch, so that in theory could be more web compatible.

**Comment by NavidZ** [comment]
Just to add when using button like in this example:
http://output.jsbin.com/wahawofufe

Edge does generate the same order of the events as Chrome. However in this example which the element is div what Rick said happens.
http://output.jsbin.com/fiyoqok

**Comment by teddink** [comment]
Here is a test page that shows the difference in behavior between Chrome Canary and Edge with our current implicit capture implementation. 

[http://jsbin.com/fiyoqok/3/edit?js,output](http://jsbin.com/fiyoqok/3/edit?js,output)

**Comment by teddink** [comment]
External Bug for Edge: [https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/8974782/](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/8974782/)

**Comment by NavidZ** [comment]
@teddink I remember you told us @jacobrossi might have had some reason on why touch is different from mouse here. I was wondering if that reason still exists or are you guys going to make touch and mouse similar regarding this issue? If so can we just create a PR and a test and close this issue?

**Comment by teddink** [comment]
If we did have a reason, we could not figure out what it could be. We intend for mouse and touch to have the same behavior here.

**Comment by mustaqahmed** [comment]
Ooops, closed accidentally.
