### ISSUE TITLE
Need to clarify what triggers boundary events when releasing a capture

### ISSUE THREAD

**Issue by mustaqahmed** [w3c/pointerevents#145]
When a pointer capture is released from an element A while the pointer is over a different element B, we expect <code>pointerout</code>/<code>pointerleave</code> events for <code>A</code> and <code>pointerover</code>/<code>pointerenter</code> events for B before sending out future events (say a <code>pointermove</code>) to the hit-test node B. The current spec wording covers this through the Note in [Section 5.1.3](https://w3c.github.io/pointerevents/#firing-events-using-the-pointerevent-interface).

The wording needs to be a bit more precise, see [the discussion in a previous PR](https://github.com/w3c/pointerevents/pull/138#r77719958).

**Comment by NavidZ** [comment]
Isn't this the same issue as issue #15 ?

**Comment by RByers** [comment]
I think this probably includes the discussion in #15, but is more than just that.  There's other ways that the boundary event behavior around capture is currently imprecise.  Eg. see [this suggestion](https://github.com/w3c/pointerevents/pull/138#r77877674).

**Comment by NavidZ** [comment]
We should be able to make the definition a little more precise to include this case as well. Since it was originally hand-wavy definition I guess it is better to fix it in V2.

**Comment by NavidZ** [comment]
I'm going to add a test for this as well after the spec PR for this lands.
