### ISSUE TITLE
Determine when boundary events are fired after capture is released

### ISSUE THREAD

**Issue by scottgonzalez** [w3c/pointerevents#15]
If an element has pointer capture enabled and you move out of the element into another element, then release the button, what is the expected series of events after releasing the button?

In IE11, you only get a pointerup event on the capturing element. The pointer must then be moved again in order to get pointermove, poinerover, and pointerenter on the element that's currently hovered.

There was some [initial discussion on the mailing list](https://lists.w3.org/Archives/Public/public-pointer-events/2015AprJun/0089.html), as well as some [follow up discussion in this week's meeting](http://www.w3.org/2015/06/16-pointerevents-minutes.html#item04).

**Comment by patrickhlauke** [comment]
I believe this is addressed by #145 (@scottgonzalez feel free to comment/reopen if you think there needs to be further changes to the spec text to cover this)
