### ISSUE TITLE
How should touch-action behave for span?

### ISSUE THREAD

**Issue by NavidZ** [w3c/pointerevents#150]
I believe this test
https://github.com/w3c/web-platform-tests/blob/master/pointerevents/pointerevent_touch-action-span-test_touch-manual.html

is designed for the old days that touch-action was working on span. Can someone confirm that touch-action should have no effect on spans?
Do you think I should just remove the test or should we change the test in a way to make sure scrolling still works even though touch-action is none for the span?

**Comment by NavidZ** [comment]
This is a test related issue that we need to fix before v2. I wonder if it is better to have a "test" label for all issues that are related to tests only or need some test updates as well.

**Comment by mustaqahmed** [comment]
The test seems stale. Since <span> is a "non-replaced inline element", the touch-action property is not applicable here.

+1 for a new label for all issues blocking only on tests.

**Comment by NavidZ** [comment]
Looking again at the test it seems it correctly expects the scrolling work on the span. Not sure what I saw back then that I thought it expects the scrolling offsets as 0. Anyhow, closing this for now as it no longer applies.
