### ISSUE TITLE
Fire pointerover/enter before gotpointercapture

### ISSUE THREAD

**Issue by NavidZ** [w3c/pointerevents#156]
Following this comment:
https://github.com/w3c/pointerevents/issues/39#issuecomment-193966884

I believe there was an agreement on sending pointerover/enter before gotpointercapture. This is not reflected in the tests though.

**Comment by mustaqahmed** [comment]
Yes, we already agreed, see [this comment](https://github.com/w3c/pointerevents/issues/39#issuecomment-216951227).
