### ISSUE TITLE
Should on(got/lost)pointercapture be in GlobalEventHandlers?

### ISSUE THREAD

**Issue by NavidZ** [w3c/pointerevents#157]
Similar to other onpointer"event" handlers, should we also have on(got/lost)pointercapture handlers added to GlobalEventHandlers instead of Element interface?

**Comment by NavidZ** [comment]
@teddink @jacobrossi 
I was wondering if there was a particular reason that Edge puts on(got/lost)pointercapture for Element instead GlobalEventHandlers along with others on"event" handlers and whether you think it is okay to put on(got/lost)pointercapture beside the others for consistency.

**Comment by RByers** [comment]
`setPointerCapture` is on `Element` so doesn't that mean only an `Element` can ever receive `gotpointercapture` / `lostpointercapture` events?  I think all implicit capture scenarios should be to `Element` also, right?  In particular, `GlobalEventHandlers` also applies to `Document` and `Window`.

**Comment by dtapuska** [comment]
the events bubble

**Comment by NavidZ** [comment]
Sure. I agree that those capturing API should remain in an Element. But on(got/lost)pointercaptures bubble up so they can be handled with something on the window presumably.

**Comment by RByers** [comment]
Duh, good point :-).  I can imagine event delegation frameworks really wanting to listen on window.  I assume you see the events bubble up to `window` on Edge when using `addEventListener`, right?  Assuming that's the case, then I agree the `ongotpointercapture` etc. properties should be consistent and live in `GlobalEventHandlers` also.

**Comment by NavidZ** [comment]
Yes. Both on Edge and Chrome, when you add a gotpointercapture listener via addEventListener to the window it does get triggered when an element inside gets the capture and yet neither of browsers have ongotpointercapture defined on window.

**Comment by teddink** [comment]
I am following up with dev and spelunking through the code a bit to see if there is a reason.

**Comment by NavidZ** [comment]
@teddink were you able to get any updates on this one?

**Comment by teddink** [comment]
Yes I was - there is no specific reason why, we intend to make the same change.

**Comment by NavidZ** [comment]
So does [this PR](https://github.com/w3c/pointerevents/pull/158) sums up all the changes needed?

**Comment by teddink** [comment]
The PR looks good to me. We should add a test as well :-)

**Comment by NavidZ** [comment]
Yup. I have the test ready as well actually. I'm going to send it as soon as the spec PR lands.

**Comment by NavidZ** [comment]
The test landed as well and this issue can be closed now.

**Comment by bzbarsky** [comment]
> the events bubble

@dtapuska Not per the spec as currently written, right?

**Comment by NavidZ** [comment]
In the [Pointer Event types](https://w3c.github.io/pointerevents/#pointer-event-types) section it is specified that the got/lostpointercapture events bubble. Also both the Edge and Chrome implementations do that.

**Comment by bzbarsky** [comment]
@NavidZ The actual processing model fires a non-bubbling event.  Specifically, https://w3c.github.io/pointerevents/#the-gotpointercapture-event says to https://w3c.github.io/pointerevents/#firing-events-using-the-pointerevent-interface which will call into https://dom.spec.whatwg.org/#concept-event-fire which by default fires a non-bubbling event.  There is no mention of setting "bubbles" to true in <https://w3c.github.io/pointerevents/#firing-events-using-the-pointerevent-interface>.

The table you link to has no obvious normative status that I can see, in the sense that it's not clear how to actually apply the data in that table to anything.

If the spec is wrong and the event should actually be bubbling, please fix the spec.

**Comment by bzbarsky** [comment]
Ah, I see.  There's the "whose attributes are set as defined in PointerEvent Interface, and Pointer Event types." bit @RByers pointed out.

I think saying "whose 'bubbles' and 'cancelable' attributes are initialized as defined in ..." would help clarity a lot here.

**Comment by bzbarsky** [comment]
And specifically, from the current wording it's not clear that the "Sync/Async" column does _not_ correspond to an IDL attribute, but the Bubbles and Cancelable columns _do_.

**Comment by NavidZ** [comment]
This is not only about that table. That section has a whole bunch of attribute initialization for different events. The firing section used to list them all but as they got bigger in one of the pull requests we changed it to just point to that section. Regarding Sync/Async I agree with you. But what do you suggest?

**Comment by bzbarsky** [comment]
I think it would make sense to explicitly say that bubbles/cancelable are set per the table and the other IDL attributes are set per the prose in https://w3c.github.io/pointerevents/#pointer-event-types though the indirectness of needing to know which event caused the algorithm to run (but that event not being an argument to the algorithm) is pretty unfortunate.  Being more explicit there would have been better too.

**Comment by NavidZ** [comment]
@bzbarsky do you mind filing another issue for that so we can track it separately?
