### ISSUE TITLE
Touch-action should distinguish between single- vs multi-finger panning

### ISSUE THREAD

**Issue by mustaqahmed** [w3c/pointerevents#159]
What happens when an app wants to handle two finger panning in JS but let the browser scroll the page?  I think the current definition of touch-actions is ambiguous, hence we have difference in implementations.

[Here is a demo](http://mustaqahmed.github.io/web/image-panning.html) that shows that a one-finger-browser-action plus two-finger-JS-action is possible in Edge but not in Chrome!  We think Chrome needs to match Edge ([bug](http://crbug.com/632525)). 

More importantly, the spec can do better by providing more granularity in touch-actions.

The spec currently covers "singer-finger pan" browser action unambiguously through <code>touch-action: pan*</code>, and we have <code>touch-action: pinch-zoom</code> both in Edge & in Chrome (still as experimental) to cover (two-finger) zoom action (see w3c/pointerevents#565).  Clearly a two-finger-pan sits in-between a one-finger-pan and a pinch zoom: in terms the outcome (=scrolling) it is like a one-finger-pan but in terms of "user activity" it is like a pinch zoom (=needs 2 fingers).  In Chrome "touch-action: pan-x pan-y" interprets a two-finger-pan as a one-finger-pan;  in Edge it is like a pinch zoom.

Perhaps an additional "attribute" in touch-action is good enough, something like
<code>touch-action: pan-x single-finger</code>
vs
<code>touch-action: pan-x multi-finger</code>.

Thoughts?

(To clarify, I am talking only about simultaneous two-fingers here. The "gesture transition" scenario---adding/removing a finger from an ongoing gesture---seems harder.)

**Comment by lpd-au** [comment]
I very recently switched mouse events for pointer events in a legacy project with a use case just like you describe, a large pannable map on a zoomable (and hence scrollable) page. The ability to treat single and double finger panning separately would have been extremely useful to me. In the end, also lacking consistent `pinch-zoom` support, I just disabled dragging on mobile browsers and provided alternative navigation.

**Comment by patrickhlauke** [comment]
Wondering how much of this is down to user agent/os though. Some UAs may implement a "pan is always two fingers", while others may pan on single finger. I'd keep the `touch-action` values rooted in what the outcome is (panning, zooming) rather than anything more specific about the action/gesture itself. (unless I completely misunderstood the point here)

**Comment by RByers** [comment]
I think the most important thing here is that implementations of 'pan-x pan-y' disallow two-finger panning for scenarios like the above.  Now that we have a [formal pinch-zoom definition](https://compat.spec.whatwg.org/#touch-action) that says explicitly "two finger panning and zooming" I think this is covered by a spec, and Chrome is just in violation of it.  We should add a test that Chrome fails but Edge passes.

Being able to explicitly toggle this behavior might be nice, but I haven't heard of any use cases where people want the Chrome behavior (IIRC it was just simpler for us to implement).  It would also be hard to spec (out of scope for PE charter) and pretty niche and so hard to get broad support for.  I suggest we only consider expanding touch-action syntax for this if major use cases come up.

**Comment by mustaqahmed** [comment]
I didn't realize the out-of-PE-charter-scope problem when I filed this issue. It makes sense to defer it unless we have a concrete use-case for the current Chrome behavior (which we will [change](crbug.com/632525) to match Edge).

I will file a separate bug for adding the 'pan-x pan-y' test, to avoid confusion.

**Comment by RByers** [comment]
Sounds good, thanks Mustaq!
