### ISSUE TITLE
Spec references both W3C DOM4 and WHATWG-DOM

### ISSUE THREAD

**Issue by RByers** [w3c/pointerevents#160]
The definition of `composed` needed to reference WHATWG-DOM (since it's a new feature not yet reflected in the W3C copy).  IMHO we should just be consistent and reference WHATWG-DOM instead of DOM4 everywhere to avoid confusion about which algorithms exactly we were referring to (eg. see [this thread](https://groups.google.com/a/chromium.org/d/msg/blink-dev/T_amUSoAzHA/J2QsfpGKDwAJ))

**Comment by patrickhlauke** [comment]
Potentially political minefield? Personally, I would say only do it for those cases where currently WHATWG-DOM is more accurate than DOM4?

**Comment by chaals** [comment]
Actually, we are working on updating the W3C DOM spec. So please [file issues](https://github.com/w3c/dom/issues) for anything that you're missing and need so we can prioritise it.

In the next few days we'll give some more concrete information about the plans. I know the timing for explaining stuff is horrible for some places, but I have been working in countries where Christmas is either in January or not really a thing...

**Comment by RByers** [comment]
Ok, filed [this issue](https://github.com/w3c/dom/issues/13).

**Comment by patrickhlauke** [comment]
check to see if we can reference https://www.w3.org/TR/dom41/ / https://www.w3.org/TR/dom41/#composed-flag or whatever

**Comment by NavidZ** [comment]
I'm going to talk to the person who added composed here in the spec and see whether it is okay whether to reference [this spec](https://github.com/w3c/dom) instead of whatwg.

**Comment by NavidZ** [comment]
We have been referencing DOM4 in our document which apparently has the same entry as WHATWG-DOM in the reference. @patrickhlauke  do you think we should just switch them all to one? Say WHATWG-DOM? We'll see whether any objection rises from that. Note that TouchEvent spec has the same problem of referencing both and having the same entry twice in the reference section.

**Comment by patrickhlauke** [comment]
to avoid politics - assuming DOM4 says the same now as WHATWG-DOM - i'd prefer just changing that tiny reference to DOM4. functionally the same, but avoids potential raised eyebrows and pearl-clutching at review time.

**Comment by patrickhlauke** [comment]
Closed via #240 (and https://github.com/w3c/pointerevents/commit/e9bad530669af40ddf3ae5241c43c766da9d6dca)
