### ISSUE TITLE
New respec warnings about missing dfns

### ISSUE THREAD

**Issue by RByers** [w3c/pointerevents#163]
I don't remember seeing this before - perhaps a respec update?

```
Warnings

No <dfn> for pointerid in pointereventinit.
No <dfn> for width in pointereventinit.
No <dfn> for height in pointereventinit.
No <dfn> for pressure in pointereventinit.
No <dfn> for tangentialpressure in pointereventinit.
No <dfn> for tiltx in pointereventinit.
No <dfn> for tilty in pointereventinit.
No <dfn> for twist in pointereventinit.
No <dfn> for pointertype in pointereventinit.
No <dfn> for isprimary in pointereventinit.
No <dfn> for pointereventinit.
No <dfn> for pointerevent.
No <dfn> for element.
No <dfn> for globaleventhandlers.
No <dfn> for navigator.
```

**Comment by patrickhlauke** [comment]
Fixed the last 5 fairly straightforwardly https://github.com/patrickhlauke/pointerevents/commit/8286af433e8ed791529b15002e69b5d1fa55c389 but the first 10 warnings stumped me - see https://github.com/w3c/respec/issues/1027

**Comment by patrickhlauke** [comment]
The current workaround for the remaining warnings is very awkward and unnecessarily wordy https://github.com/w3c/respec/issues/1027#issuecomment-272771174
I think I'd rather live with having some ReSpec warnings than doubling up on the definitions just for the dictionary. Going to merge in my changes above and then close this if that's ok...
