### ISSUE TITLE
Should spec mention OS/UA features like palm rejection?

### ISSUE THREAD

**Issue by patrickhlauke** [w3c/pointerevents#165]
Looking over https://w3c.github.io/pointerevents/#the-primary-pointer (in relation to https://github.com/w3c/pointerevents/issues/570#issuecomment-268988711) we have information such as 

> Only a primary pointer will produce compatibility mouse events. In the case where there are multiple primary pointers, these pointers will all produce compatibility mouse events.

and

> NOTE
> When two or more pointer device types are being used concurrently, multiple pointers (one for each pointerType) are considered primary. For example, a touch contact and a mouse cursor moved simultaneously will produce pointers that are both considered primary.

One thing the spec doesn't mention is that some OS/UAs may have additional built-in features like palm rejection (where once you use a pen/stylus, touches are ignored) or similar (e.g. on Surface 3, while you're actively touching/using the touchscreen or stylus, the trackpad on the keyboard is disabled, meaning you can't have a touch/pen and mouse at the same time - although once you plug in an external usb mouse, that does work).

I'm thinking some form of non-normative note here in that section, just so that this doesn't come as a surprise to developers?

**Comment by RByers** [comment]
I definitely don't think we want anything normative here (it's just a feature of the hardware/OS in how it interprets physical stimuli like many others like smoothing).  But I can see how developers could be surprised by this, so a note could potentially be helpful.

Though in general I wonder if we weren't better off putting stuff for helping web developers to understand into a place like MDN than the spec (after filling a bunch of holes in the MDN docs for touch-action myself)?  I assume web developers are much more likely to read MDN than the spec, right?  No harm in doing both though IMHO.

**Comment by NavidZ** [comment]
This issue is somewhat similar to w3c/pointerevents#226. @patrickhlauke does the pull request for that issue cover this? Do you think we can make that more generic to cover anything that is missing?
https://github.com/w3c/pointerevents/pull/233
