### ISSUE TITLE
Need a test for 'touch-action: pinch-zoom` and `touch-action: pan-x pan-y' behavior for multi-finger panning

### ISSUE THREAD

**Issue by mustaqahmed** [w3c/pointerevents#166]
Since both two-finger panning & zooming is included in the [formal definition of pinch-zoom](https://compat.spec.whatwg.org/#touch-action), a 'pan-x pan-y' region should disallow two-finger panning. Edge behaves correctly, Chrome [doesn't](http://crbug.com/632525).

We need to add a test for this behavior.

**Comment by RByers** [comment]
See some relevant discussion in #159.

For tests that test a combination of stuff defined by the pointer events spec and the whatwg compat spec, I propose we create a "compat" sub-directory within the pointerevents web-platform-test directory.  This will make it easy to get a complete picture of pointer events interop generally, while still being able to easily focus just on PEL2 spec conformance in the rare situations that's most appropriate (eg. for CR exit criteria).  @mustaqahmed @NavidZ WDYT?

**Comment by NavidZ** [comment]
I personally love the idea of the subfolder for the interaction between pointerevents and other specs instead of only a naming convention.

**Comment by RByers** [comment]
Perhaps this test should also test the `pinch-zoom` property?  Alternately that could of course be a separate test, but since they're technically still manual tests it's nice to keep the number of separate test files to a minimum (ideally each operation we ask a user to do would occur in no more than a single test file which would validate everything we care about for that interaction).

**Comment by mustaqahmed** [comment]
Yes, I was also thinking of a single test where the user will do two-finger swipes twice (in a 'pan-x pan-y' region and then in 'pinch-zoom').

**Comment by RByers** [comment]
Sounds perfect, thanks!

**Comment by mustaqahmed** [comment]
The fix in Chrome has just [landed](https://chromium.googlesource.com/chromium/src/+/16ce460b6793b9fff0c1d4cc72deab60b921a159), yayy!

@NavidZ, we need to update the test status dashboard.

**Comment by NavidZ** [comment]
Thanks for letting me know about this test. I will update the test results once again before the end of the quarter.
