### ISSUE TITLE
Latest published spec link is wrong

### ISSUE THREAD

**Issue by RByers** [w3c/pointerevents#17]
It points to [http://www.w3.org/TR/pointerevents-level-2/](http://www.w3.org/TR/pointerevents-level-2/) because we changed the short-name from pointerevents to pointerevents-level-2.  Do we really want to change the shortname for a new version of the spec?

**Comment by jacobrossi** [comment]
Yeah, since this spec isn't errata but a new REC-track spec it needs a separate shortname.  This is like CSS3 Selectors versus CSS4 Selectors.

That said, we haven't published a WD of the new spec yet. So we could probably hide this link until we do (since it 404s right now).

**Comment by RByers** [comment]
Ok.  Looks like there's no easy way to do that (latestVersion is [supposed to be always auto-generated](https://github.com/w3c/respec/blob/1bba41b914f7186eb4968599bd2b4c15edbe94df/js/w3c/headers.js#L72) and there's no ID to style).  Presumably this is normal for new EDs - published version is just 404.  I'll just ignore it :-)
