### ISSUE TITLE
Behaviour of dblclicks is not specified

### ISSUE THREAD

**Issue by IvanSanchez** [w3c/pointerevents#171]
I'm a maintainer of Leaflet, and after fixing bug https://github.com/Leaflet/Leaflet/issues/5180 , I must complain about `dblclick`s in browsers which support `PointerEvent`s.

As far as I'm aware, the current state of affairs when it comes to firing `dblclick` events is:

| Browser        | Fires `dblblick` when double-clicking with a mouse  | Fires `dblclick` when double-tapping a touchscreen | Supports `PointerEvent`s |
| -------------- | ------------- | ------------- | ------------- |
| IE10, IE11     | Yes           | Yes           | Yes           |
| Edge           | Yes           | No            | Yes           |
| Firefox (v50)  | Yes           | No            | No            |
| Chrome (v<55)  | Yes           | No            | No            |
| Chrome (v>=55) | Yes           | Yes           | Yes           |
| Safari         | Yes           | No            | No            |

This makes polyfilling `dblclick` behaviour a hard issue (and one that requires browser sniffing which, as we know, is a Bad Idea™). As far as I'm aware, Leaflet is the only library that polyfills `dblclick`s for `PointerEvent`s; [jquery-PEP](https://github.com/jquery/PEP/) does not.

Part of the fault is attributable to the current redaction of the `dblclick` event in https://www.w3.org/TR/DOM-Level-3-Events/#event-type-dblclick (emphasis mine):

> A user agent MUST dispatch this event when the primary **button** of a pointing device is clicked twice over an element. The **definition of a double click depends on the environment configuration**, except that the event target MUST be the same between mousedown, mouseup, and dblclick.

That was written way before `TouchEvent`s were defined or implemented, so browser vendors can either stick to the wording (like Edge) or to the spirit (like Chrome, IE10/IE11).

I hereby request that UAs should behave **consistently** about firing `dblclick`s, and that this should be specified and documented. Either fire `dblclick`s only with a mouse, or fire `dblclick`s with any pointer type (I'd slightly prefer the later).

This probably depends on https://github.com/w3c/pointerevents/issues/100 , but is a different issue.

**Comment by RByers** [comment]
Thanks for raising this!  I'm not sure if this issue belongs here or UI Events, but for now let's not worry about that.  /cc @garykac @travisleithead.

I'm the one who pushed for sending `dblclick` for touchscreen in Chrome (which BTW we used to do ONLY on desktop not mobile - yuck).  My argument was that we want to allow developers to use high-level abstractions where appropriate for maximum UI consistency (time between taps) and accessibility and quality (edge cases like detecting a double-tap on the border of an iframe can be problematic for script).  It's also part of the pointer events philosophy to provide pointer-agnostic APIs, while allowing developers to customize per-pointerType when desired.

@teddink @smaug---- do you have any good arguments for NOT firing `dblclick` for a double tap, while still firing `click` for a single tap in Edge and Gecko?

**Comment by RByers** [comment]
Note that technically whether `click` is fired for touchscreens isn't even specified anywhere!  There's some encouraging notes [here](https://w3c.github.io/pointerevents/#compatibility-mapping-with-mouse-events), but nothing normative (although I think some of our tests depend on this).  Happily implementations agree (Safari's weird special case of "clickability" not withstanding).

So for now let's keep this issue focused on what implementations should do.  If we can get rough consensus on that, then separately we can discuss whether/how to improve the spec for both `click` and `dblclick`.

**Comment by patrickhlauke** [comment]
Assuming that `dblclick` for two taps would only be allowed to fire in case of `touch-action:manipulation` / `touch-action:none`, as otherwise it's a gesture that the UA will likely have a default behavior for?

**Comment by lpd-au** [comment]
In addition to desktop touch, Chrome for Android seems to also fire `dblclick` events when the page isn't scrollable, ie a viewport is specified and the content fits on the screen. As Rick said, it doesn't fire otherwise. [The `touch-action` value seems to be irrelevant.](http://output.jsbin.com/rowuhe)

~~It seems sensible to me that adding a `dblclick` event handler would, if necessary to actually detect and fire the event, re-enable the (touch) click delay for that element and its descendents.~~ And, likewise, that receiving such an event should only be guaranteed when `touch-action` is set to manipulation or stricter.

**Comment by ChumpChief** [comment]
We fire a dblclick for double tap in Edge when it doesn't result in a zoom (e.g. `touch-action: manipulation`) as @patrickhlauke suggests.  The zoom isn't considered a default action for dblclick in Edge though, as the zoom initiates on the second pointerdown (whereas the dblclick doesn't fire until after the second pointerup).

Using `touch-action: manipulation` is the recommended way to explicitly indicate that you intend to handle non-scrolling or non-continuous-zooming actions per PE level 1, which would include taps and double-taps.  Varying behavior on event registration would be an unpleasant side effect that doesn't have much precedent AFAIK.

**Comment by patrickhlauke** [comment]
@smaug---- @NavidZ do you think this is something that needs to be addressed/mentioned (even if only in an informative/non-normative note) in the PE spec? if so, any suggestions?

**Comment by NavidZ** [comment]
IMO since it is related to touch events I suggest either following it in the touch event spec or maybe in ui events where it defines dbclick. Now that we know browsers fire that for double tap gestures it is better to be spec it there

**Comment by NavidZ** [comment]
We talked about this in the call and since pointerevent spec doesn't mention anything about when to send click or dblclick it is outside of the scope for pointerevents. Maybe this issue is better to be moved to uievents (where dblclick event is defined) or touch events spec.
