### ISSUE TITLE
Should spec defines what triggers pointerover and pointerenter when implicitly releasing pointer capture?

### ISSUE THREAD

**Issue by mingchou** [w3c/pointerevents#173]
I knew this had been discussed in #145, but I'm still not sure about what triggers pointerover and pointerenter when implicit releasing pointer capture.

When the pointer is captured, hit test target is the pointer capture target override object. That means UA won't run the normal hit test algorithm. When implicitly releasing pointer capture, the hit test target is changed, and UA must fire boundary events. Should spec define what triggers UA run the normal hit test algorithm to determine the hit test target and fire pointerover / pointerenter to it?

e.g. When the pointer is captured by element A while pointer is hovering on element B, pointer is implicitly released when pointerup. What trigger UA to run the hit test algorithm and fire pointerover / pointerenter to B (in the case of the pointer isn't moved) ?

Tested on Chrome, boundary events are fired with a pointermove event. Edge fires boundary events with the subsequent pointermove event (happened when the pointer is moved).

**Comment by NavidZ** [comment]
We talked about this in the call and we agreed it makes more sense to send boundary events to the elements right after the capture release to kind of match the hover effect and what happens in scrolling. Let's add a test as well as a normative text to the spec for this.

**Comment by patrickhlauke** [comment]
@smaug---- just checking if you'll be able to draft up something for this? happy to fine-tune / wordsmith it further.

**Comment by smaug----** [comment]
Feel free to take this. I won't get this to in couple of days.
(And there was Easter, which means some holiday in Finland ;) )

**Comment by smaug----** [comment]
But I'll try to get to this still this week. Sorry about delay.

**Comment by patrickhlauke** [comment]
No worries. I'll have a think about it too (just didn't manage to get to it in the end last night as I was going through the last outstanding items)

**Comment by NavidZ** [comment]
We talked about this in the call today.
@mingchou @smaug---- what do you think of sending the pointerover/enter right after lostpointercapture without waiting for another move event? Does that sound reasonable? I believe this is not what Chrome does right now but we can change Chrome if we all agree on this behavior.

**Comment by smaug----** [comment]
yeah, that is fine. The most important is to have _some_ behavior defined.
