### ISSUE TITLE
ReSpec warning on "Privacy and Security"

### ISSUE THREAD

**Issue by patrickhlauke** [w3c/pointerevents#183]
New ReSpec warning "This specification doesn't appear to have any 'Privacy' or 'Security' considerations sections. Please consider adding one, see https://w3ctag.github.io/security-questionnaire/"

**Comment by marcoscaceres** [comment]
> On 4 Apr 2017, at 7:04 pm, Patrick H. Lauke <notifications@github.com> wrote:
> 
> /cc @marcoscaceres any good example out in the wild of a spec that has such a section?
> 

I cant think of any really good ones ... which is sad 😭 

> i'm guessing (please anybody else chime in if you think i'm talking rubbish) that this spec does not have any such potential concerns, so am i right in thinking we'd just need a section with the correct heading text and then a short para basically saying that there's nothing to be concerned about here in this respect?
> 

Go through: 

https://www.w3.org/TR/security-privacy-questionnaire/

It's actually super enlightening. You should be able to construct a paragraph from answering those questions.

**Comment by patrickhlauke** [comment]
@marcoscaceres well i gave it a shot https://github.com/w3c/pointerevents/pull/193 ;)
