### ISSUE TITLE
The spec doesn't define the values for relatedTarget

### ISSUE THREAD

**Issue by smaug----** [w3c/pointerevents#184]
Per current spec relatedTarget should be null (since nothing sets it), but implementations sure are setting it to some value with pointerover/out etc.

**Comment by patrickhlauke** [comment]
do you mean spec'ing this for touch/stylus? for mouse, it should behave the same as mouse events, and that part is inherited from the extended mouse event behavior

**Comment by smaug----** [comment]
Nothing in any spec defines what .relatedTarget should be for any pointer event.

UI Events spec explicitly defines what relatedTarget should be for mouseover/out etc. and otherwise null:
"The relatedTarget should be initialized to the element whose bounds the mouse pointer just left (in the case of a mouseover or mouseenter event) or the element whose bounds the mouse pointer is entering (in the case of a mouseout or mouseleave or focusout event). For other events, this value need not be assigned (and will default to null). "

**Comment by patrickhlauke** [comment]
as pointer events extend mouse events, and UI Events defines relatedTarget (for mouse), would it stand to reason that (for pointerType mouse) pointerevents behaved the same way? i.e. explicitly state this in the PE spec (and what would sensible value for touch/stylus be...same?)

**Comment by smaug----** [comment]
Oh, sure, pointer events should definitely behave the same way as mouse events. It is just that it is not defined anywhere.

Meaning that if one currently wants to implement pointer events per spec, .relatedTarget should be always null. But that is not what implementations do.
