### ISSUE TITLE
Should DnD release pointer capture?

### ISSUE THREAD

**Issue by NavidZ** [w3c/pointerevents#194]
Following #135 I believe there was an agreement that when DnD starts it should release the pointer capture of the pointer that initiated the DnD. I faced another question while implementing this in Chrome.

**Should the lostpointercapture be sent after dragstart event or right before?**

Testing [this example](http://jsbin.com/giqopi/edit?html,output) on Edge it seems that if fires the lostpointercapture sometime after dragstart. Edge may also send a few drag events before firing lostpointercapture depending on how much you move the mouse.

I believe it might be a little inconsistent with what the [DnD](http://w3c.github.io/html/editing.html#drag-and-drop) spec says:
_From the moment that the user agent is to initiate the drag-and-drop operation, until the end of the drag-and-drop operation, device input events (e.g., mouse and keyboard events) must be suppressed._

However, the spec didn't define what exactly drag-and-drop operation is. For example if js calls preventDefault in dragstart event handler the drag doesn't continue (or not even start I guess).

**Having said all these, and to also make it consistent across the board, I suggest sending lostpointercapture right before dragstart event if no one has any point against it.**

**Comment by NavidZ** [comment]
@patrickkettner is this alright from your side in Edge?
@mingchou does this sound reasonable since you are implementing it in Firefox?

**Comment by NavidZ** [comment]
@patrickkettner does the proposal sound reasonable?

**Comment by patrickkettner** [comment]
lgtm

**Comment by NavidZ** [comment]
Note that following the discussion on another issue #205 we went with sending pointercancel (and if necessary the lostpointercapture) after the drag operation starts which could be prevented by calling preventDefault on dragstart.
The test [here](https://github.com/w3c/web-platform-tests/blob/master/pointerevents/html/pointerevent_drag_interaction-manual.html) expects this behavior.
