### ISSUE TITLE
touch-action: scroll || scroll-x || scroll-y

### ISSUE THREAD

**Issue by appsforartists** [w3c/pointerevents#211]
A common interaction pattern that is not well-addressed by the pointer events spec is overscroll; that is, trying to scroll beyond the bounds of a scroll pane.  For instance, dragging a message in Inbox adjusts the scroll position until it's 0.  Dragging further will begin a gesture to close the message (while leaving scroll position at 0).  Another common example is pull-to-reload.  These interactions aren't straightforward to achieve with the current spec.

Would it be possible to introduce a new `touch-action` mode and behaves like `pan-{x,y}` does now, except it sends pointer events for overscroll?

- `scrollY = 100`
- User places finger at `{ 200, 200 }` and drags finger down by 110px
- For the first 100px, scrolling happens normally.  No pointer events are dispatched.
- When the user scrolls past `scrollY === 0`, `pointerdown` is dispatched with `{ pageX: 200, pageY: 300 }`
- `pointermove` is dispatched every frame until the pointer is lifted.
- `pointerup` is dispatched at `{ pageX: 200, pageY: 310 }`

**Comment by NavidZ** [comment]
@appsforartists would overscroll/scrollend events [here](https://discourse.wicg.io/t/proposal-new-events-for-overscroll-and-scrollend/3481) would solve the issue here? If so you might want to take a closer look and suggest any modifications there in these early stages.

**Comment by patrickhlauke** [comment]
Discussed at today's PEWG meeting (see minutes https://www.w3.org/2019/07/10-pointerevents-minutes.html). Decided that at this stage, this may require further discussion, as it is potentially beyond just pointers/pointer events, and that the proposed behavior may bring up issues when apps and default browser action need to be handed off twice. Suggest discussion happens at the WICG https://discourse.wicg.io/t/proposal-new-events-for-overscroll-and-scrollend/3481 / https://github.com/WICG/overscroll-scrollend-events - it may come back to PE when it's more matured, or may go into more general group like UIEvents
