### ISSUE TITLE
Would pointerType === 'pen' events participate in HTML5 Drag & Drop?

### ISSUE THREAD

**Issue by nicholaswmin** [w3c/pointerevents#212]
## Overview

Would `PointerEvent` events sent by a `pointerType === 'pen'` still be able to participate in [HTML5 Drag & Drop][1] behaviours?

## Use case

A user is using his Pen tablet to draw doodles in a canonical HTML5 Canvas whiteboard-style app. The app also has a Shape library where users can drag/drop shapes from onto the canvas. Would `pen` events still participate in that behaviour?

## Notes

- Chrome 59.x seems to have a bug with Pen events, see [this Chromium bug][2] for more info, so we can't really test this assertion there. 

- Chrome 61 (dev channel) doesn't seem to have that bug and pen events partly work as expected, however they don't seem to work on HTML5 Drag/Drop behaviours.

[1]: https://developer.mozilla.org/en-US/docs/Web/API/HTML_Drag_and_Drop_API
[2]: https://bugs.chromium.org/p/chromium/issues/detail?id=738357#c15

**Comment by NavidZ** [comment]
I believe we matched Edge's behavior regarding DnD for PointerEvent type pen. Do you see the same behavior in Edge that you see in Chrome 61 (which is not doing DnD with pen)?

**Comment by nicholaswmin** [comment]
@NavidZ Yes, DnD doesn't work on Edge either with a `PointerEvent` type pen.

I'm using [this demo][1] for the test

[1]: https://www.w3schools.com/html/html5_draganddrop.asp

**Comment by NavidZ** [comment]
I recall we had some problems getting DnD to work with WM_POINTERs for pen on Windows. That's why we just went with matching Edge's behavior. Perhaps they had the same problem or something. Maybe @patrickkettner can comment better here.

**Comment by nicholaswmin** [comment]
Yeah thanks, pushing this because creating synthetic `DragEvent`s is out of the question. 

Setting `dataTransfer` poses a security risk which is AFAIK the only way to transfer data between a draggable and it's dropzone.

So while we can simulate `MouseEvent`s from `PointerEvent`s (which partly fixes buggy behaviour in Chrome 59.x.x), there's no way to simulate a `DragEvent`.

**Cutting to the chase:** If this is not supported on the browser-level we can't hack around it in JS.

In any case, DnD should be working the same on the browser level across `penType`s, negating the need for such 'hacks'

**Comment by NavidZ** [comment]
In the cal we talked about this and everyone agreed that this is UA specific and if UA supports such behavior as long as it reports the pointercancel and other related events correctly it should be fine.
