### ISSUE TITLE
Difficulty understanding getCoalescedEvents definition

### ISSUE THREAD

**Issue by gsnedders** [w3c/pointerevents#215]
To me, the paragraph defining `getCoalescedEvents ` seems like a bit of mess. It makes a lot of statements without clearly delineating between them, and without defining what events get coalesced (and hence what properties they have are essentially undefined) and hence doesn't really define what the coalesced events even are. I'm also not clear on which sentences are declaring something normatively, and which are stating something informatively based on other definitions.

In short, I can understand each sentence individually, but the sum of them seems to leave a lot of behaviour undefined as far as I can tell (what are these events? what are their attributes?).

I can make a guess that we're meant to create the coalesced events ordinarily and then just change various attributes, but that's not clear. Or are we not changing them because we've coalesced them in such a way that they've already got those values?

I'd suggest something more like:

> Returns a sequence of all PointerEvents that were coalesced into the dispatched pointermove event. 
>
> Events must be coalesced into a single dispatched event grouped by [XXX], and the dispatched event's attributes set to a best representative summary of the coalesced events.
>
> Coalesced events must:
> * have the same pointerId, pointerType, isPrimary, isTrusted, target as the dispatched event,
> * have cancelable and bubbles set to false [NOTE: this is because they will never be dispatched], and
> * have all attributes mutated during [event dispatch](https://dom.spec.whatwg.org/#concept-event-dispatch) set to their default value. [NOTE: all related functions, including `stopPropagation` and `stopImmediatePropagation`, will do nothing as a result]
>
> The sequence must be in chronological order, sorted by `timeStamp`.

I think everything else in the paragraph is informative? You can add them back, but they should be clearly delineated from the normative requirements.

**Comment by patrickhlauke** [comment]
@RByers et al, mind having a closer look at this proposed rewrite suggestion?

**Comment by NavidZ** [comment]
@gsnedders the way you wrote it here sounds much better and clearer that it is now. Thanks. The only problem is that I'm not sure what we should use for the **XXX** part in _Events must be coalesced into a single dispatched event grouped by [XXX]_. The coalescing generally happens for all the events that happened since the last animation frame. However, if the main thread is busy or something they can also get coalesced even beyond that.

**Comment by dtapuska** [comment]
You might want to refer to something in here: https://html.spec.whatwg.org/#event-loop-processing-model

**Comment by gsnedders** [comment]
@NavidZ I think you need to refer to what @dtapuska linked to, and probably need to file a bug on HTML to make sure there's some way to reference it (or for it to reference pointer events); and you also need to, I think, say that you coalesce where they share pointerId, pointerType, isPrimary, isTrusted, and target attributes (AIUI).

**Comment by patrickhlauke** [comment]
@NavidZ are you able to have a look at this again?
