### ISSUE TITLE
Should "Setting Pointer Capture" with elements which are in document, but doesn't have associated browsering context

### ISSUE THREAD

**Issue by smaug----** [w3c/pointerevents#219]
The spec has just "If the Element on which this method is invoked does not participate in its ownerDocument's tree, throw an exception with the name InvalidStateError."
That means that document.implementation.createHTMLDocument().body.setPointerCapture(id) should work, which is rather surprising. If that works, why the need for element to be in any document?

**Comment by NavidZ** [comment]
We will follow the same wording as PointerLock spec saying restricting the capture to the active document.

**Comment by patrickhlauke** [comment]
I believe this is addressed by #246 and #247 (@smaug---- feel free to reopen if you believe this needs further clarification)
