### ISSUE TITLE
Add an API to get pre-coalesced points

### ISSUE THREAD

**Issue by RByers** [w3c/pointerevents#22]
When a web app is slow, most browsers will coalesces multiple movement events into a single one (with the latest position only).  This is perfect for scenarios that care most about minimizing latency, but unfortunate for scenarios (like art applications) where maximum motion detail is required.  Similarly, many OSes will artificially align input to v-sync for maximum motion smoothness, but for drawing scenarios it's really the raw points the app wants.

Android [MotionEvents](http://developer.android.com/reference/android/view/MotionEvent.html) are similarly batched and expose a history API (eg. [getHistoricalX](http://developer.android.com/reference/android/view/MotionEvent.html#getHistoricalX%28int,%20int%29)) to get all the original raw points.  iOS 9 adds a `coalescedTouchesForTouch` API for this ([sample code](https://developer.apple.com/library/prerelease/ios/samplecode/TouchCanvas/Listings/TouchCanvas_CanvasView_swift.html#//apple_ref/doc/uid/TP40016561-TouchCanvas_CanvasView_swift-DontLinkElementID_6)).

Perhaps `PointerEvent` should have a similar API?  Eg. `getCoalescedEvents` that returns an array of `PointerEvent` instances for the same pointerId?

I don't think this is particularly urgent (the art scenarios are fairly niche), but may become so if we want to block #9 on this.

**Comment by patrickhlauke** [comment]
Purely from a layman's "I like to make funky things with JS" point of view, I'm intrigued by this. Presumably, I'd be easy to then iterate over the array in sequence (i.e. the array has a defined chronological order for each `PointerEvent` contained inside)?

**Comment by RByers** [comment]
Yep, roughly instead of:

``` javascript
canvas.addEventListener('pointermove', addPoint)
```

You'd have something like:

``` javascript
canvas.addEventListener('pointermove', e => {
  for(let point of e.getCoalescedPoints()) {
    addPoint(point);
  }
}
```

On a device with a 120hz touch scan rate (eg. Nexus 5) you'd get lines that have twice as many points.

**Comment by RByers** [comment]
One risk here is that people would end up using this for other (more common) scenarios where it adds only wasted work (eg. dragging something around) and may decrease smoothness.  Perhaps we'd want to choose the API name carefully to help reduce the risk of this (maybe Android's "historical" term is better for this than iOS's more technically descriptive "coalesced").

**Comment by RByers** [comment]
Note we discussed this back in 2014 [here](https://lists.w3.org/Archives/Public/public-pointer-events/2014AprJun/0055.html)

**Comment by RByers** [comment]
Discussed at TPAC f2f, we think we should have an API something like:

```
interface PointerEvent {
  sequence<PointerEvent> getCoalescedEvents();
}
```

Properties:
- Some of the properties would be redundant with the primary event.  Eg. `pointerId`, `pointerType`, `target` would always match exactly
- `getCoalescedEvents` method on each such object would return an empty sequence (but perhaps could throw)
- The primary event always has a timestamp greater than every event returned by `getHistoricalEvents`
- We prefer "coalesced" to "historical" because it more precisely indicates that it does NOT include data for previously dispatched events.  It's a niche API so having a harder to spell word isn't a problem.

**Comment by teddink** [comment]
Windows API that could provide the raw data for this API: [https://msdn.microsoft.com/en-us/library/windows/desktop/hh454880(v=vs.85).aspx](https://msdn.microsoft.com/en-us/library/windows/desktop/hh454880%28v=vs.85%29.aspx)

There are similar API's in Windows for both pen and touch - so a UA may need to use multiple all of them to get all of the relevant data to fill in the full pointer event object.

**Comment by NavidZ** [comment]
Do you think we should have a way for js to be able to populate this list for an untrusted PointerEvent (which is created in js)?

**Comment by RByers** [comment]
Yes, absolutely!  JS should always be able to generate events just like the UA (except `isTrusted` of course).  Thanks for catching that I missed that.

**Comment by NavidZ** [comment]
As discussed previously in the mailing list I removed the v2-blocking from this issue.

**Comment by RByers** [comment]
Landed [here](https://w3c.github.io/pointerevents/extension.html#dom-pointerevent-getcoalescedevents) via #149 (looks like this didn't auto-add due to "Addresses" instead of "Fixes" in the commit description).  As usual, we'll leave the issue open until tests land.

**Comment by NavidZ** [comment]
I believe this can be closed as we are done with both the tests and the spec in the extension doc.

**Comment by patrickhlauke** [comment]
yup, good catch

**Comment by RByers** [comment]
[This](https://w3c.github.io/pointerevents/extension.html#dom-pointerevent-getcoalescedevents) is [now shipping](https://www.chromestatus.com/feature/5853451217010688) in Chrome 58 (stable).

@NavidZ has updated my [eventRate](https://rbyers.github.io/eventRate.html) demo to draw smaller dots representing the points that come from `getCoalescedEvents`.  Here's a screenshot from a [Samsung Chromebook Plus](http://www.samsung.com/us/computing/chromebooks/12-14/xe513c24-k01us-xe513c24-k01us/) which has a 200hz stylus that (like other touch-like input on ChromeOS) fires events only at 60hz.
![screenshot 2017-05-05 at 3 26 43 pm](https://cloud.githubusercontent.com/assets/1280419/25762993/09902a0e-31af-11e7-8833-64f8e6d4cf92.png)

You can see how you can get much smoother curves by considering the coalesced points.  If you introduce some synthetic jank by typing "20" into the "extra work" field, you can see how the main events are impacted but the coalesced points aren't.

@NavidZ has also updated my [event-timing](https://rbyers.github.io/event-timing.html) test page to show how the timing of the coalesced events lines up with the main event and the frames (though we had a [bug](https://bugs.chromium.org/p/chromium/issues/detail?id=710442) in Chrome 58, fixed in 59).  Here's some sample output from Chrome dev channel on Linux (where we have rAF aligned mouse events enabled) with a 120hz mouse.
```
frame[0]: events 0.8ms
frame[1] 14.9ms: events
frame[2] 16.7ms: events
frame[3] 17.7ms: events 0.2ms(4.5)
frame[4] 16.2ms: events 0.1ms(12.7, 4.7)
frame[5] 16.6ms: events 0.1ms(13.3, 5.3)
frame[6] 16.6ms: events 0ms(13.9, 5.9)
frame[7] 16.7ms: events 0ms(14.6, 6.6)
frame[8] 16.7ms: events 0.1ms(15.3, 7.3)
frame[9] 16.7ms: events 0.1ms(15.9, 7.9)
frame[10] 16.7ms: events 0ms(16.6, 8.6)
frame[11] 16.7ms: events 0ms(17.3, 9.3, 1.3)
frame[12] 16.7ms: events 0ms(9.9, 1.9)
frame[13] 16.7ms: events 0ms(10.6, 2.6)
frame[14] 16.7ms: events 0ms(11.3, 3.3)
frame[15] 16.7ms: events 0ms(11.9, 3.9)
frame[16] 16.7ms: events 0.1ms(12.6, 4.6)
```

The `frame[x] 16.7ms` shows that (as expected) `requestAnimationFrame` is ticking at a steady 60hz. The 'events 0ms' bit shows how each `pointermove` event is arriving just before `requestAnimationFrame` callbacks.  The relative times in parenthesis show that the `getCoalescedEvents` are coming in at a pretty steady 120hz without any alignment to vsync (there's a slow drift relative to the vsync clock).

**Comment by NekR** [comment]
@RByers can you confirm that mouse events aren't limited to 60hz on WIndows (just curious)?  I have I a 1000hz mouse which produces a lot more mouse events than say Macbook's touchpad.

**Comment by RByers** [comment]
@NekR, we [plan to soon](https://www.chromestatus.com/feature/6192761317359616), but it's only a trial now (1% of users or something).  Use the above test pages to see.

**Comment by dori4n** [comment]
@NekR I can confirm, that the mouse events are limited to the monitor background refresh rate on Windows 10 1703, as I've just tried it. That is typically capped at 120Hz (often some not as exact but odd value, resulting in 119Hz measured). The mouse I have used can do 1000Hz refresh, but I have set it to 800. The monitor I used was set to 144Hz refresh rate. The events measured were between 117 and 122, most often the result out of the 30 tests I've done was 119.

Edit: Scratch that, got up to 142 by drawing very short lines (4-5 dots), still, somehow seems weird to me.

**Comment by sigurdle** [comment]
Hi, I was told that feedback from developers is useful to further the standardization of certain api. The getCoalesced API I've found very useful. I'm making a a paint/art program and it should go without saying that any API that gives you more control over the pointer, movements etc. is very very useful for such a program. I'm very excited about several things that the chromedev team are doing, getCoalescedEvents and everything to do with pointer (pressure,tilt etc. which is now standard) makes all the difference when it comes to an app that can really compete with desktop apps. I really hope that getCoalescedEvents will become standard (and also a new rawmovepointer event that I hear about sounds very exciting as well), and anything to do with WebGL/WebGPU. And a new thing that chrome is  working on, a new API to better support real local files. All very very welcome.
Thank you for great work

Sigurd Lerstad

**Comment by patrickhlauke** [comment]
thanks for the feedback @sigurdle - this has been initially spec'd out here https://w3c.github.io/pointerevents/extension.html and may find its way into future versions of the PE specification
