### ISSUE TITLE
It isn't clear what "page" means in "Setting Pointer Capture"

### ISSUE THREAD

**Issue by smaug----** [w3c/pointerevents#220]
What does "If this method is invoked while the page has a locked element ([PointerLock]), throw an exception with the name InvalidStateError." mean? What is a "page"?
Does it contain top level document and documents in iframes or what? The spec doesn't explain this.

See #219

**Comment by NavidZ** [comment]
In the call we talked about this and we are going to follow the same terminology as PointerLock spec which is the document instead of the page.
