### ISSUE TITLE
Should setPointerCapture work in Shadow DOM

### ISSUE THREAD

**Issue by smaug----** [w3c/pointerevents#221]
Per spec setPointerCapture shouldn't work in Shadow DOM, but f I read for example Chromium's source code right, it doesn't use "does not participate in its ownerDocument's tree", but Shadow including connected() check.

**Comment by patrickhlauke** [comment]
@mustaqahmed @NavidZ any thoughts on this? is it a chrome bug, or something wrong that needs specifying in the spec?

**Comment by mustaqahmed** [comment]
This looks like a crack in Chrome, we haven't been careful about Shadow DOM when we added the [check](https://cs.chromium.org/chromium/src/third_party/WebKit/Source/core/dom/Element.cpp?rcl=195db4ec8d8bc4fc650015fdd86de98ce81748d1&l=3372).

Thanks for noticing this.  I will file a chromium bug.

**Comment by mustaqahmed** [comment]
[Here](https://crbug.com/810882) is the Chromium bug.  I don't think we need to change the spec, so closing the issue.

**Comment by smaug----** [comment]
I'm pretty sure we want setPointerCapture to work in Shadow DOM too.

**Comment by patrickhlauke** [comment]
@smaug @mustaqahmed do you think this needs to be explicitly spec'd in the PE spec? if so, any pointers where/how?

**Comment by smaug----** [comment]
Yes, it needs to be spec'ed explicitly in PointerEvents. 
Right now the spec says 
https://w3c.github.io/pointerevents/#dfn-pointer-capture
"If the Element on which this method is invoked does not participate in its ownerDocument's tree, throw an exception with the name InvalidStateError."
That needs to say something else than 'does not participate in its ownerDocument's tree

Maybe something like 'if element's owner document is not shadow-including ancestor of the element'
https://dom.spec.whatwg.org/#concept-shadow-including-ancestor
(I wonder if some spec has better language for this. Maybe HTML spec)

**Comment by NavidZ** [comment]
In the call we agreed to follow the wording of other specs for this.
