### ISSUE TITLE
How is pointer event ctor supposed to work when coalescedEvents is passed using the PointerEventInit

### ISSUE THREAD

**Issue by smaug----** [w3c/pointerevents#223]
It isn't clear what is supposed to happen when coalescedEvents is passed using the PointerEventInit. 
Does the event have some internal array of pointer events or what? Does coalescedEvents work only when type is pointermove?

Gecko bug related to this: https://bugzilla.mozilla.org/show_bug.cgi?id=1303957.
I guess we'll implement some guess what the spec might try to say

**Comment by dtapuska** [comment]
Most Event ctor generally take the arguments as the user has specified even if they logically don't make sense. I'd expect pointer event to be like this.

**Comment by smaug----** [comment]
yeah, I'd expect that too, but the explanation of getCoalescedEvents() says
"Returns a sequence of all PointerEvents that were coalesced into the dispatched pointermove event."

What if the event wasn't dispatched at all? What if one just creates a pointer event and passes coalescedEvents in the init. What should getCoalescedEvents() return?
I'd expect the array which was passed in, but per spec that isn't suppose to happen.

**Comment by dtapuska** [comment]
Feel free to make a pull request with some alternate text. This really shouldn't be around the getCoalesecedEvent call but really how the coalescedEvents is initialized by the user agent by default.

**Comment by NavidZ** [comment]
Regarding the event that are being created in js I remember talking to @RByers and he was saying the ctors usually don't do any checks and just initialize properties from the stuff in the dictionary. So we went with that idea and whatever you put inside the initialization dictionary will be inside the pointerevent object regardless of what js set the type of the event be or what no.
We have [a test](https://github.com/w3c/web-platform-tests/blob/master/pointerevents/extension/pointerevent_constructor.html) for this case but apparently I didn't stretch it enough to set all the random attributes in the coalesced event array.

**Comment by smaug----** [comment]
Yeah, that sounds reasonable, but can we get that also to the spec?
Currently getCoalescedEvents() is limited to pointermove + event dispatch, and I don't understand why.

**Comment by smaug----** [comment]
The spec has changed but it is still wrong. Nothing says how the data from
PointerEventInit.coalescedEvents gets to the `coalesced event list ` .
And `coalesced event list ` is defined to be empty if event type is pointermove or pointerrawupdate.

**Comment by smaug----** [comment]
https://dom.spec.whatwg.org/#inner-event-creation-steps handles the normal cases, but 'coalesced event list' isn't an attribute.

**Comment by smaug----** [comment]
@annevk do you recall other cases where event contructor needs to do something special like this?

**Comment by annevk** [comment]
There's an issue with required members not working: https://github.com/whatwg/dom/issues/600. (And there's https://github.com/whatwg/dom/issues/606 about being more accurate about when time is captured.)

(I'm somewhat surprised this got all the way to shipping without at least some investigation into "how should this be specified".)

**Comment by annevk** [comment]
I recommend filing an issue against the DOM Standard for this so that we can consider what to do here whenever we end up reworking event construction and initialization.

**Comment by smaug----** [comment]
https://dom.spec.whatwg.org/#concept-event-constructor-ext

So pointer events spec should to define
**event constructing steps** for all the PointerEvents:
let **coalesced events list** be a clone of  eventInitDicts' coalescedEvents sequence.
let **predicted events list** be a clone of eventInitDicts' predictedEvents sequence.


that way the event constructions steps would follow the DOM spec.

Currently PointerEvents spec has a bit hand wavy " Untrusted events have their coalesced events list initialized to the value passed to the constructor."   

And I think https://github.com/web-platform-tests/wpt/blob/1408b119ac/pointerevents/pointerevent_constructor.html is a bit broken since it tests that event.target of coalesced events is updated too, but those are untrusted events, so target shouldn't be changed.

https://wpt.fyi/results/pointerevents/pointerevent_constructor.html?label=master&label=experimental&aligned&q=pointerevent_constructor.html shows that blink and gecko would need to be tweaked

**Comment by patrickhlauke** [comment]
did https://github.com/w3c/pointerevents/pull/427 fully address this issue, or is there more that needs to be done here?

**Comment by smaug----** [comment]
Whoever updates the implementation first will need to tweak https://github.com/web-platform-tests/wpt/blob/1408b119ac/pointerevents/pointerevent_constructor.html

**Comment by smaug----** [comment]
I'm tweaking the test on mozilla-central. I'm expecting to land the patch soon and then the test gets automatically merged to wpt.

**Comment by smaug----** [comment]
https://github.com/web-platform-tests/wpt/pull/32466 is the merge from mozilla-central.

**Comment by patrickhlauke** [comment]
perfect, thank you @smaug----
