### ISSUE TITLE
What should be the width/height of touch pointerUp?

### ISSUE THREAD

**Issue by EiraGe** [w3c/pointerevents#225]
Edge used to have touch pointerup width/height as 0, but it's not anymore.  Edge seems returning some interger between 1 to 5 now. Is it an implementation change?
Also Firefox, it seems randomly have 0 and 1. 
What do you think about pointerup width/height for touch? Should it be 0 as the pressure?
@patrickkettner @smaug---- @mingchou

**Comment by mingchou** [comment]
We generate pointer events from touch events on Firefox. Width and height come from touch radius, which is fetched from OS. Checked [touch event spec](https://w3c.github.io/touch-events/#touch-interface), it says "The radius of the ellipse which most closely circumscribes the touching area along the axis indicated by rotationAngle, in CSS pixels of the same scale as screenX; 0 if no value is known. The value must not be negative.". Current behavior seems reasonable for me.

Wondering if this causes some problems or blocks some features? Not opposed to change it, just want to know more.

**Comment by EiraGe** [comment]
Thanks for the reply @mingchou. Sorry that I'm slow in replying. It's not causing any problem, I just want to make it clear before we work on Chrome's implementation.
We are thinking that when pointerup, there is no touch in contact with the screen. Similar to ``pressure``, the spec specified that  **all pointerup events will have pressure 0**, should we have the same thing for ``width``/``height``?

**Comment by mingchou** [comment]
Sounds reasonable to me. Is this also applied to pointerup with a stylus?

**Comment by mustaqahmed** [comment]
Whatever we do, all pointer types should reflect it.  We shouldn't treat "touch" in a special way.

This is somewhat related to #65 where we discussed hovering width/height for mouse.  The discussion there suggests to me that _not_ resetting width/height on `pointerup` is a better option:
- For paint apps that would possibly care the most about width & height (e.g. Rick's [paint.html](https://rbyers.github.io/paint.html)), reporting the last contact geometry on the `pointerup` event removes the need to cache last known dimensions.
- If some digitizers report default non-zero constant values, we shouldn't hide them.  E.g. if a "thick" stylus tip causes the digitizer to report high width & height, the hovering cursor of the stylus could be wider than normal when possible, to let the painter know (before the pen touches the surface) that pen's stroke is wider.
- Both Chrome and Edge mouse reports width=height=1 for a while already.  We shouldn't change it even for a hovering mouse pointer unless there is a specific use case we want to support.

**Comment by mingchou** [comment]
So width and height are not really "contact" geometry, they are more like the geometry of the input device?

**Comment by NavidZ** [comment]
@mingchou to my understanding yes. But more accurately we report what the device reports us. So the device is in charge of translating that geometry to a number. If it can report a valid width and height for a hovering pointer we should be using that.

@mustaqahmed I believe the decision for the width/height=1 for mouse was that if we had a device that doesn't support reporting the width/height we set it to undefined and since the undefined value was problematic for the existing web we decided to call the undefined the value 1 (which could also be a real value reported by the device).
Following the same reasoning we can just set the pointerup for touch (or any other pointer) to 1 if we didn't get any valid width/height from underlying API. Does that sound reasonable?
Then if a device wants to define a default value or have the capability of calculating the width/height for the hovering touch (or any other pointer) they can just report that number and will use that.

**Comment by NavidZ** [comment]
Also a compatibility note. The same unknown value in the [touch event spec](https://w3c.github.io/touch-events/) is set to 0 for touch points.

> radiusX: The radius of the ellipse which most closely circumscribes the touching area (e.g. finger, stylus) along the axis indicated by rotationAngle, in CSS pixels (as defined by [CSS-VALUES]) of the same scale as screenX; 0 if no value is known. The value must not be negative.

So if we were to be consistent are we okay with reporting 0 for touchend touch points as well?

**Comment by mustaqahmed** [comment]
Returning `1` when the touch device _doesn't report a value_ looks like a more logical choice.  Having a default of `0` only for `pointerType=touch` would make life harder for developers IMO.

(Moreover, I see `TouchEvent.radiusX` too different from `PointerEvent.width` to justify copying their default value to here.)

**Comment by NavidZ** [comment]
In the call we talked about this issue and we agreed to just report 1,1 for touch pointerup events. I will add a test for that.

**Comment by patrickhlauke** [comment]
As the spec already states that the default value for width/height is 1 (https://w3c.github.io/pointerevents/#dom-pointerevent-width / https://w3c.github.io/pointerevents/#dom-pointerevent-height) and we've had agreement on the call that diverging values in implementations are bugs, I'm closing this as resolved. @EiraGe feel free to comment if you feel this should be further clarified in the spec text.
