### ISSUE TITLE
Should getCoalescedEvents() return always the same objects or new instances with same data?

### ISSUE THREAD

**Issue by smaug----** [w3c/pointerevents#227]
I didn't test yet what Blink does.
Need to test this during event dispatch, and also after event dispatch if JS keeps a ref to the event.

@NavidZ

**Comment by NavidZ** [comment]
Blink returns the same object. What do you think is better?

**Comment by smaug----** [comment]
Blink's behavior sounds reasonable.

**Comment by smaug----** [comment]
Does it return the objects also if the event  has been dispatch and getCoalescedEvents is called way after the event dispatch? So the event does keep the coalesced events alive, right?

**Comment by NavidZ** [comment]
Yes. It does keep them alive for as long as the event itself is alive.

**Comment by smaug----** [comment]
I think the spec is actually good enough here.
