### ISSUE TITLE
pointer-events for pseudo-elements

### ISSUE THREAD

**Issue by laukstein** [w3c/pointerevents#230]
https://w3c.github.io/pointerevents/ doesn't mention anything regarding `pointer-events` and pseudo-elements (`:before` and `:after`).

And currently seems no browser supports

```
<a href=#test></a>

a:before {
    content: "Link";
    pointer-events: none;
}
```
testcase https://output.jsbin.com/telawab/quiet

Wouldn't `pointer-events` be expected to be supported also in pseudo-elements? In this case, means, link mustn't be clickable, right?

Maybe would be worth to mention anything in spec.

**Comment by laukstein** [comment]
In case this issue isn't directly related to https://w3c.github.io/pointerevents/ spec then what one (where is CSS related spec for it)?

**Comment by patrickhlauke** [comment]
this is the repo for the JS Pointer Events API. for the CSS one, you'll likely want to file something against CSS-UI-4 (though I don't think `pointer-events` is in there yet, but certainly discussed) https://github.com/w3c/csswg-drafts/ (see https://wiki.csswg.org/spec/css4-ui#pointer-events)

**Comment by laukstein** [comment]
Thanks @patrickhlauke! I open https://github.com/w3c/csswg-drafts/issues/2012 for it.
