### ISSUE TITLE
Clarify that canceling pointerdown shouldn't affect to scrollbar handling

### ISSUE THREAD

**Issue by smaug----** [w3c/pointerevents#236]
This is a bit weird case, since I guess scrollbar handling in general is not spec'ed.
Canceling pointerdown does prevent mousedown to fire, but should not affect to scrollbar scrolling.

Gecko bug https://bugzilla.mozilla.org/show_bug.cgi?id=1447196

**Comment by NavidZ** [comment]
We talked about this issue in the call and we agreed to keep the pointerevents spec as is regarding the default actions of pointerdown here in this spec and not list the ones that are not. This issue might be better be discussed in uievents maybe.
