### ISSUE TITLE
Same table style for CSS touch-action property?

### ISSUE THREAD

**Issue by saschanaz** [w3c/pointerevents#254]
It's harder to programmatically detect CSS property definitions in this spec than in CSSWG specs.

Comparing with [CSS Transitions](https://www.w3.org/TR/css-transitions-1/#transition-property-property) for example:

![image](https://user-images.githubusercontent.com/3396686/39566829-d69ebc98-4ef7-11e8-80c4-03381e4337fa.png)

We can use `dfn.css[data-dfn-type=property]` or `.propdef dfn` to get CSS property definitions in those spec, but currently in Pointer Events:

![image](https://user-images.githubusercontent.com/3396686/39567109-d8dbcbb2-4ef8-11e8-94bd-bed3ce32a398.png)

1. This is too general
2. It doesn't support `dfn` links

How about using the CSSWG style to define `touch-action`?

**Comment by patrickhlauke** [comment]
The CSS Transitions spec is generated using Bikeshed, which creates all those classes/ids. Pointer Events uses ReSpec, which is more limited in that regard. These would have to be added manually throughout the HTML for consistency - it's not just a case of doing it for this one special case and applying the same CSS as the Transitions spec. For the time being, I think we'll have to pass. In future, we MAY want to move to Bikeshed if the group feels it is of more value? (personally, I found ReSpect a bit cryptic at times)

I have, however, added a `<dfn>` for the `touch-action` definition, for what it's worth https://w3c.github.io/pointerevents/#dfn-touch-action
