### ISSUE TITLE
Security & Privacy Section Removed Between April 4, 2018 and May 10th, 2018 Drafts

### ISSUE THREAD

**Issue by jasonanovak** [w3c/pointerevents#255]
In comparing the April 4, 2018 and May 10th, 2018 Drafts of the Pointer Events Level 2 Specification, it looks like the Security & Privacy Section was present in the April 4, 2018 draft and removed in the May 10, 2017 draft.

[Issue 252](https://github.com/w3c/pointerevents/pull/252) was meant to address some feedback from PING's review of the April 4, 2018, so unclear what happened between 252 and the May 10th drafts.

**Comment by patrickhlauke** [comment]
@plehegar any idea why the published version doesn't match https://w3c.github.io/pointerevents/ ?

**Comment by patrickhlauke** [comment]
the published version is missing quite a few other minor changes/revisions present in the editor's draft from 26 April

**Comment by patrickhlauke** [comment]
Fixed now. https://www.w3.org/TR/2018/CR-pointerevents2-20180522/ / https://www.w3.org/TR/pointerevents2/

Thanks for spotting and reporting it @jasonanovak
