### ISSUE TITLE
Concern about "InvalidPointerId" DOMException.

### ISSUE THREAD

**Issue by yuki3** [w3c/pointerevents#256]
Web IDL defines DOMException with many kinds of names.  See [Web IDL 2.7.1. Error names](https://heycam.github.io/webidl/#idl-DOMException-error-names).

Except for obsolete web standards, all other web standards (AFAIK) are using DOMExceptions defined in Web IDL and do not define DOMExceptions with own names.  I think that it's better to use DOMExceptions already defined in Web IDL instead of defining own "InvalidPointerId", or to define a new DOMException in Web IDL (not in Pointer Events standard) if it's really necessary.

By the way, AFAIK, "InvalidPointerId" is the only instance that doesn't end with the suffix "Error" among all DOMException names.

**Comment by patrickhlauke** [comment]
@NavidZ @mbrubeck as this is outside of my technical understanding/comfort zone, could you look into what's required here?

**Comment by patrickhlauke** [comment]
I'll add that those exception names were defined way back in Pointer Events Level 1 https://www.w3.org/TR/pointerevents1/, and reflect implementation reality from that time. Not sure if/how we can square these off now with the (newer?) Web IDL error names convention

**Comment by NavidZ** [comment]
I talked to @foolip as well about this. I believe following that format seems like a better idea. The only question is to whether add a new error or just reuse one. The closest one that caught my eyes was **NotFoundError**. I wonder what others think about it.

This should be an easy change in the browsers I guess as soon as we agree on an error. @smaug---- @patrickkettner WDYT?

**Comment by NavidZ** [comment]
I also checked the usage in http archive and it was about only 300 urls none of them I could recognized. Looking at some of their codes I realized they are all seem to be coming from jquery/pep anyway:
https://github.com/jquery/PEP/search?q=invalidpointerid&unscoped_q=invalidpointerid

and couldn't find actually catching the exception and handling it in any part of their code.

cc @scottgonzalez

**Comment by scottgonzalez** [comment]
PEP itself wouldn't ever listen for the error because it wouldn't run a browser that supports Pointer Events.

**Comment by NavidZ** [comment]
Yup. Exactly. I meant that those websites who do have InvalidPointerId are just using PEP which is firing that event and not an actual listener acting on it. This makes it easy to just change the error code. So we need to update PEP as well as the browsers after we land on a new error name.

**Comment by scottgonzalez** [comment]
Gotcha. Sounds good.

**Comment by smaug----** [comment]
NotFoundError should be fine.

**Comment by patrickhlauke** [comment]
I too believe `NotFoundError` seems appropriate. Unless I hear strong opposition, I'd like to merge the above PR (and I made a matching PR for PEP)

**Comment by patrickhlauke** [comment]
from the PEP PR discussion:

@NavidZ
> lgtm. But we also need to update this test later. I'll update it along with Chrome change unless @smaug---- beats me to it.
https://github.com/web-platform-tests/wpt/blob/master/pointerevents/pointerevent_setpointercapture_invalid_pointerid-manual.html

**Comment by NavidZ** [comment]
There were actually 2 tests that needed update. I fixed them both.
