### ISSUE TITLE
"When the pointer capture target override is removed from its ownerDocument's tree" should talk about target not being connected anymore

### ISSUE THREAD

**Issue by smaug----** [w3c/pointerevents#259]
I think we do want this work in Shadow DOM

**Comment by patrickhlauke** [comment]
@smaug---- is this something we want to do in v2, or is this a v3 thing? if the former, any suggestion how to do it / what you'd like to see in the spec?

**Comment by smaug----** [comment]
I think v2. 

https://fullscreen.spec.whatwg.org/#fully-exit-fullscreen is dealing with similar issue for fullscreen element, the part "Whenever the removing steps run with a removedNode, run these steps:" Something similar should be done for pointer capture target.

**Comment by patrickhlauke** [comment]
@smaug---- would you mind just having a punt at drafting what this could look like in practice? or perhaps @NavidZ ?
