### ISSUE TITLE
Remove myself as editor and add NavidZ?

### ISSUE THREAD

**Issue by RByers** [w3c/pointerevents#263]
Hey all,
With my increasingly pointy hair, I haven't really spent any time directly on pointer events in the past year, I think it's misleading to continue to list me as an editor. So I propose removing myself.

@NavidZ has long been the one on the Chrome team really leading our pointer events efforts and proposing the most edits. I propose we add him as an editor to reflect that. 

Please let me know (here or private e-mail if you prefer) if you have any concerns / objections.

/cc @patrickhlauke @mbrubeck

**Comment by patrickhlauke** [comment]
i was pondering this recently. you HAVE been editor for a good chunk of 2.0, but yes @NavidZ has done stellar work as well as you moved into the shadows. Wonder if there'd be objections to listing you both (just as the spec is, hopefully, now pushing over the finish line shortly)?

**Comment by RByers** [comment]
I have no objection to that - add Navid now, remove me after 2.0 goes out the door to reflect that I'm not active in post-2.0 work.

**Comment by patrickhlauke** [comment]
@mbrubeck any objection?

**Comment by mbrubeck** [comment]
No objection here! I have been an absentee editor myself...

**Comment by patrickhlauke** [comment]
it's all good. will do the PR tomorrow :)

**Comment by patrickhlauke** [comment]
@NavidZ could you let me know your w3cid? see https://github.com/w3c/echidna/wiki/How-to-use-Echidna-with-ReSpec-and-GitHub#the-editor-ids

**Comment by patrickhlauke** [comment]
@NavidZ as you were...managed (via a circuitous route) to find your w3cid

**Comment by NavidZ** [comment]
My id is 92361. But I can see you already found it. Thanks :)

**Comment by RByers** [comment]
Awesome, thank you @patrickhlauke!
