### ISSUE TITLE
tiltX and tiltY aren't as helpful as just having altitude angle

### ISSUE THREAD

**Issue by grorg** [w3c/pointerevents#274]
Pointer Events for a stylus currently use `tiltX`, `tiltY` and `twist` to give the orientation of the stylus in space. I believe that just `twist` and `altitude` would be sufficient for most cases, and easier to understand.

`altitude` is the angle between the screen surface and the stylus, ignoring the rotation or twist. Many styluses don't have an "up" direction around the barrel (e.g. Apple Pencil), so spinning the stylus in your fingers shouldn't change any values. Most drawing applications therefore just use the angle between the screen and the stylus to determine the angle of the painting nib, and the direction in which the stylus is "falling" for direction. Mapping those from `tiltX` and `tiltY` is confusing. It also makes those values dependent on the twist.

**Comment by grorg** [comment]
`twist` is defined as "The clockwise rotation (in degrees, in the range of [0,359]) of a transducer (e.g. pen stylus) around its own major axis".

Unless I'm misunderstanding, this value would always be zero for an Apple Pencil. The stylus's own major axis is irrelevant to this device - what's important is how the stylus is oriented to the surface.

I think polar coordinates make much more sense than a tiltX and tiltY in applications (and it's only the angle part of the polar coordinate that matters).

**Comment by grorg** [comment]
This also means an app that expects to get values for `twist` (say with a stylus that does have an orientation around the Z axis when standing straight up), won't work correctly with an app that doesn't provide values. i.e. a painting app would orient the nib shape around the twist, but instead should use tiltX and tiltY.

I could be wrong! It's a bit confusing.

Either way, I still think the idea of a polar rotation from the Y-Z plane (called `azimuthAngle`) and the smallest angle between the surface and the stylus (called `altitudeAngle`) makes more sense for apps.

**Comment by dfleck** [comment]
There are two common APIs:
xTilt, yTilt, and twist
or
altitude (angle between stylus and surface), azimuth (“compass” direction of tilt), and twist

twist is axial rotation of the stylus, and is the least supported (it usually requires an additional electrode or coil). Twist is important for non-symmetrical brushes (think chisel tip marker where moving with the stylus vertical could result in a narrow line, or a wider line when there is a 90 degree twist)

Due to the detection method (in most cases a series of X and Y electrodes or coils) what is natively measured is xTilt and yTilt. This is often converted to azimuth and altitude with simple trig. Twist has nothing to do with this transformation.

Depending on the brush, both altitude and azimuth can be important. Take an airbrush for example. When vertical (altitude = 90 degrees) the brush is circular and azimuth doesn't matter. However it becomes somewhat oval and directional (spraying away from the tip) when altitude isn't 90 degrees. When the stylus is tilted, the direction of the oval spray depends on the azimuth (but does not depend on twist with a round nozzle).

**Comment by grorg** [comment]
Right. So why are we using `tiltX` and `tiltY`? Apps want altitude and azimuth. Why force the devs to do the trig?

**Comment by dfleck** [comment]
The hardware reports xTilt and yTilt because doing floating point trig on an eight bit micro with no math coprocessor is very time consuming.
Some people want raw data so they can decide what processing and what precision is necessary (if you only want altitude and not azimuth you don't need to compute both).
Sometimes you want xTit and yTilt (such as correcting coordinates based on tilt).

**Comment by grorg** [comment]
What hardware? iOS certainly does not provide xTilt and yTilt.

Not all hardware uses an eight-bit micro and, even then, every event here is going through the browser engine, where the overhead from the trig function is going to be negligible compared to the event dispatch, the call into JavaScript, and then the processing JavaScript will do. This is premature optimization to the extreme.

Again, since most apps will want azimuth and altitude, it makes more sense to serve those values and let the smaller number of apps that want tiltX and tiltY to calculate that as needed.

**Comment by grorg** [comment]
https://developer.apple.com/documentation/uikit/uitouch

👆 An example of an API that gives the developers what they mostly want rather than the raw values.

**Comment by dfleck** [comment]
> What hardware? iOS certainly does not provide xTilt and yTilt.

The sensor hardware. Even with an Apple pencil the touch sensor measures xTilt and yTilt.

> Not all hardware uses an eight-bit micro and, even then, every event here is going through the browser engine, where the overhead from the trig function is going to be negligible compared to the event dispatch, the call into JavaScript, and then the processing JavaScript will do. This is premature optimization to the extreme.

Everything going thru the browser engine went thru the OS first, and the low level native API is usually xTilt, yTilt (Windows, Mac, and Linux).
https://docs.microsoft.com/en-us/uwp/api/windows.ui.input.pointerpointproperties.xtilt

> Again, since most apps will want azimuth and altitude, it makes more sense to serve those values and let the smaller number of apps that want tiltX and tiltY to calculate that as needed.

The Wacom Wintab API provides both and developers can choose. In this situation this would provide backward compatibility.

**Comment by patrickhlauke** [comment]
so, for both backwards compatibility and "giving developers what they want" (though, is this backed up by data on developer wants? or purely on "since on this platform there's only this type of data, this is what they want"?), would a way forward be to provide these as additional properties? which would then require browsers to backfill/calculate the data that isn't currently provided by the low-level APIs?

**Comment by grorg** [comment]
> > What hardware? iOS certainly does not provide xTilt and yTilt.

> The sensor hardware.

Yes, but that's irrelevant. We don't provide the sensor data. We don't tell the app what the voltage measured in the sensor is, for example.

The Web exposes APIs that make sense to developers, and in this case the Pointer Events specification provides the less useful information.

>  Even with an Apple pencil the touch sensor measures xTilt and yTilt.

This highlights my point. Apple doesn't expose that to the developer. It exposes azimuth and altitude, because that makes more sense.

> > Not all hardware uses an eight-bit micro and, even then, every event here is going through the browser engine, where the overhead from the trig function is going to be negligible compared to the event dispatch, the call into JavaScript, and then the processing JavaScript will do. This is premature optimization to the extreme.

> Everything going thru the browser engine went thru the OS first, and the low level native API is usually xTilt, yTilt (Windows, Mac, and Linux).

No. It seems to be tilt on Windows. Not on iOS.

And again, the Web doesn't expose the low-level sensor data. It exposes a programming API.

> > Again, since most apps will want azimuth and altitude, it makes more sense to serve those values and let the smaller number of apps that want tiltX and tiltY to calculate that as needed.

> The Wacom Wintab API provides both and developers can choose. In this situation this would provide backward compatibility.

I'm fine with exposing both. As I'm implementing it right now, I might just do it.

**Comment by grorg** [comment]
> "giving developers what they want" (though, is this backed up by data on developer wants? or purely on "since on this platform there's only this type of data, this is what they want"?)

This is a valuable question! Thanks for asking it. I didn't provide any data.

So let's think about the common apps that would use a stylus. We can ignore everything that only needs the x,y locations (which is probably the majority of apps... because the user is on a stylus and the app just treats it like a regular touch).

Of the "specialised for stylus" apps, I suggest the most common involve painting of some kind. That means they are trying to emulate a brush or nib, so the important inputs are:

- the pressure at the tip
- the orientation of the nib around the surface
- the angle between the surface and the stylus

i.e. pressure, azimuth and altitude

Giving them tiltX and tiltY just means they have to do calculations.

So what apps would actually want tiltX and tiltY? I guess some kind of simulation (e.g. surgery). But even then, if they are trying to represent a physical object, then the vectors they are interested in are better represented by the azimuth and altitude.

**Comment by dfleck** [comment]
> so, for both backwards compatibility and "giving developers what they want" (though, is this backed up by data on developer wants? or purely on "since on this platform there's only this type of data, this is what they want"?), would a way forward be to provide these as additional properties? which would then require browsers to backfill/calculate the data that isn't currently provided by the low-level APIs?

Good question. I imagine there is a legacy bias "I wrote this decades ago on an SGI and X Windows has always provided tilt so I dealt with it".

Proving both has "pain equity" since both platforms need to calculate something. Platforms with tilt need to compute altitude azimuth, and platforms with altitude azimuth need to compute tilt. ;-)

**Comment by dfleck** [comment]
Something else. The resolution on tilt is often only one degree (remember, this is the raw starting point in the hardware). So if you want to control two independent things you really need to use tilt (which gives you a clean +- 60 values for each - independently). With altitude and azimuth the resolution of azimuth depends on the altitude value. At one degree off vertical, azimuth can only represent roughly every 45 degrees.

I've seen tablet to MIDI music applications where this was important.

**Comment by grorg** [comment]
I'm happy to include both. I'd send a pull request but I'm not officially allowed to contribute to the group at the moment :)

**Comment by grorg** [comment]
(BTW, given that the spec produces values in degrees rather than radians, there is definitely a lot of calculation happening before it ever gets to the JS level. And since the sensors produce a busy stream of noisy data, the amount of computation happening for each event way more expensive than calculating azimuth and altitude if you don't get them from the platform)

**Comment by k3a** [comment]
I've made a script to do the conversion between the two which may be useful:
https://gist.github.com/k3a/2903719bb42b48c9198d20c2d6f73ac1

* **spherical to tilt** is from Qt code but is quite obvious (projection to axes and using arctan to find angles)
* **tilt to spherical** was done by defining normal vectors of tilted planes, making the cross product of them to find the pen direction, converting it to spherical coordinates and matching angle orientation and offsets to match the *spherical to tilt* inputs.

A few observations:
* **tilt angles** have highest precision when the pen is nearly perpendicular to the screen/tablet
* in reality, the pen is held approximately 45 degrees tilted so there is little difference between the two
* Qt and Windows use tilt angles in degrees, iOS use spherical angles in radians

**Comment by dfleck** [comment]
Actually, users hold the stylus more vertical than 45 degrees. More like 62.4 degrees:
http://www.xiaojunbi.com/pdf/pta.pdf

It’s 76.3 degrees for a left handed person. (XTilt of 13 from vertical - but YTilt is all over the place due to the wide variety of left handed grips).

**Comment by patrickhlauke** [comment]
discussed this in today's PEWG meeting - we're aiming to draft out something for v3 to include both sets of variables - will circle back to this once we have something tangible

https://lists.w3.org/Archives/Public/public-pointer-events/2019JulSep/0034.html

**Comment by patrickhlauke** [comment]
@grorg see https://github.com/w3c/pointerevents/pull/316 ... does this initial naive PR sound appropriate/feasible?

**Comment by grorg** [comment]
@patrickhlauke thanks for the ping and sorry for the delay.

Yep, this looks good.

**Comment by patrickhlauke** [comment]
Perfect, thanks @grorg
