### ISSUE TITLE
`touch-action: none` definition is too vague

### ISSUE THREAD

**Issue by graouts** [w3c/pointerevents#276]
The spec for the [`touch-action`](https://w3c.github.io/pointerevents/#the-touch-action-css-property) property currently has this to say about its [`none`](
https://w3c.github.io/pointerevents/#details-of-touch-action-values) value:

> Touches that begin on the element MUST NOT trigger default touch behaviors.

The other values for the `touch-action` property concern themselves with panning and zooming, so it makes sense to conclude that those "default touch behaviors" may be related to panning or zooming, but there is no explicit mention of this specifically, nor is there a mention of user interactions around navigation and text. I think this spec should be clearer, even if only as a note, about what is the expected behaviour of `touch-action: none` on text for instance. Chrome on Android allows text selection and traversing a link by tapping on it, but it seems equally conformant to prevent text selection and link traversal.

**Comment by patrickhlauke** [comment]
Sorry Antoine, only getting to this now. I've proposed a rewording/clarification here now, but - to give a bit of history - the vagueness of the definition came down to walking the fine line of IPR on what could and couldn't be directly stated in the spec (in terms of particular gestures that this CSS property tried to prevent). Hoping to provide some more clarity though if #349 is ok'd and merged.

**Comment by trusktr** [comment]
Comment moved to https://github.com/w3c/pointerevents/issues/387
