### ISSUE TITLE
Limit pointerrawupdate and getCoalescedEvents API to secure origins

### ISSUE THREAD

**Issue by NavidZ** [w3c/pointerevents#277]
@thiemonagel FYI
Both of getCoaelscedEvents and pointerrawupdate APIs expose some high frequency input and might expose some fingerprinting possibilities to the app.

Limiting this API to the secured origins makes sure only the intended origin has access to this data and no other malicious party over the network.

**Comment by smaug----** [comment]
If we want to do this, better to do it sooner than later, before non-secure context web pages start to use the APIs heavily. I could imagine some script libraries use the APIs and then one just uses those also outside secure context.
