### ISSUE TITLE
equivalent of rotationAngle from Touch Events?

### ISSUE THREAD

**Issue by patrickhlauke** [w3c/pointerevents#28]
Though hardware support doesn't seem all too great (I had to go on the hunt for a second-hand Nexus 10 in order to test/add this to my tracker demo), wondering if there's mileage in spec-ing something equivalent to Touch Events' `rotationAngle` in version 2? 

![tracker-touch-radius-rotation-force-hud](https://cloud.githubusercontent.com/assets/895831/11227078/d824d470-8d7b-11e5-989f-f9131de9e0fc.jpg)

If yes, how would this affect `width`/`height`? Would we still want to keep them as the rectangular bounding box (aligned with the screen axes), or modify them to act as `radiusX`/`radiusY`?

This may even be seen as a generalisation of https://github.com/w3c/pointerevents/issues/25 - not exclusive to pen/stylus, but to touch as well, as conceptually they're the same?

**Comment by RByers** [comment]
I'd rather not conflate this with #25 myself, they're not really the same thing.  For one, touch contact geometry has a range of 180° where pen rotation has a range of 360°.

I'm not opposed to adding this, but given that hardware and OS support is so rare I don't personally think it's worth it (AFAIK Android Nexus 10 would be the only platform that would benefit).  If hardware support were to increase then I'd consider it more important.

**Comment by patrickhlauke** [comment]
Closing this, as I'd rather see a proper implementation of #25 than TouchEvents' half-baked (in my opinion) `rotationAngle`
