### ISSUE TITLE
Setting pointer capture on an element in a parent frame when the pointer was made active in a child frame

### ISSUE THREAD

**Issue by graouts** [w3c/pointerevents#291]
The test [pointerevent_mouse_pointercapture_inactivate_pointer.html](https://github.com/web-platform-tests/wpt/blob/master/pointerevents/pointerevent_mouse_pointercapture_inactivate_pointer.html) specifically checks that handling a `pointerdown` event dispatched on a target element in a child frame and calling `setPointerCapture()` in the parent frame on an element contained in the parent frame should *not* trigger pointer capture. 

However, I'm not finding explicit text in the spec that would specify this behavior. The only step in [Setting Pointer Capture](https://w3c.github.io/pointerevents/#setting-pointer-capture) that should fails silently is:

> 4. If the pointer is not in the active buttons state, then terminate these steps.

But I can't see anything that specifies that, in this scenario, the pointer would not be in the active buttons state.

As it stands on [wpt.fyi](https://wpt.fyi/results/pointerevents/pointerevent_mouse_pointercapture_inactivate_pointer.html?label=master&label=experimental), I see Chrome and Edge pass this test, but Firefox and Safari do not.

**Comment by NavidZ** [comment]
@graouts You are right. It is not very clear how the active button state is defined with respect to the iframes. But how do you feel about the current behavior?

A little background on this. We realized if we had cross origin frames we didn't want the embedder or the embedded iframe call the setpointercapture if they didn't receive an active button state pointer before for security reasons. Not only that if they had received a leave event (like when pointer leaves their boundaries) we still didn't want them to be able to capture. So we thought we should not let the element that belongs to a document that doesn't have an active pointerevent in it be able to call capture. If we accept such a logic this test should also fail. As it really doesn't matter who is calling capture on the element in the embedder. Either a timeout or a function call from the inner frame. However, let's first see what you think about the behavior in general. @graouts do you think that is reasonable? @smaug---- in case this was missed before, what do you think?

**Comment by smaug----** [comment]
Given the current spec, nothing prevents setPointerCapture to occur, so the test is invalid.

How did that happen, invalid test landed to wpt. Hmm, some Google internal thing... https://github.com/web-platform-tests/wpt/commit/9d19b76509703231f5449f72c1ebf8f8bbf1bb7d#diff-a7cee0688ae91de031e5f94fff49e332  linking to some non-open design doc :/

That test should be removed from wpt until we've decided in the spec what the behavior should be.

**Comment by smaug----** [comment]
I'm not against limiting setPointerCapture to current domain, although that does prevent certain use cases. And a question is that should it be limited to the current document, or current domain.

**Comment by NavidZ** [comment]
> That test should be removed from wpt until we've decided in the spec what the behavior should be.

I don't mind either moving the test to the extension folder until we agree on a behavior about this. Also I believe @EiraGe just made that document public.

Regarding the use cases, what did you have in mind @smaug---- ? I'd like to know whether those would encourage any of domain vs document level capturing or not.

**Comment by EiraGe** [comment]
I'll have the test remove from WPT shortly. Sorry for the incorrect test :/

**Comment by smaug----** [comment]
Just some embedding scenario where some cross-domain widget would do something useful. One could pass pointerid via postMessage.
Same origin iframe case is probably more compelling, since there communication is synchronous.

Does Blink limit setPointerCapture to the document, or same origin iframes or what?

**Comment by NavidZ** [comment]
> Does Blink limit setPointerCapture to the document, or same origin iframes or what?

Our plan was to limit it to the document. There might be some bugs here and there and edge cases that we haven't caught yet but that was our plan and the current state as far as our tests say.

**Comment by EiraGe** [comment]
It may also have security concern for allowing capture in cross-domain widget: a frame may keep trying to capture mouse id or just random pointer ids without any postMessage.

**Comment by smaug----** [comment]
What does limiting to document mean? If an element with event listener for pointerdown is moved during event dispatch to another document and then handles the event, is it allowed to call setPointerCapture?
(Remember, event path is calculated before handling the event, so capturing event listeners for example can move targets in path to other documents)

**Comment by NavidZ** [comment]
I believe from the Blink implementation we do limit it to the document that belongs to the event path calculation (i.e. the document that the target belonged to at the time of hit-testing). But we certainly are open to other interpretations and changing this behavior if there are use cases for them

**Comment by NavidZ** [comment]
This issue was discussed in today's PEWG call and we decided to add the restriction of the activeness to the target's associated document (@NavidZ to send a pull request and we can discuss further on that). Although this seems to be restricted we decided to go with that for now to make sure abusive behaviours are not possible. But we keep an eye on this in case any valid use case rises in future. @graouts do you also agree with this approach? Although we can discuss better on a concrete proposal in the PR. So I'll send one soon.

**Comment by graouts** [comment]
@NavidZ That seems reasonable. Has a PR materialized yet? Feel free to Cc me.
