### ISSUE TITLE
Set touch-action to allow web pages opt out Android back gesture

### ISSUE THREAD

**Issue by LanWei22** [w3c/pointerevents#295]
Android Q starts building fully gestural system navigation to replace navigation bar buttons, when we are doing horizontal edge swipe from left or right, the Android system will make Chrome go back. Android provides a Gesture Exclusion Rects API which sets a list of areas where the Android system should not intercept touch or other pointing device gestures, and instead the web pages will consume the touch events and handle the pages as they expect. We are planning to call this API on the elements which are set to be touch-action "none" or "pan-y" without any "pan-x", "pan-left" or "pan-right", so that the touch events are all passed to the web pages and Android will not perform back gesture, or if touch-action is set to "pan-left" or "pan-right", right or left horizontal scrolling gestures are handled by the web pages. The Gesture Exclusion Rects API restricts edge length to 200 dp, so if the element’s height is more than 200 dp, we will make the bottom-most 200 dp as the exclusion region.

**Comment by patrickhlauke** [comment]
This sounds like it's a user agent implementation choice, not necessarily something that would/should be covered by the spec itself (unless I'm missing something?)

**Comment by LanWei22** [comment]
We will add this into the touch-action's spec, even though this does not change the current behavior of touch-action.

**Comment by patrickhlauke** [comment]
As a non-normative note, I'd assume?

**Comment by LanWei22** [comment]
Yes, as a non-normative note.

**Comment by NavidZ** [comment]
There is a similar edge swipe gesture on iPhone as well and I was wondering whether Apple folks have any comments regarding exposing such a control to the web apps. @graouts WDYT?

**Comment by graouts** [comment]
@NavidZ I don't think we'd be interested in this, application-level gestures should always be respected in my opinion.

**Comment by patrickhlauke** [comment]
Closing this based on the above discussion (that this is UA implementation, not directly related to PE) https://github.com/w3c/pointerevents/issues/295#issuecomment-523217128
