### ISSUE TITLE
Suggestion. pointer-events: disabled

### ISSUE THREAD

**Issue by ExtAnimal** [w3c/pointerevents#299]
Or some similar property value name.

`disabled` would mean no events at all. Not event from ancestor elements. No `:hover` behaviour either. Unreactive.

`none` means that pointer events "see through" the element and just start their bubble and hover behaviour from the `parentNode`.

For some applications, you just want an element to be unreactive.

**Comment by patrickhlauke** [comment]
`pointer-events` CSS property has, confusingly, nothing to do with the Pointer Events API. suggest you post this on https://github.com/w3c/csswg-drafts/issues
