### ISSUE TITLE
Spec implies mice can't support pressure

### ISSUE THREAD

**Issue by RByers** [w3c/pointerevents#30]
The spec says: 

> For hardware that does not support pressure, including but not limited to mouse, the value must be 0.5 when in the active buttons state and 0 otherwise.

Which implies it's impossible for a mouse to support pressure.  Force-touch touchpads on Mac OS are a real-world example that violates this, and I think we should plumb force out to `PointerEvent.pressure` on Mac OS.

Can we just remove the "including but not limited to mouse"?  Or replace it with "(for example, most mice)"?

**Comment by patrickhlauke** [comment]
proposing "(such as most traditional mouse and trackpad inputs)"

using "inputs" here because i find "mice", though of course correct plural form, somehow weird when talking about the computer hardware (and possibly not immediately understandable to non-native english speakers)

**Comment by scottgonzalez** [comment]
I'm not sure that the reference is needed at all, so I'm in favor of just removing it.

**Comment by RByers** [comment]
Thanks Patrick.  Either option is fine with me.

**Comment by RByers** [comment]
Let's land Patrick's PR for now as a step in the right direction, but keep this issue open until there is consensus...

**Comment by patrickhlauke** [comment]
i can see @scottgonzalez' point that it's perhaps redundant to even list examples of hardware that doesn't support pressure as it's implicit. then again, it kind of makes this more immediately clear to me (and now part of me also want to crowbar in traditional touchscreens ;) )

**Comment by scottgonzalez** [comment]
My main concern with this wording is that over time this statement may become meaningless to new developers. We already have legacy references in HTML with `<input type="radio">` which has absolutely no implicit meaning to a large portion of developers. Input devices are changing fairly rapidly and the "traditional mouse" could easily become a relic while still being referenced in this spec.

**Comment by patrickhlauke** [comment]
Personally, I think the danger of obsolescence here (particularly as the term isn't used for an attribute name or value) is fairly low. For how do we feel then about the change made in #31 versus removing the parenthetical bit altogether? I have no major strong feelings either way.

**Comment by scottgonzalez** [comment]
I'd still prefer just removing the parenthetical, but I don't have very strong feelings either.

**Comment by RByers** [comment]
Either way is fine with me.

**Comment by patrickhlauke** [comment]
At two "whatever" and one "remove" (and nobody else appearing to have any opinion on it either way either), I'll make a PR to remove it :)
