### ISSUE TITLE
ReSpec error caused by MouseEventInit

### ISSUE THREAD

**Issue by patrickhlauke** [w3c/pointerevents#311]
Doing a bit of cleanup of some errors that creeped in after the merge of the extension, but am stuck with the last one.

"The term "`MouseEventInit`" is defined in `cssom-view`, `ui-events` in multiple ways, so it's ambiguous."

I thought the `data-cite` attribute we use for the IDL takes care of this, but apparently not...

```
<pre class="idl" data-cite="ui-events">
dictionary PointerEventInit : MouseEventInit {
...
</pre>
```

Anybody who's more ReSpec savvy than me have any pointers/ideas of how to resolve this last ReSpec error?

**Comment by smaug----** [comment]
I think https://drafts.csswg.org/cssom-view/#extensions-to-the-mouseevent-interface
