### ISSUE TITLE
CfC: Publication of PE3 as FPWD (ends 5 Dec 2019)

### ISSUE THREAD

**Issue by patrickhlauke** [w3c/pointerevents#312]
This is a call for consensus for publication of the Pointer Events Level 3 specification as First Public Working Draft (FPWD).

Deadline for this call for consensus is 5 December 2019 9am Boston time.

While there are still open issues at present, the major additions that were planned (coalesced events, raw pointer data, additional `touch-action` values) have now been merged into the working draft.

Positive replies/ +1s to this issue would be appreciated, but aren't necessary.

If you have concerns about this proposed consensus position that have not been discussed already and feel that those concerns result in you “not being able to live with” this decision, please let the group know before the CfC deadline.

**Comment by NavidZ** [comment]
+1

**Comment by patrickhlauke** [comment]
Not having received any negative replies to this, the CfC is passed. Thanks all.

**Comment by patrickhlauke** [comment]
Made the request for FPWD https://github.com/w3c/transitions/issues/201
