### ISSUE TITLE
should altitudeAngle default to 0 or pi/2 when not supported?

### ISSUE THREAD

**Issue by patrickhlauke** [w3c/pointerevents#320]
splitting this off from https://github.com/w3c/pointerevents/pull/316#discussion_r413854172

in short: in Touch Events, if the current touch is *not* from a stylus that supports altitudeAngle/azimuthAngle, both values are `0`. the theoretical case of a stylus lying completely flat/horizontal on the screen does not seem to actually happen - the stylus tip does not touch the digitizer in that scenario. so `0` seems a safe assumption for "not a stylus, or a stylus that doesn't support position/attitude information". presumably web apps that deal with stylus using Touch Events use this assumption today as well.

for pointer events, currently we also used `0` as default value. now, a more logical/safe approach may well be to say that the default should be either PI/2 (perpendicular stylus), or to provide a clear NaN or similar that signals it's not supported at all.

personally, i think it would be confusing if PE's `altitudeAngle` differed this dramatically from TE's `altitudeAngle`. but i can see the argument about authors simply wanting to plug a property into their code and have it default to something sensible.

would appreciate further thoughts/opinions on this.

**Comment by NavidZ** [comment]
Just to add one additional point. When the device doesn't support this stylus angle we set tiltX/Y to zero. Meaning we indicate the pen is straight. If we set altitude/azimuth to 0 as well it shows that the pen is parallel to the surface. Then these two coordinate system at least in the case of the device not supporting them are going to differ and show two different states of the pen.

**Comment by patrickhlauke** [comment]
ah, good catch. this could at least be used as a sensible justification beyond "just because we don't like it / think it makes sense" in TE vs PE

**Comment by patrickhlauke** [comment]
Decided on today's call https://lists.w3.org/Archives/Public/public-pointer-events/2020AprJun/0050.html that it does make sense to go for a value of `pi/2` for the `altitudeAngle` when no sensor is present/no value is provided by the platform (compared to `0` in Touch Events as the default value).

We should consider adding a prominent warning there in the spec so authors don't miss this divergence from Touch Events.

**Comment by patrickhlauke** [comment]
Addressed in https://github.com/w3c/pointerevents/pull/323/
