### ISSUE TITLE
It is not possible to generate one set of angle values from other set

### ISSUE THREAD

**Issue by NavidZ** [w3c/pointerevents#321]
@patrickhlauke @smaug---- @liviutinta

Based on the latest spec we have the following line:
"When an untrusted (synthetic) Pointer Event is created programmatically using the constructor, and only one set of values is provided, the complementary set of attributes MUST be calculated and initialized"

But apparently based on the current bindings and how the default dictionary values are set we cannot do that. Mainly all the values are present in the PointerEventInit (either when user explicitly set them and if not with their default values as per current spec).
After talking to @domenic, it seems that they expect all the constructors to be dummy setters from dictionary values and if we want to achieve the behavior we described we need to also patch the binding generation from idl and also [dom spec](https://dom.spec.whatwg.org/#concept-event-constructor).

I wonder if we can come up with an easier solution here.

**Comment by patrickhlauke** [comment]
this probably causes a little conundrum at least for `tiltX`/`tiltY` as `0`/`0` is a valid actual value (while, as discussed in the other thread, it seems that no device actually allows for/recognises a completely flat stylus, so `altitudeAngle`/`azimuthAngle` of `0`/`0` can be assumed to be default/not provided).

just spitballing, but some kind of wording that says that all values need to be provided. but that the browser should then compare the two. if one of the pairs is `0`/`0` and the other pair then has a valid set of values, it should assume that the latter are the only values actually provided and then backfill the set that is `0`/`0` appropriately? and note that for `tiltX`/`tiltY` values of `0`/`0` can also be legit, so if those are zero but the altitude/azimuth are also zero, assume the tilt values actually do carry meaning?

starts getting a bit convoluted, but...

**Comment by domenic** [comment]
I think it's worth taking a step back here and asking what you're trying to accomplish. The browser is never going to fire an event with inconsistent values, right? Because you specced it that way. That seems important.

But you're not working on the specification for browser-created events. You're working on the spec for author-created events. What are you trying to accomplish there?

In particular, what are the use cases for author-created events that auto-computation of the complementary values helps with?

**Comment by patrickhlauke** [comment]
@domenic from my perspective, what I'd like to achieve is:
* we've crammed two different ways of describing a stylus/pen/pencil spatial orientation into the spec, because different authors will find either method easier/more aligned with what feels more natural to them (and it mirrors two different low-level APIs available on different platforms and the kinds of values they return)
* we want to avoid forcing authors having to calculate both representations of a particular orientation they want when defining synthetic events - as the whole point was that authors can choose either the `tiltX`/`tiltY` or `altitudeAngle`/`azimuthAngle` way of looking at it because it's most natural/suitable/convenient to them in their app, it would then seem odd to require them to pre-calculate themselves what both representations are.

The idea with the events is (based on the latests changes) that regardless of what the browsers get from the OS, they calculate the matching pair of values themselves. I'd like the same convenience (and speed) for synthetic events generated by authors somehow.

**Comment by domenic** [comment]
Can you say more about what the use cases are for synthetic events, and how they benefit from this convenience?

**Comment by patrickhlauke** [comment]
well, what are the scenarios in general for any synthetic events being generated? (synthetic mouse events, synthetic touch events, etc)

**Comment by domenic** [comment]
That's what I'm asking you...

**Comment by patrickhlauke** [comment]
assuming that you ask the same question to UI Events folks etc for why THEY would want to synthesize events...but i'll take a first stab: when authors want to "fake" events (like in automated testing), simulate one type of device/input (e.g. a pen/stylus) when the user's actually using another input like a mouse, some form of remote control type application where inputs from one device are sent and then simulated on another?

**Comment by domenic** [comment]
OK. So, how do those cases benefit from this convenience? It seems like test code would not test the properties that it does not synthesize. (Doing so would just be testing the browser's conversion algorithm, which is not very useful.)

**Comment by patrickhlauke** [comment]
tests are only one case (and browser tests themselves are arguably still a valid case?). and keeping in mind that this may not be happening in isolation: one developer may be generating synthetic events that may then be consumed by other scripts not in the author's direct control (which may expect/want the other set of values)

**Comment by domenic** [comment]
> tests are only one case

Could you expand on the others, so we can figure out how to best serve them?

> (and browser tests themselves are arguably still a valid case

I'm not discussing browser tests (which are done in C++ and unrelated to synthetic events); I'm saying that it's not useful to test the browser's logic when writing tests for your web platform application.

> keeping in mind that this may not be happening in isolation: one developer may be generating synthetic events that may then be consumed by other scripts not in the author's direct control (which may expect/want the other set of values)

Can you explain a use case where this might happen? So far you've mentioned tests, but that doesn't seem to meet this definition.

**Comment by patrickhlauke** [comment]
>  simulate one type of device/input (e.g. a pen/stylus) when the user's actually using another input like a mouse, some form of remote control type application where inputs from one device are sent and then simulated on another?

these weren't tests that i mentioned.

**Comment by patrickhlauke** [comment]
> I'm not discussing browser tests (which are done in C++ and unrelated to synthetic events);

web platform tests?

**Comment by domenic** [comment]
> these weren't tests that i mentioned.

I see! In that case, it sounds like it would be convenient to have a way to generate correct values for converting between the representations. Perhaps a separate utility class or namespace?

**Comment by NavidZ** [comment]
> Perhaps a separate utility class or namespace?

@domenic do you have an example of such functions in other specs? Is that for example going to be a function in window.PointerEvent interface or something?

**Comment by domenic** [comment]
Static functions on the `PointerEvent` interface make sense to me. I'm not aware off the top of my head of many other examples of unit conversion functions on the web platform, but perhaps something in CSS; I know they have a lot of units.

**Comment by NavidZ** [comment]
@patrickhlauke do you think this is good enough of a solution? It is not as clean interface as just having an attribute on PointerEvent object similar to TouchEvent but at least that solved the issue we are having in implementation.

**Comment by patrickhlauke** [comment]
@NavidZ sure, i'm just not quite sure how that would be documented/how it would manifest itself in the spec...and I guess then the conversion algorithm pseudocode section would/should be turned more into a suggested "how user agents should implement these conversion functions" section. in principle though yes, sounds reasonable.

**Comment by NavidZ** [comment]
We would need to add those functions to the specification. Alternatively we can just have getAzimuth and getAltitude functions on PointerEvent which just returns its angle in these forms. So instead of saying PointerEvent.azimuth they'd have to call PointerEvent.getAzimuth and would get the same thing. But the attribute is not going to be in PointerEventInit dict anymore and no way for the developer to initialize the PE with azimuth/altitude.

There is one caveat with respect to this solution that is rare but I'd like to put it out there at least. For now pens are only on the top of the surface and can never be meaningfully parallel to the surface. So tiltX/Y seems fine in these cases. But in the future if there are some stylus devices that support like the whole sphere, the plane that is parallel to the surface tiltX/Y will have problems that one set like tiltX/tiltY=0 could represent any position on the parallel plane to the surface but Azimuth/Altitude can express exactly where the pen is. So if we only allow developers to create synthetic events with tiltx/y they will not be able to express these states correctly.

**Comment by patrickhlauke** [comment]
@NavidZ do our recent changes cover this now?

**Comment by NavidZ** [comment]
Yes. This should be all good now.
