### ISSUE TITLE
The behavior of `touch-action: none` on <iframe> is unclear

### ISSUE THREAD

**Issue by graouts** [w3c/pointerevents#325]
I just fixed a WebKit test ([bug 213846](https://bugs.webkit.org/show_bug.cgi?id=213846)) which made the assumption that interacting with the content of an `<iframe style="touch-action: none">` that is part of a scrollable document would prevent scrolling. As it turns out, WebKit's implementation did not prevent scrolling in this case and Chrome's behavior is similar. However, this does not match my expectation as an author and I don't think the current specification explains this case's behavior clearly.

**Comment by mustaqahmed** [comment]
This is the repro from the webkit bug: https://codepen.io/mustaqahmed/full/yLeZKpP

**Comment by patrickhlauke** [comment]
Discussed on PEWG call today https://www.w3.org/2020/07/22-pointerevents-minutes.html#item03 - more investigation (to also see what Firefox Mobile currently does here). May lead to note about this apparently unintuitive behavior, or to a change in behaviour?

**Comment by mustaqahmed** [comment]
I started working on a test for this and hit a test-driver hiccup.  So I made the test manual in my my CL pointed above.  I will try to make it automatic sometime next week.

**Comment by smaug----** [comment]
Firefox seems to behave the same way as Chrome when touch-action: none is on the iframe element.
I don't think there is anything unclear there. The contents of iframe is a separate browsing context after all, why would iframe affect to the behavior there.

**Comment by staktrace** [comment]
It could be confusing/unclear because of the discrepancy with `pointer-events:none`, which *does* apply to the contents of the iframe when set on the iframe element.

**Comment by smaug----** [comment]
That is true. I couldn't however find any definition how pointer-events: none; is supposed to work with nested browsing contexts. Is it just that browsers happen to work in a certain way or am I missing some spec?

**Comment by mustaqahmed** [comment]
Yesterday we landed a WPT for `touch-action:none` on `iframe` matching the common behavior in Chrome, Firefox and Safari.

For `pointer-events:none`, I suggest opening a new issue.  Regardless of what browsers do, I have a naive question: isn't an `iframe` supposed to be an "un-crossable" border for CSS rules?

**Comment by staktrace** [comment]
I'm not sure if it's specced; I did a quick search but didn't find anything.

**Comment by patrickhlauke** [comment]
As discussed in meeting today, added a minimal note to the spec about this - hope that's sufficient (though admittedly very handwavy)
