### ISSUE TITLE
Specify exactly how event coalescing works

### ISSUE THREAD

**Issue by smfr** [w3c/pointerevents#328]
The Pointer Events spec at https://w3c.github.io/pointerevents/#dfn-coalesced-event-list talks about coalesced event lists, but there's no description of exactly how event coalescing works.

What are the start/end points of coalescing in terms of the HTML event loop (https://html.spec.whatwg.org/multipage/webappapis.html#event-loop-processing-model)?

**Comment by smaug----** [comment]
Some of the coalescing could happen outside HTML event loop, for example in a different process, so I'm not sure whether this can be defined in terms of  the HTML event loop.

**Comment by smaug----** [comment]
What kind of clarification would be useful in the spec (assuming it doesn't rely on HTML event loop or such)?

**Comment by smfr** [comment]
Too long ago; I've lost context.

**Comment by patrickhlauke** [comment]
@smaug---- do you think it's worth attempting some form of definition, or is this outside of the scope of the spec (in which case we should explicitly say that it's not defined here, possibly point to some other event handling spec?)

**Comment by patrickhlauke** [comment]
I believe this can be closed / is superseded by this https://github.com/w3c/pointerevents/issues/361
