### ISSUE TITLE
Please don't <dfn> Element

### ISSUE THREAD

**Issue by annevk** [w3c/pointerevents#333]
This specification created a conflicting definition for the Element interface. Could you please remove that?

It's breaking build scripts from other specifications, e.g., https://github.com/whatwg/fullscreen/pull/187.

**Comment by annevk** [comment]
This also applies to Navigator, see https://github.com/whatwg/storage/pull/114. :-(

**Comment by patrickhlauke** [comment]
I have no idea what the expected format/markup should then be ... @plehegar any ideas?

**Comment by annevk** [comment]
It seems this was caused by 598cbef3474b343c0926eca98881cbf5ff4fdf54 but I guess until recently this document did not get indexed so it didn't cause ecosystem-wide problems. Instead of using `<dfn>` for these interfaces locally, you want to use whatever mechanism ReSpec has for referencing terms in other specifications.

**Comment by patrickhlauke** [comment]
@marcoscaceres wonder if you'd be able to help me out - admittedly I've only been cargo-culting respec and never really understood what it does/what it expects

**Comment by plehegar** [comment]
I poked at this but can't figure it out :(. The use of "partial interface Element" is appropriate as far as I can tell. Respec automatically exports WebIDL definitions so that's why sheperd sees it. We could drop data-dfn-fr but then I don't know how to reference it anymore.

**Comment by annevk** [comment]
@plehegar the problem is not the partial, it's the heading above. I.e., "Extensions to the Element interface" contains a `<dfn>` that wraps "Element". Similar for Navigator.

**Comment by marcoscaceres** [comment]
As a general rule, "if you don't own it, don't `dfn` it... you can {{Link}} [=to=] `<a>`it`</a>`".
