### ISSUE TITLE
How pointer capture should behave on draggable element?

### ISSUE THREAD

**Issue by EdgarChen** [w3c/pointerevents#338]
For example,
```html
<div id="target" draggable="true">drag me</div>
<script>
let target = document.getElementById("target");
target.addEventListener("pointerdown", function(e) {
  target.setPointerCapture(e.pointerId);
});
</script>
```
https://codepen.io/edgarchen-the-decoder/pen/wvWaNOd

Spec seems to not define how pointer capture should behave while setting pointer capture on a draggable element. 
Both Chrome and Safari would stop pointer capture while dnd is triggered, Firefox basically does the same thing in most of the time, there is an inconsistency if we set pointer capture in `mousedown` handler, see https://bugzilla.mozilla.org/show_bug.cgi?id=1669673, but we plan to fix that to have consistent behavior.

**Comment by patrickhlauke** [comment]
wondering if this should be spec'd/defined in the PE spec, or in the relevant DND spec / living standard. @smaug---- @NavidZ thoughts?

**Comment by NavidZ** [comment]
Latest version of Pointerevents does define that to behave as you see in Chrome and Firefox. It is defined [here](https://w3c.github.io/pointerevents/#the-pointercancel-event). Basically if browser/platform takes over input stream (in this case when dragging starts) you are not going to receive any more input events from that stream. This part is already defined in DnD spec. So here we would send a cancel pointer event which cancels capture as well. If you do want to continue receiving events for that input stream and continue having the capture you need to cancel drag and drop by preventing default dragstart event.

**Comment by patrickhlauke** [comment]
oh, goodness, you're right...forgot we already mention drag operations (which explains why this topic rang a bell but i didn't find any open issues).
