### ISSUE TITLE
Order of pointer events across frames when using pointer capture 

### ISSUE THREAD

**Issue by liviutinta** [w3c/pointerevents#355]
Regarding https://wpt.fyi/results/pointerevents/pointerevent_pointercapture_in_frame.html%3Fpen?label=experimental&label=master&aligned, in test 4 (Test penpointer capture in same-origin frame: Pointerdown with set capture at outer frame, then release on next pointermove).

There are two frames, outerframe and innerframe. The inner frame is a same-origin frame. 
At pointerdown we call setPointerCapture on the outerframe, and at first pointermove event we call releasePointerCapture on outerframe, and pointerup in the innerframe. 
The usual order of events is (we only track pointerdown/gotpointercapture/lostpointercapture/pointerup and the first pointermove after pointerdown):
- outerframe pointerdown
- outerframe gotpointercapture
- outerframe pointermove
- outerframe lostpointercapture
- innerframe pointerup

However, when running the test against Chrome, I sometimes see the following order, and the test fails because of it:
- outerframe pointerdown
- outerframe gotpointercapture
- outerframe pointermove
- innerframe pointerup
- outerframe lostpointercapture

From reading the Pointer Events spec, I wasn't able to understand if there is a certain ordering of pointer events from the same sequence across frames. 
Is it fair to say that pointer events from the same sequence should be ordered per frame and not across frames?

**Comment by smaug----** [comment]
(This was discussed during a call.)
Given that the windows belong to the same [similar-origin window agent](https://html.spec.whatwg.org/#similar-origin-window-agent) and an agent has an [event loop](https://html.spec.whatwg.org/#create-an-agent), it is surprising to see different behavior in iframes vs non-iframes.  It should behave as if there was just one page.
And @flackr hinted that this might be a pen handling specific issue in Chrome, so this issue feels mostly an implementation issue.

Please reopen if we misunderstood the issue or there is something unclear.

**Comment by mustaqahmed** [comment]
For records: this is an interop problem affecting all major browsers: see the [WPT dashboard](https://wpt.fyi/results/pointerevents?label=master&label=experimental&aligned&view=subtest&q=pointerevent_pointercapture_in_frame.html), and the bugs for [Mozilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1700234) and [Chromium](https://crbug.com/1186788).

cc: @DavMila
