### ISSUE TITLE
Clarify when lostpointercapture should fire

### ISSUE THREAD

**Issue by smaug----** [w3c/pointerevents#357]
This is split from https://github.com/w3c/pointerevents/issues/75
The spec is contradicting itself whether lostpointercapture should fire before or after click.
[implicit-release-of-pointer-capture](https://w3c.github.io/pointerevents/#implicit-release-of-pointer-capture)

"if in an implicit release scenario both click and lostpointercapture events are fired, click SHOULD be fired before lostpointercapture."
(note, that is just "SHOULD")

vs

"Immediately after firing the pointerup or pointercancel events, a user agent MUST clear the pending pointer capture target override for the pointerId of the pointerup or pointercancel event that was just dispatched, and then run Process Pending Pointer Capture steps to fire lostpointercapture if necessary."
(Note, this is using "MUST")

Chromium seems to fire click first, Gecko and Webkit fire lostpointercapture first.
[Testcase](https://output.jsbin.com/zuwiwep) Click on blue.

**Comment by EdgarChen** [comment]
My two cents: if the pointer capture affects the click targets, it seems to make sense to fire `click` event before `lostpointercapture`.

**Comment by patrickhlauke** [comment]
Mentioned briefly in today's call. Parking this issue until #356 has been fleshed out more

**Comment by smaug----** [comment]
Resolution is to fire lostpointercapture before the click, since click target is calculated already when firing pointerup - no matter whether it is implicit or explicit release.

**Comment by smaug----** [comment]
This was fixed as part of https://github.com/w3c/pointerevents/pull/474

**Comment by mustaqahmed** [comment]
Looks like `pointerevent_click_during_capture.html` needs to be updated: the spec now says `click` should be after `lostpointercapture` as per this [comment](https://github.com/w3c/pointerevents/issues/357#issuecomment-1601040840).

**Comment by mustaqahmed** [comment]
Done with WPT.
