### ISSUE TITLE
Clarify that pointer event listeners are passive by default

### ISSUE THREAD

**Issue by patrickhlauke** [w3c/pointerevents#360]
Split from https://github.com/w3c/pointerevents/issues/359#issuecomment-819828218

**Comment by patrickhlauke** [comment]
@mustaqahmed @smaug---- is there some IDL-specific way of denoting this in the spec? or is this just something that can be done with prose somewhere?

**Comment by smaug----** [comment]
It is not a WebIDL level thing. 
But I'm not sure where it has been said that the listeners would be passive.

(certain touch events and wheel event on the document and body and so are passive.)

**Comment by patrickhlauke** [comment]
yeah wondering if this is more of a heuristic/implementation suggestion (i.e. an informative note), or if it's always true due to the fact that pointer events are non-blocking by their nature (unless there's some `touch-action` shenanigans I guess?)

**Comment by mustaqahmed** [comment]
Idea of passive event listeners is defined [here](https://dom.spec.whatwg.org/#dictdef-eventlisteneroptions) in the DOM Standard.

I think the best statement in that [other discussion you linked](https://github.com/w3c/pointerevents/issues/359#issuecomment-819828218) would have been "pointerevent listeners are _always_ passive".  This is because (to guarantee browser responsiveness) a script can never `preventDefault` the browser behavior in response to a PointerEvent; the script has to declare a `touch-action` region instead.

Perhaps the `touch-action` intro section deserve a link to the spec?  Not sure though.

**Comment by NavidZ** [comment]
Just to add to this regarding passiveness. I also commented something about this [there](https://github.com/w3c/pointerevents/issues/359#issuecomment-823274011).

I guess to be more accurate they are not passive (in the way that DOM spec [says](https://dom.spec.whatwg.org/#dom-addeventlisteneroptions-passive)) as you can prevent default a pointerdown and it will cause the corresponding mouse events not to fire. But the default action of pointerevents have nothing to do with scrolling as already [specified](https://www.w3.org/TR/pointerevents2/#attributes-and-default-actions) in the PointerEvent spec. Although not explicitly called out that scrolling is not part of the default action.
Just a note that if you do add a `passive: true` to pointerevent listener the `preventDefault` on that doesn't work and compat mouse events [always fire](https://jsbin.com/meyocuqugu/edit?html,console,output).

**Comment by patrickhlauke** [comment]
> Just a note that if you do add a `passive: true` to pointerevent listener the `preventDefault` on that doesn't work and compat mouse events always fire.

this is new, and i don't think defined anywhere? this definitely should be added in the spec if it's supposed to be normative (and we need a test for this as well). or is it just a heuristic that blink does?

**Comment by NavidZ** [comment]
> this is new, and i don't think defined anywhere? this definitely should be added in the spec if it's supposed to be normative (and we need a test for this as well). or is it just a heuristic that blink does?

No this is not new. I just tested it with Safari and Firefox and they all do the same as what Blink does today. This is what I expect from the `passive: true` in the event listener as defined in the DOM spec. Meaning that the default action of the event will run regardless of whether the handler calls preventDefault or not. So I assume we are inline with how passiveness is spec'ed already and nothing to add to PointerEvent spec.

Our default action in this case I'm testing is [dispatching compat mouse events](https://w3c.github.io/pointerevents/#ref-for-dfn-compatibility-mouse-events-11:~:text=Authors%20can%20prevent%20the%20production%20of,events%20by%20canceling%20the%20pointerdown%20event.) and calling `preventDefault` does prevent it. But if we add `passive: true`  mouse events continue firing despite `preventDefault`.

**Comment by mustaqahmed** [comment]
Thanks @NavidZ for clarifying.  My comment above narrowly focused on browser panning only (deleted to avoid creating confusion).
