### ISSUE TITLE
Move glossary to the end of the spec

### ISSUE THREAD

**Issue by patrickhlauke** [w3c/pointerevents#362]
Traditionally, a glossary comes at the end of a piece of writing/book. Currently, we have it right at the start, which is a bit unusual. I'd propose moving it to the end, after "Converting between `tiltX`/`tiltY` ..."

**Comment by patrickhlauke** [comment]
See for instance other specs like https://www.w3.org/TR/WCAG/#glossary

**Comment by chaals** [comment]
The Glossary *might* help a first-time reader, but for most people reading, having it near the start moves the most valuable content further away. That seems backwards.

**Comment by smaug----** [comment]
But isn't the actual content closer to infrastructure, which is at the beginning of the modern specs
https://dom.spec.whatwg.org/#infrastructure https://html.spec.whatwg.org/#toc-infrastructure

**Comment by patrickhlauke** [comment]
> Traditionally, a glossary appears at the end of a book and includes terms within that book that are either newly introduced, uncommon, or specialized

https://en.wikipedia.org/wiki/Glossary

At least that's the way I've always understood glossaries. And, as @chaals mentioned, to me the glossary currently stands between the reader and getting to the actual "meat" of the spec. If they do then encounter a term they're unfamiliar with, they can follow the link to the glossary.

**Comment by smaug----** [comment]
UIEvents spec has glossary at the end. So I guess there is no consistency where glossary/infrastructure lives in the specs.
