### ISSUE TITLE
disambiguate default *action* and default *behavior* in prose

### ISSUE THREAD

**Issue by patrickhlauke** [w3c/pointerevents#368]
split from https://github.com/w3c/pointerevents/pull/349#issuecomment-811092269

[edit: modified this issue text to renumber the links to sections, for clarity, as the structure has changed since this was opened]

at the start of [8. Declaring candidate regions for default touch behaviors](https://w3c.github.io/pointerevents/#declaring-candidate-regions-for-default-touch-behaviors), it reads:

```
<p>For touch input, the default action of any and all pointer events MUST NOT be a manipulation of the viewport (e.g. panning or zooming).</p>
```

followed by the note:

```
Touch manipulations are intentionally not a default action of pointer events. Removing this dependency on the cancellation of events facilitates performance optimizations by the user agent.
```

It's unclear to me, as a reader, what this actually means/refers to. What concept is this trying to convey? I'm guessing it's essentially saying here that panning/zooming is special and not counted as a "default action" in the sense of [4.1.3.1 Attributes and Default Actions](https://w3c.github.io/pointerevents/#attributes-and-default-actions), and that for this reason panning/zooming also can't be cancelled by cancelling/preventing the event. This may need a bit more clarification/expansion. Perhaps even foreshadowing what we say later about `pointercancel` being fired. And then leading into the actual reason for this whole section: "instead, authors can control how user agents should handle panning/zooming using the `touch-action` CSS property instead".

That first sentence (about "default action ... MUST NOT be a manipulation of the viewport...") then seems at odds with the first note in [8.1 The touch-action CSS property](https://w3c.github.io/pointerevents/#the-touch-action-css-property)

```
As noted previously, in the case of user agents that allow default behaviors (such as panning or zooming) for other pointer types...
```

In that note, I think we need to drop the mention of "default behaviors" since we just said previously that panning/zooming isn't counted as a default behavior.

**Comment by mustaqahmed** [comment]
Yeah, the "action" vs "behavior" difference is non-trivial and confusing.  It confused us twice already in #359 and #360, and before that you raised it a few times in our WG meetings.

The good thing is that the "default behavior" term is used _only_ in the touch-action section ([Sec8.1](https://w3c.github.io/pointerevents/#the-touch-action-css-property)).  After reading the whole thing again just now, I am now convinced that the term means one precise idea: "viewport manipulation".  The first para in [Sec8](https://w3c.github.io/pointerevents/#declaring-candidate-regions-for-default-touch-behaviors) indirectly says this.

Does replacing "default behavior" with "viewport manipulation" look like a reasonable first step here?

**Comment by patrickhlauke** [comment]
I think part as part of this, [4.1.3.1 Attributes and Default Actions](https://w3c.github.io/pointerevents/#attributes-and-default-actions) should clarify right away that viewport manipulations (panning/zooming) do *not* count as default action - already foreshadowing what is said at the start of [8. Declaring candidate regions for default touch behaviors](https://w3c.github.io/pointerevents/#declaring-candidate-regions-for-default-touch-behaviors). 

That sentence currently in 8 also could do with some tweaking.

> For touch input, the default action of any and all pointer events MUST NOT be a manipulation of the viewport (e.g. panning or zooming).

sounds odd. It's not that panning/zooming MUST NOT be a default action/something the browser does. but rather that for the purpose of pointer events (and particularly with respect to cancelability), panning/zooming viewport manipulation is not considered/counted as a default action, so it can't be canceled, which is *why* authors need to use `touch-action` instead if they want to prevent or otherwise influence this viewport manipulation behaviour as a result of a direct manipulation interaction on the part of the user.

and then yes, replace that "default behaviour" in the sentence in 8.1 with "viewport manipulation (panning/zooming)" sounds about right, and should hopefully reduce confusion.

I'll mull this over some more and make another PR.

(edit: also, I see I basically rehashed most of what I said in the thread opener here...apologies for repeating myself, but at least this shows me that my initial gut feeling still holds a few days later)
