### ISSUE TITLE
Do user agents only coalesce pointermove events relating to changes in position?

### ISSUE THREAD

**Issue by patrickhlauke** [w3c/pointerevents#375]
https://w3c.github.io/pointerevents/#coalesced-events states that

> For performance reasons, user agents may choose not to send a `pointermove` event *every time the position of a pointer is updated.*

Does this really only apply to *position* updates? Or do changes in other attributes ("i.e. button state, coordinates, pressure, tangential pressure, tilt, twist, or contact geometry", to borrow from the `pointerrawupdate` description) also get coalesced (and the non-coalesced events would have the more granular changes from those attributes)?

**Comment by smaug----** [comment]
Just looking at the implementation, Gecko may coalesce also when things like tilt or twist or pressure changes.

**Comment by flackr** [comment]
I would expect that every non-discrete field could /should be coalesced. I.e. in your original post the only thing I wouldn't expect to get coalesced would be the button state since that changes discretely. I believe blink does this by virtue of the button state change also causing discrete events to fire which forces us to flush the current coalesced event out first.

**Comment by patrickhlauke** [comment]
Discussed today to update to `not to send a pointermove event every time a non-discrete property (such as coordinates, pressure, tangential pressure, tilt, twist, or contact geometry) of a pointer is updated.`

**Comment by patrickhlauke** [comment]
may need glossary entry as well for discrete/non-discrete properties (in former also include `metaKey` etc inherited from mouse events)

**Comment by patrickhlauke** [comment]
Added the proposed update to the wording, plus a glossary definition for "discrete and coalesced properties", to https://github.com/w3c/pointerevents/pull/379
