### ISSUE TITLE
Clarify which steps constitute canceling a pointer

### ISSUE THREAD

**Issue by mustaqahmed** [w3c/pointerevents#400]
Currently the steps are listed vaguely in the `pointercancel` [section](https://w3c.github.io/pointerevents/#the-pointercancel-event).  We can improve both this section and the HTML spec reference to this section through defining a "pointer cancel" task that includes firing three events (`pointercancel`, `pointerout` and `pointerleave`) and releasing the capture.

This was suggested [here](https://github.com/w3c/pointerevents/issues/384#issuecomment-890219263).

**Comment by plehegar** [comment]
(originally related to https://github.com/whatwg/html/issues/6758)

**Comment by mustaqahmed** [comment]
Just sent out #437 for review, PTAL.
