### ISSUE TITLE
Lost pointer issue - spec or browser bug?

### ISSUE THREAD

**Issue by jakearchibald** [w3c/pointerevents#407]
https://static-misc-3.glitch.me/pointer-test/

On OSX 11.5.2 (at least), in Chrome 92, Firefox 91, Safari 14.1.2 I see these events:

1. Press down left mouse button somewhere on the page - `pointerdown`
1. With the left mouse button still down, click the right mouse button. This should open a context menu. - `contextmenu`
1. Release the left mouse button - no event
1. Click the left mouse button outside the context menu - no event

This means, as far as my code is aware, the left pointer is still down. I would have expected a `pointerup` or `pointercancel` for this pointer at some point.

If I click the left button after these steps, Chrome and Firefox fire a `pointerdown` and a `pointerup`, whereas Safari only fires the `pointerup`, as if it's 'correcting' for the stuck pointer.

Am I missing something, or is this a spec/browser issue?

**Comment by jakearchibald** [comment]
My workaround is to look out for a subsequent `pointermove` with a `.buttons` of 0 and synthesize a `pointercancel` if the pointer is currently considered 'down'.

The workaround isn't perfect, as you'll miss the next `pointerdown` in Safari as it doesn't fire an event for it. I guess you could continue to monitor `pointermove` and synthesize as `pointerdown` there too.

**Comment by vdwijngaert** [comment]
On Linux (Arch Linux, X server, KDE Plasma) and Chrome 92.0.4515.159, this is what I get:

![image](https://user-images.githubusercontent.com/772137/130968172-2ea18b77-38a1-482a-a71a-37fd6cc5a7a6.png)

1. Left click somewhere -> `pointerdown`
2. Right click -> `pointermove`, `contextmenu`
3. Release left click -> nothing
4. Click somewhere outside context menu -> `pointermove` & `pointerup`

**Comment by nstepien** [comment]
It also affects iframes, for example the youtube volume slider vs chat iframe:
- press left mouse button on the volume slider
- move the cursor on top of a chat iframe
  - => slider won't move anymore
- release left mouse button on top of a chat iframe
  - => the volume slider can still move

**Comment by jakearchibald** [comment]
@nstepien I think the iframe issue is different and is adequately solved by pointer capture https://static-misc-3.glitch.me/pointer-test/2.html

**Comment by nstepien** [comment]
Interesting, thanks.
I've been using `setPointerCapture` but its capture wasn't working when the cursor was outside an iframe, turns out `event.preventDefault()`... prevented that? Unexpected.
For reference: https://github.com/adazzle/react-data-grid/pull/2613/files

**Comment by jakearchibald** [comment]
> My workaround is to look out for a subsequent `pointermove` with a `.buttons` of 0 and synthesize a `pointercancel` if the pointer is currently considered 'down'.

In case anyone is doing the same thing, you'll need to work around Firefox, where `.buttons` is always 0 for touch-based pointer events. https://bugzilla.mozilla.org/show_bug.cgi?id=1729440

**Comment by patrickhlauke** [comment]
coming back a bit late to this, i'm guessing that if triggering the `contextmenu` were to send a proper `pointercancel` (https://github.com/w3c/pointerevents/issues/408) then this would resolve itself as well, as your script should also listen for that and "drop"/"forget" any hanging `pointerdown`s then. we'll have a look at this issue in the coming meetings
