### ISSUE TITLE
Should triggering the contextmenu with the mouse cause a pointercancel?

### ISSUE THREAD

**Issue by jakearchibald** [w3c/pointerevents#408]
https://static-misc-3.glitch.me/pointer-test/2.html

Open the console to see logging, and right click somewhere on the page to get a context menu.

On OSX 11.5.2, I only get a `pointerdown` for the pointer. Is this correct? I expected to get a `pointercancel` or `pointerup`.

If the pointer is captured, Chrome releases the capture on the next pointer move after the context menu is closed. Firefox and Safari don't release the capture until the next left click.

**Comment by jakearchibald** [comment]
My workaround is to look out for a subsequent `pointermove` with a `.buttons` of 0 and synthesize a `pointercancel` if the pointer is currently considered 'down'.

**Comment by patrickhlauke** [comment]
x-ref https://twitter.com/jaffathecake/status/1430843636703506434

as said on twitter, my gut feeling is that triggering context menu should fire `pointercancel`, as the user agent should determine that the pointer is no longer "on the page" per se, but in the context menu.

**Comment by jakearchibald** [comment]
> My workaround is to look out for a subsequent `pointermove` with a `.buttons` of 0 and synthesize a `pointercancel` if the pointer is currently considered 'down'.

Watch out for this bug https://bugzilla.mozilla.org/show_bug.cgi?id=1729440
