### ISSUE TITLE
touch-action - incorrect values in note for pull-to-refresh?

### ISSUE THREAD

**Issue by patrickhlauke** [w3c/pointerevents#41]
Currently in "9.1 The touch-action CSS property" we have

> For example, to implement a simple pull-to-refresh effect the document's `touch-action` can be set to `pan-x pan-down` whenever the scroll position is 0 and `pan-x pan-y` otherwise. This allows pointer event handlers to define the behavior for upward scrolls that start from the top of the document.

Shouldn't the first value (for scroll position 0) be `pan-x pan-up`, as you'd want to handle the down movement yourself for the pull to refresh?

**Comment by patrickhlauke** [comment]
thinking out loud...or is this a "natural scroll" (where you'd drag down) vs "traditional scroll behavior" (where you'd drag up) thing? on touchscreens/for touch, the natural behavior is likely the most prevalent.

**Comment by RByers** [comment]
This is always confusing.  Here's the spec language designed to clarify this today: 

> Directions are interpreted as the opposite of the physical movement in the screen co-ordinate space. For example, pan-right always corresponds to input event sequences where screenX is decreasing at the start of a scroll, which typically (ignoring iframes with rotation transforms) results in increasing scrollLeft values.

IIRC we debated a bit at the time about which interpretation to use but found this one was more consistent with other APIs (there's probably some GitHub issue / pull request history here if you want to go digging - we fixed this only a few months ago IIRC).

**Comment by patrickhlauke** [comment]
Ah, gotcha, I missed that clarification. It feels unnatural to me, but I guess if it does indeed provide more consistency, so be it.

I wonder though if the wording could be tweaked to make it a tad more explicit, and to tie in with the pull-to-refresh example further down. Something like:

> For example, `pan-up` always corresponds to input event sequences where typically (ignoring situations such as `iframe` containers with CSS rotation transforms) `screenY` is increasing (i.e. a gesture where a touch point moves down the screen).

**Comment by RByers** [comment]
You mean replace the `pan-right` example with this similar `pan-up` example in order to tie into the p2r example?  That's fine with me.  Having both would be feel redundant etc (since it's just an example of the general rule).

**Comment by patrickhlauke** [comment]
Yup, that was my thinking. Also, quite unscientifically thinking (because of pull-to-refresh being a very commonly known paradigm/thing) that this example may be more grokkable and relatable. Will PR in a moment...

**Comment by danburzo** [comment]
I was just reading through the spec and had the same reaction to the _pull-to-refresh_ example. The explanation on how to interpret direction-specific _touch-action_ values seems to have disappeared in the meantime (probably part of [this PR](https://github.com/w3c/pointerevents/pull/238/files)). Can we reinstate that para?

**Comment by patrickhlauke** [comment]
> Can we reinstate that para?

afraid not, as it was moved out of the normative spec itself, since there was not sufficient consensus on it.

**Comment by danburzo** [comment]
Got it. Thanks for the pointer!
