### ISSUE TITLE
clarify what happens if touch-action is changed dynamically

### ISSUE THREAD

**Issue by patrickhlauke** [w3c/pointerevents#42]
It's probably implicit in the prose for "9.1 The touch-action CSS property", but: what should happen if, on `pointerdown`, the `touch-action` for the element is changed dynamically (for instance, from `auto` to `none`, based on the document's scroll position, for a naive pull-to-refresh implementation)? I assume that at that point, it's already too late and the user agent determined what to do (whether to handle the pointer/gesture or not) based on what `touch-action` was the moment when `pointerdown` was fired...if so, would it be useful to clarify this in a note?

**Comment by patrickhlauke** [comment]
Guessing this sentence (as part of the note for the direction-specific pan values) is, essentially, what I'd like to see generalised as a separate note?

> It's not possible to change the behavior of a pan in the middle of an operation.

So in essence, that it's not possible to change the behavior of any "gesture" (if that's the most appropriate word) after it has already started (either being handled by browser, or passed on to be handled by JS)

**Comment by RByers** [comment]
Yep, that's right.  I remember bikeshedding about the wording way back.  There's a few places this makes it in, but I agree it could be stronger:

> When a user touches an element...
> ...  for touches that begin on the element.

If you want to also add an explicit note about this, that's fine with me.
