### ISSUE TITLE
Inconsistent ordering of `pointerleave` events during touch interactions

### ISSUE THREAD

**Issue by dfreedm** [w3c/pointerevents#431]
The [pointerup](https://www.w3.org/TR/pointerevents/#the-pointerup-event), [pointercancel](https://www.w3.org/TR/pointerevents/#the-pointercancel-event), and [pointerleave](https://www.w3.org/TR/pointerevents/#the-pointerleave-event) events all specify that `pointerleave` must be sent after `pointerup` or `pointercancel` for interactions that do not support hovering.
However, multiple vendors (Chromium and Firefox at least) are dispatching `pointerleave` immediately after `pointerup`, and before `click`, which is incompatible with the [mapping for devices that do not support hover](https://www.w3.org/TR/pointerevents/#mapping-for-devices-that-do-not-support-hover).

Example: 
![Screen Shot 2022-02-07 at 10 58 03 AM](https://user-images.githubusercontent.com/46725/152853630-fee41a32-0b3b-46bb-b76a-73d5bea533b4.png)
https://marred-traveling-crustacean.glitch.me/

Is the suggested mapping in the spec supposed to be a normative mapping, or should it reflect what vendors have implemented?

**Comment by patrickhlauke** [comment]
The spec is indeed normative in this regard. For devices that don't support hover, there MUST be a `pointerout` and then a `pointerleave`.

It does indeed look like in Chrome/Android, Firefox/Android, and even Safari/iOS, only `pointerleave` is fired after the `pointerup`, and that `pointerout` is missing.

Unless I'm missing something, this looks like an implementation issue. /cc @smaug---- @mustaqahmed 

[if there *is* a good reason why implementations are not following the spec, we should instead patch the spec's normative wording]

**Comment by dfreedm** [comment]
Actually, I wasn't tracking `pointerout`, but my main point is that I expect the order to be
```
pointerenter
pointerdown
pointerup
click
pointerleave
```

instead of 

```
pointerenter
pointerdown
pointerup
pointerleave
click
```

**Comment by patrickhlauke** [comment]
ah sorry, i clearly went off on a tangent there and missed the actual point.

so your demo doesn't even log `pointerout` (so suspect that if it did, it would show it coming straight after `pointerup`.

your concern is about the `click`? in which case no, what's listed there in the mapping section https://www.w3.org/TR/pointerevents/#mapping-for-devices-that-do-not-support-hover is in a NOTE, which is non-normative (and was written ages ago, if memory serves ... probably before the time the whole "MUST fire `pointerout` and `pointerleave`" part of the spec was nailed down).

I'll update the NOTE to make it match reality, as yes it's only there as a suggested order, and that suggestion now clearly clashes with what the spec says normatively earlier on.

sorry for the confusion

**Comment by patrickhlauke** [comment]
(and yes confirming that when tracking `pointerout` as well https://buttercup-solar-soil.glitch.me/ the event sequence does have `pointerout` in the correct place in all tested browsers)
