### ISSUE TITLE
Pointerup and mouseup events stop firing when the click was started on top of another element on Chromium based browsers.

### ISSUE THREAD

**Issue by ecations** [w3c/pointerevents#433]
Pointerup and mouseup events are behaving in an unexpected way in Chromium based browsers when the click is started on top another element. In Firefox they seem to work.

You can view the issue in the codepen below. Click on the upper div, hold the mouse button down and move the cursor to the second div. You might get one pointerup to fire, but then it stops working until you click on the second div. After clicking on the second div, it will work once. If you drag from the side where there are no divs, then it works more often:

https://codepen.io/noip/pen/BammGdw?editors=1111

**Comment by patrickhlauke** [comment]
you're triggering some text-selection/drag and drop. adding `user-select:none;` on your containers there fixes the issue. you'd be more likely to see the problem with some actual content inside the two `<div>`s, but it seems Chrome also does its drag'n'drop selection dance when there's effectively no content there to drag'n'drop.

**Comment by ecations** [comment]
Thank you, user-select:none; helped. Isn't it a bit weird to stop detecting pointerup events just because there is dragging going on?
