### ISSUE TITLE
Moving an element to a different place in the DOM tree loses pointer lock and pointer capture

### ISSUE THREAD

**Issue by guillaumebrunerie** [w3c/pointerevents#439]
If an element currently has pointer lock or pointer capture active and we move it at a different place in the DOM tree (for instance using `Node.insertBefore`), then it loses pointer lock/capture. I believe it should not lose it.

The specification says:
> When the [pointer capture target override](https://w3c.github.io/pointerevents/#dfn-pointer-capture-target-override) is no longer [connected](https://dom.spec.whatwg.org/#connected) [[DOM](https://w3c.github.io/pointerevents/#bib-dom)], the [pending pointer capture target override](https://w3c.github.io/pointerevents/#dfn-pending-pointer-capture-target-override) and [pointer capture target override](https://w3c.github.io/pointerevents/#dfn-pointer-capture-target-override) nodes SHOULD be cleared and also a PointerEvent named lostpointercapture corresponding to the captured pointer SHOULD be fired at the document.

but I guess it isn’t entirely clear on whether `Node.insertBefore` causes the node to no longer be connected (?)

Here is an example: https://codepen.io/Latcarf/pen/NWXjYNb.
Try to drag the "Drag me" box, you’ll notice that it works fine when dragging to the right but pointer lock is lost as soon as we drag one step to the left. The same happens with pointer capture. The difference between right and left is that the element itself is moved when dragging to the left, but the element to its right is moved when dragging to the right.

I’m not sure if it is a bug in the specification or in web browsers (or if I misunderstood something), but I tested it in Chrome, Safari and Firefox on Mac OS X Catalina, and all three exhibit the same behavior.

**Comment by smaug----** [comment]
There is no such primitive in DOM as "move". Node is always first disconnected and then possibly connected again.
DOM spec is clear on this
https://dom.spec.whatwg.org/#concept-node-insert calls https://dom.spec.whatwg.org/#concept-node-adopt
which does "If node’s [parent](https://dom.spec.whatwg.org/#concept-tree-parent) is non-null, then [remove](https://dom.spec.whatwg.org/#concept-node-remove) node."

**Comment by guillaumebrunerie** [comment]
Ok, wouldn’t it still make sense that if a DOM node is disconnected and then connected again immediately/soon(?) after, then the pointer capture/pointer lock state should be preserved?

**Comment by smaug----** [comment]
That doesn't happen with other APIs either. For example if you move iframe to another place, the page it has is effectively reloaded.
There has be discussions over the years, or should I say over the [decades](https://bugzilla.mozilla.org/show_bug.cgi?id=254144), to support "move" in some way, but no one has come up with anything too concrete yet.
I think there are some open DOM or HTML spec issues discussing about this too.

**Comment by guillaumebrunerie** [comment]
Thank you for the explanation and the pointers :)
