### ISSUE TITLE
Should the spec really reference tracker anymore?

### ISSUE THREAD

**Issue by RByers** [w3c/pointerevents#45]
The spec status currently says:

> Action items to be completed are tracked in Tracker.

Can we just officially say GitHub issue are our only source of tracking now?  If we want to do that, someone probably needs to go through the [open tracker items](https://www.w3.org/2012/pointerevents/track/) and make sure anything still relevant has a GitHub issue.

**Comment by patrickhlauke** [comment]
Referencing GitHub would be my preference, too - unless that breaks W3C protocol somehow @shepazu ?

**Comment by patrickhlauke** [comment]
Can we even just drop that whole sentence? looking quite unscientifically at other drafts like https://w3c.github.io/webcomponents/spec/custom/ I think they don't even have that...

**Comment by RByers** [comment]
I'd be happy to drop the sentence, but only after we've filed GitHub issues for any outstanding work we shouldn't forget about from tracker.
