### ISSUE TITLE
pointerrawupdate missing in "Attributes and default actions"

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/pointerevents#451]
https://w3c.github.io/pointerevents/#attributes-and-default-actions lists all the events but `pointerrawupdate`; in particular, it's not clear whether that event is supposed to bubble and is cancellable.

**Comment by patrickhlauke** [comment]
thanks for raising this @dontcallmedom, we'll discuss this at the next WG meeting tomorrow

**Comment by patrickhlauke** [comment]
discussed at meeting today. will add the omitted row to the table
