### ISSUE TITLE
Respec's "Latest published version"

### ISSUE THREAD

**Issue by patrickhlauke** [w3c/pointerevents#46]
Looking at https://w3c.github.io/pointerevents/, respec currently generates the following

> Latest published version:
> http://www.w3.org/TR/pointerevents-level-2/
> Latest editor's draft:
> https://w3c.github.io/pointerevents/
> Latest Recommendation:
> http://www.w3.org/TR/pointerevents

Obviously, the "Latest published version" URL currently 404s. Anybody versed enough in the dark arts of respec know how this can be fixed (taking inspiration, perhaps, from the markup used for http://w3c.github.io/touch-events/) ?

**Comment by patrickhlauke** [comment]
Just changing

```
shortName:            "pointerevents-level-2",
```

to

```
shortName:            "pointerevents",
```

would do the job, but is it...semantically correct?

**Comment by RByers** [comment]
IIRC @jacobrossi and I discussed this when the spec was renamed.  I think the conclusion was that leaving it as-is was semantically correct, despite the broken link (there have not been any "published" versions of "pointer events level 2" yet).  Should be able to find the history of this discussion somewhere....

**Comment by patrickhlauke** [comment]
wondering then if there's some extra setting/incantation in respec to suppress the "latest published version" ... some way of saying that at this stage there's only an editor's draft, and no actual published version. i'm sure there must be something...

**Comment by shepazu** [comment]
We could solve this by doing a FPWD for http://www.w3.org/TR/pointerevents-level-2/.

Do we think we could do this sometime soon?

**Comment by patrickhlauke** [comment]
@shepazu 

> Do we think we could do this sometime soon?

If you let me know what's needed, from an organisational standpoint, my gut feeling would be that we could... (he said naively)

**Comment by shepazu** [comment]
How about a telcon? https://lists.w3.org/Archives/Public/public-pointer-events/2016JanMar/0169.html

**Comment by patrickhlauke** [comment]
Closing, as this will be resolved as soon as the FPWD is published
