### ISSUE TITLE
Coordinates of a `pointercancel` event

### ISSUE THREAD

**Issue by mustaqahmed** [w3c/pointerevents#463]
I think the spec should say that the coordinates of a `pointercancel` event are uninitialized (or zeros).

Chrome does not initialize the coordinates of a `pointercancel` event, which seems logical because the event is tied to a specific `pointerId` and not related to a specific pointer location.  For example, if a touch-drag causes scroll (and therefore the firing of a `pointercancel` event), the user agent absorbs the last `pointermove` events to determine the scroll amount etc and the page is not expected to know those event locations.  Developers can cache the last `pointermove` for that `pointerId` if there is any use.

We have a [Chrome bug](https://bugs.chromium.org/p/chromium/issues/detail?id=724013) about it which we are planning to close soon.

**Comment by smaug----** [comment]
Coordinates of touchcancel aren't clear either. Worth to test what implementations do there
https://w3c.github.io/touch-events/#event-touchcancel
I'm not yet quite sure what the behavior should be here.

**Comment by smaug----** [comment]
@flackr noticed Touch events spec does have https://w3c.github.io/touch-events/#dom-touchevent-changedtouches

**Comment by patrickhlauke** [comment]
Made an initial stab at clarifying this https://github.com/w3c/pointerevents/pull/464

While we didn't discuss it at the meeting, I added something about coalesced/predicted events there too (tl;dr: `pointercancel` has empty lists). Let me know if this makes sense or not, we can amend this.

**Comment by mustaqahmed** [comment]
Thanks @patrickhlauke for creating the PR reflecting our last meeting's decision, this highlights a questionable difference between our decision vs what we do for a touch `pointerup`.  Let me elaborate.

A touch `pointerup` is very similar to a touch `pointercancel` because each of them represents a moment the touch-point has become effectively non-existent for the page.  From this perspective, if the `pointercancel` event carries all attributes of the last seen `pointermove`, the same should hold for a touch `pointerup` too because an up means the touch-contact is gone. 
 This would be in conflict with both:
- the current spec (which explicitly mentions `pointerup` pressure to be zero, and we [decided similarly](https://github.com/w3c/pointerevents/issues/225) for few other attributes of `pointerup`), and
- current implementations (a very fast swipe on Firefox Android logically shows an updated coordinates in `pointerup` vs the last `pointermove`).

Now an additional point, which is perhaps more important here: looking back at the main motivation behind our decision, I think our comparison with `touchcancel` coordinates was not precise because that spec is silent about the coordinates of the `TouchEvent` itself!  The [`changedTouches`](https://w3c.github.io/touch-events/#dom-touchevent-changedtouches) specifies the last known location of individual `TouchPoint` in the "group", and says nothing about the location of the "group" (i.e. the group "called" `ToucheEvent`).  In particular, whenever there are two `changedTouches`, the coordinates of the `TouchEvent` remains logically inconclusive!

---

Because of both of these, it now seems to me that a `pointercancel` should not be required to "copy" last event's data.  I am now in fact biased to go as far as suggesting the simplest requirement that "this event carries no data other than `pointerId`", for sake of being more readable and concise for the developers who won't lose anything with such a change.

Thoughts?

**Comment by patrickhlauke** [comment]
> this highlights a questionable difference between our decision vs what we do for a touch pointerup. 

that's why I always like to do even speculative/strawman PRs, just so it's easier to visualise in context 😄 
I'll have another look over this myself with some fresh eyes. Just going by what you wrote here though, the argument that it is essentially the same/similar to `pointerup` is a compelling one, and would make sense/keep the same internal logic.

**Comment by mustaqahmed** [comment]
In today's meeting, we agreed to go with the change.

**Comment by mustaqahmed** [comment]
Just realized that we still need a spec line about the coordinates in a `pointercancel` event.

Edited: we decided to "copy" the coordinates of the last dispatched event instead of zeroes, right?
