### ISSUE TITLE
Investigate if `tangentialPressure` is correctly implemented/working in browsers/documented appropriately in spec

### ISSUE THREAD

**Issue by patrickhlauke** [w3c/pointerevents#467]
Related to the initial email I sent to the list about the Wacom airbrush pen https://lists.w3.org/Archives/Public/public-pointer-events/2023JanMar/0041.html which now led me down a strange rabbit hole.

Wondering if we could spend some time:

* checking if/how the behind-the-scenes plumbing in Chrome/Firefox has been done, and whether it's correct or not (not spec-related)
* whether or not we may need to add some more information/description to our definition https://w3c.github.io/pointerevents/#dom-pointerevent-tangentialpressure (spec-related)

Related links/issues

* where `tangentialPressure` was first mentioned by @dfleck and what HID value it uses https://github.com/w3c/pointerevents/issues/25#issuecomment-152013055
* PDF version of the HID specification https://www.usb.org/sites/default/files/documents/hut1_12v2.pdf (at least I *think* this is the relevant/most up-to-date one)
* Apple's `tangentialPressure` documentation https://developer.apple.com/documentation/appkit/nsevent/1525959-tangentialpressure (which solidified our choice for the name/decision to actually implement this in spec)
* split-out issue to add `tangentialPressure` to the spec https://github.com/w3c/pointerevents/issues/70
* actual PR that added `tangentialPressure` https://github.com/w3c/pointerevents/pull/87
* a check on browser implementation of `tangentialPressure`, and @mustaqahmed's comment about it shipping https://github.com/w3c/pointerevents/issues/192#issuecomment-291603884

(and for reference, the Wacom Airbrush Pen https://estore.wacom.com/en-US/wacom-airbrush-pen-kp400e2.html - note the "finger wheel" feature)

**Comment by patrickhlauke** [comment]
Note that for testing, you should be able to use https://patrickhlauke.github.io/touch/pen-tracker/ (i've hooked it up to show `tangentialPressure` as a value once you start interacting with the demo using a tablet/pen)

![Screenshot of the pen tracker and the Wacom diagnostic utility, when using a Wacom airbrush pen - tangentialPressure is shown as 0, but in the diagnostic tool the 'Wheel' property shows an actual value](https://user-images.githubusercontent.com/895831/222411330-f4840459-557a-49d1-b726-ee89e991145d.png)

**Comment by patrickhlauke** [comment]
@mustaqahmed @smaug---- let me know if I should explicitly file bugs anywhere about this (presumably in https://bugs.chromium.org/p/chromium/issues/list and https://bugzilla.mozilla.org/ respectively), or if you're happy (?) to check internally first

**Comment by patrickhlauke** [comment]
also, some more info on how the finger wheel is actually used: in essence, it's just an additional sensor on the airbrush, and does not *replace* pressure. users generally map/remap what it does in applications - by default, I believe that apps like Photoshop have the wheel mapped to pressure (changing opacity, so essentially *replacing* the purpose of tip pressure, which is then ignored/not mapped to opacity anymore), but it's up to users - some remap it so that tip pressure still affects the usual opacity of a stroke, and the wheel is used to set brush size for instance.

**Comment by smaug----** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1372097 says it was implemented on Firefox/Mac, and I don't see any code for it on non-Mac platforms.

**Comment by patrickhlauke** [comment]
@smaug---- @mustaqahmed following on from our quick discussion at today's meeting, I can confirm that `tangentialPressure` is actually handled correctly on Chrome/macOS and Firefox/macOS - so the problem may be in the integration for Windows (not able to test for Linux at this point)

<img width="1152" alt="Screenshot 2023-03-15 at 22 49 01" src="https://user-images.githubusercontent.com/895831/225462754-41a965c4-2e55-497e-be80-c26f89556da4.png">
<img width="1152" alt="Screenshot 2023-03-15 at 22 45 35" src="https://user-images.githubusercontent.com/895831/225462756-4ddbf261-c3ca-4ca1-93c6-fdba1dc23e33.png">

Safari/macOS does not currently recognise the Wacom stylus as an actual `pen` device, and just reports it as `mouse`. I guess it's a long shot to ask if @graouts is in a position to share if there's an intention of implementing this in webkit or not...

**Comment by patrickhlauke** [comment]
(incidentally, @smaug---- ... found a bug with Firefox/macOS and its `tiltY` while testing this https://bugzilla.mozilla.org/show_bug.cgi?id=1822714)

**Comment by mustaqahmed** [comment]
On Windows, did you mean it's broken on both Chrome and Firefox?

Too many variations here, it would be nice to have a table of impl status across [major browsers] x [major OSes].

**Comment by patrickhlauke** [comment]
@mustaqahmed on Windows, `tangentialPressure` shows just `0` in both Chrome and Firefox. On macOS, `tangentialPressure` works correctly in Chrome and Firefox. all with latest stable release OS and browser version.

macOS/Safari doesn't even know what a `pen` device. it recognises the Wacom stylus just as a mouse, and `tiltX`, `tiltY`, `tangentialPressure`, `pressure` are all `0`

**Comment by patrickhlauke** [comment]
@mustaqahmed remind me...is there a chrome bug about this `tangentialPressure` on Windows already, or do you want me to file one?

@smaug---- similar question...is there already a firefox bug for this on Windows, or do you want me to file one too?

**Comment by mustaqahmed** [comment]
I couldn't find any existing Chromium bug, looks like we need to file one at crbug.com/new.

**Comment by patrickhlauke** [comment]
I'll get on that later tonight, @mustaqahmed

**Comment by patrickhlauke** [comment]
@mustaqahmed filed a bug against Chrome https://bugs.chromium.org/p/chromium/issues/detail?id=1426685

@smaug---- ditto for Firefox https://bugzilla.mozilla.org/show_bug.cgi?id=1823822
