### ISSUE TITLE
consider to change the behavior of getCoalescedEvents on non-SecureContext

### ISSUE THREAD

**Issue by smaug----** [w3c/pointerevents#472]
https://github.com/w3c/pointerevents/pull/318 landed quite awhile ago, but it isn't implemented, at least not in Firefox nor in Chrome.
We could change that so that in non-SecureContext the method was still there, but it would always just return the event itself, and not any coalesced events. That would be hopefully less risky change than unshipping the API altogether from non-SecureContext.

**Comment by mustaqahmed** [comment]
Thanks for noting this unfortunate situation.  I agree that the compat risk could be non-trivial.  What about collecting some real world data (on usage in non-secure contexts) to help our decision?

**Comment by smaug----** [comment]
That sounds reasonable.

**Comment by mustaqahmed** [comment]
Today we landed a [use-counter](https://chromium-review.googlesource.com/c/chromium/src/+/4666230) in Chrome to track its usage in non-secure contexts.  The data will be available from M117 Beta in late August and from Stable in late September.

**Comment by patrickhlauke** [comment]
Discussed in meeting today, this issue is resolved (as the spec already says about secure context only)

**Comment by mustaqahmed** [comment]
The usage in non-secure contexts is low, at around [0.00008% page visits](https://chromestatus.com/metrics/feature/timeline/popularity/4598) based on data from Chrome M117 (current Beta).  Today we agreed that it is safe to update the brosers to match the current spec.

I filed [this Chrome bug](https://crbug.com/1477325) to track deprecation and removal from Chrome in non-secure contexts.
