### ISSUE TITLE
What happens when an isPrimary pointer is removed?

### ISSUE THREAD

**Issue by patrickhlauke** [w3c/pointerevents#48]
Currently the spec does not explain what would happen if an isPrimary pointer is removed.
The scenario would be: imagine more than one touch pointer in the document, one of which isPrimary; the user lifts the primary finger, and that pointer disappears. Should the touch that came after the isPrimary one be promoted to now being the new primary?
My hunch would be that no, as at the start of the gesture/interaction, no new primary should be promoted/elected. This is not, however, made explicit (or even implicit) in the spec to date.

**Comment by NavidZ** [comment]
I agree that there is no explicit statement about this. However, this section
https://w3c.github.io/pointerevents/#dfn-the-primary-pointer

implies that for example for touch:
A pointer representing touch input is considered the primary touch input if its pointerdown event was dispatched when no other active pointers representing touch input existed.

which I guess prevents the promotion of any existing event to new primary. Also the last note in this section tries to bring up the case that user agent can fire pointer events in which no pointer is marked as a primary pointer. Maybe we can reword that note to add the scenario you are mentioning as well?
