### ISSUE TITLE
[chore] Failed job: Couldn’t find “non secure context“ 

### ISSUE THREAD

**Issue by plehegar** [w3c/pointerevents#481]
The automatic publishing is failing due to an [error during the build](https://github.com/w3c/pointerevents/actions/runs/6026562198/job/16387644368#step:3:809):
[[
[Error] Couldn’t find “non secure context“ in this document or other cited documents: [dom], [fetch], [html], [infra], [uievents], [url], and [webidl].
]]

**Comment by patrickhlauke** [comment]
I think that was an error in a PR (https://github.com/w3c/pointerevents/pull/480) that, in the end, we didn't need/wasn't published. There shouldn't be anything relating to this in the current main branch
