### ISSUE TITLE
Wide review for Pointer Events 3

### ISSUE THREAD

**Issue by plehegar** [w3c/pointerevents#482]
- [x] [Dated Working draft](https://www.w3.org/TR/2024/WD-pointerevents3-20240318/) available for wide review (currently March 18)
- [x] Send notifications to groups listed in [Charter coordination section](https://www.w3.org/2023/11/wg-pointer-events-charter.html#coordination): DAS WG, Touch Events CG, WebApps WG
- [x] A11y review https://github.com/w3c/a11y-request/issues/78
- [x] I18n review https://github.com/w3c/i18n-request/issues/229
- [x] Privacy review https://github.com/w3cping/privacy-request/issues/134
- [x] Security review https://github.com/w3c/security-request/issues/67
- [x] TAG review https://github.com/w3ctag/design-reviews/issues/941

See also [How to do Wide Review](https://www.w3.org/Guide/documentreview/) for additional instructions.

**Comment by patrickhlauke** [comment]
apologies, after TPAC i got sucked into a whole series of client engagements and droppped the ball...will look at this more closely in the coming weeks

**Comment by patrickhlauke** [comment]
With monstrous delay, I am now (that we sorted out what at first seemed like a small thing, but turned out to touch on all sorts of Shadow DOM etc aspect) looking at this. @plehegar reading over the "How to do Wide Review" document, I noticed this as the first step

> You must publish an updated technical report, with the Status of the Document indicating clearly that you're looking for wide review, before inviting review from other stakeholders. Our [tooling](https://github.com/w3c/transition-notifier/blob/main/notify.js) monitors publications and propagates notifications to [public-review-announce@w3.org](mailto:public-review-announce@w3.org) automatically (for example, [Candidate Recommendation Snapshot: Payment Request API (Call for Wide Review)](https://lists.w3.org/Archives/Public/public-review-announce/2021Jun/0008.html)).

Could you provide me with a hint of how/what exactly I need to do to the status in the document? I assume I need to change something in the respec metadata? Or somewhere else?

**Comment by plehegar** [comment]
In [index.html](https://github.com/w3c/pointerevents/blob/gh-pages/index.html), add the following to `section#abstract` :

```
  <p>This document is ready for wide review. Comments are welcome at any time but most especially before 1 April 2024.
```

You probably want to change that date :)

Then commit/merge and it will get published automatically.

**Comment by patrickhlauke** [comment]
Thank you @plehegar ... done https://github.com/w3c/pointerevents/blob/gh-pages/index.html#L68

**Comment by plehegar** [comment]
> Thank you @plehegar ... done https://github.com/w3c/pointerevents/blob/gh-pages/index.html#L68

I should have been more explicit. That sentence needed to be added to the SOTD section, not the abstract....

**Comment by patrickhlauke** [comment]
@plehegar Doh, my bad. I should have inferred that, looking at it now. Fixed https://github.com/w3c/pointerevents/commit/77680fb4d07ebbdfcf63cabe7eaa815d6dfe69c8

And just to check, is there a specific template or phrasing to use to notify the groups? Or is a simple (to paraphrase) "Hey, we'd appreciate a review, ideally before X" enough?

**Comment by patrickhlauke** [comment]
Automated email that went out on the public-review-announce mailing list https://lists.w3.org/Archives/Public/public-review-announce/2024Mar/0003.html

**Comment by aphillips** [comment]
I saw the WR announcement this morning, but I18N is not in receipt of a review request. Just a reminder not to wait before doing your horizontal reviews. Instructions are [here](https://www.w3.org/Guide/documentreview/#how_to_get_horizontal_review) in the Guide.

**Comment by patrickhlauke** [comment]
@aphillips yes sorry, i've not been through the various groups to explicitly request review yet (and wasn't quite clear what the automated email thing would or wouldn't trigger directly)

**Comment by patrickhlauke** [comment]
Still waiting for security and privacy reviews. @plehegar I assume we can't proceed without these? or is it possible to set the wheels in motion already, despite the lack of reviews?

**Comment by patrickhlauke** [comment]
Closed the security review request https://github.com/w3c/security-request/issues/67 as there's been no movement on it since May when it was first filed.

**Comment by patrickhlauke** [comment]
All resulting issues have now been addressed. Closing.

**Comment by plehegar** [comment]
i18n got cleared in https://github.com/w3c/pointerevents/issues/505#issuecomment-2794907369
