### ISSUE TITLE
Make `pointerenter` definition similar to `pointerover` w.r.t. `pointerdown` from a touch pointer

### ISSUE THREAD

**Issue by mustaqahmed** [w3c/pointerevents#497]
The definition for [`pointerdown`](https://w3c.github.io/pointerevents/#the-pointerdown-event) has a special case for `pointerover` and `pointerenter` events from a touch pointer:

> For input devices that do not support hover, the user agent MUST also fire a pointer event named pointerover followed by a pointer event named pointerenter prior to dispatching the pointerdown event.

The [`pointerenter`](https://w3c.github.io/pointerevents/#the-pointerenter-event) definition repeats the same point ("... including as a result of a pointerdown event from a device that does not support hover") but the [`pointerover`](https://w3c.github.io/pointerevents/#the-pointerover-event) definition doesn't.  These two definitions should be similar.

**Comment by smaug----** [comment]
pointerbut? 

pointerdown/over/enter all talk about "devices that do not support hover". What are we missing?

**Comment by mustaqahmed** [comment]
The last sentence of 4.2.1 covers the diff I was worried about.  Closing the issue.
