### ISSUE TITLE
improve drop down menu handling

### ISSUE THREAD

**Issue by tienmai56** [w3c/pointerevents#499]
When using touch to access hyperlinked menu that is designed to expand further into sub-menus, the entire menu opens for a split second and then web users are directed to the main menu's page. This happens in websites such as Ebay, USPS, etc. 
<img width="406" alt="image" src="https://github.com/w3c/pointerevents/assets/35861383/15635be6-7b8f-4743-94cb-ce771c34753d">

This is because when the sticky hover logic is invoked on anchor tags or on elements that are otherwise clickable, navigation is not cancelled.  Safari fixes this behavior by determining whether any child element of the element that appeared is clickable. If so, they'll cancel the navigation and treat the tap as a hover. If not, they'll continue with the navigation/executing the click handler. 

Should we consider matching Safari's behavior? I think we should consider this for good compatibility with Safari and existing web content that's never going to get updated to be mobile-friendly

**Comment by patrickhlauke** [comment]
It would be inappropriate to try and address this at the Pointer Events specification level, in my view. This falls heavily under heuristic browser behavior.

**Comment by patrickhlauke** [comment]
Discussed at today's meeting https://www.w3.org/2024/03/13-pointerevents-minutes.html

The group agrees that this would be out of scope for the Pointer Events specification, as it involves browser heuristics that each user agent will decide for themselves unfortunately.

**Comment by tienmai56** [comment]
@patrickhlauke can you recommend what repo I should open this issue? pointer events group was recommended by some folks from Google. Thanks!
