### ISSUE TITLE
Status out of date in the README

### ISSUE THREAD

**Issue by pygy** [w3c/pointerevents#500]
The README mentions that the spec is partially implemented in Gecko and WebKit, but both links are dead. 

https://mozilla.github.io/standards-positions/ and https://webkit.org/standards-positions/ don't seem to mention this spec at all (searching from "pointer" doesn't yield anything).

The `pointerrawupdate` tests at https://wpt.fyi/results/pointerevents?label=master&label=experimental are also out of date, since they expect the event to fire in non-secure contexts (and thus chrome "fails" where firefox "succeeds" where they shouldn't).

**Comment by patrickhlauke** [comment]
Updated/edited the readme, as all major engines now have PE support (though their level of individual aspects of the spec will differ, but that is a more granular aspect that can't be appropriately covered in just the README).

As for the WPT tests, they are being updated constantly. I would suggest opening a matching issue in https://github.com/web-platform-tests/wpt
