### ISSUE TITLE
Selection creation sometimes causes a `pointerleave` in Safari

### ISSUE THREAD

**Issue by pygy** [w3c/pointerevents#501]
In Safari, in [this example](https://flems.io/#0=N4IgzgpgNhDGAuEAmIBcIB0ALeBbKIANCAGYCWMYaA2qAHYCGuEamO+RIsA9nYn6wA6dADxIyANwAEZJAF4ACgwBOEPgD5hUqUtV8tUsZJnzYWCkk11t2gMIAJAJIAZACIGRAenESrXn+qckDAIZLxU6ABsqJEgAL6E9Ews6BgAVlTEPHxq8Ky6uRi8AA7cZDl6iMpSclIAFBASAJRy6tlg3DAYUNwA5nUA5MUquVK5EMoDTcLCBXxFdKXlVTAMEhA19Y0tbeGdEN19g8OVUqvrUzN0ZhYLSxXj1bV1O8AGxYM3UEhjFZfWUk8nikXyQGFUuG46xewjiwlBdzKFXOG2er3en3M3zOEDWEH+2iBIKxYIhUIgMLocSC0Dg8DCdAiIAArKgAIwADniiRAjGYrAwsDAmS4vH4eXQPjeAIARgxYABrXrKbgAVzoSFQUgAxCQAAx6gAsAG5YVdtXN4NLtFgIGRejgtQBmPXFAAepqp5tBUmtUlKYDI9N4WoYMo6UFViE9NrtDvgztdHrNdBpIWDjNYACZUHr4gBdOJAA), if you select text stradling the element boundary, `pointerleave` is fired.

Is this spec compliant?

https://github.com/w3c/pointerevents/assets/54515/3a586b4e-e4fd-4939-8d55-2d98b073bb8d

**Comment by aprotyas** [comment]
Hi @pygy, do you mind filing a bug report on https://bugs.webkit.org?

**Comment by pygy** [comment]
Here you are!

https://bugs.webkit.org/show_bug.cgi?id=271346

Edit: I suppose we can close this.

**Comment by mustaqahmed** [comment]
Thanks for moving the discussion to WebKit.
