### ISSUE TITLE
https://www.w3.org/TR/pointerevents/ redirects to old spec...

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/pointerevents#506]
Should https://www.w3.org/TR/pointerevents/ redirect to https://www.w3.org/TR/pointerevents3/ instead?

**Comment by patrickhlauke** [comment]
Level 3 isn't REC yet, https://www.w3.org/TR/pointerevents/ points to the latest REC version (Level 2)

**Comment by marcoscaceres** [comment]
Right, but generally you’d want the main one to point to what developers and implementers should be looking at, no? 

I’m asking because I googled for the spec and then took me a while to figure out I was looking at something that’s not the latest.

**Comment by patrickhlauke** [comment]
deferring to @plehegar here, as I'm not 100% au-fait with the intricacies of what exactly should redirect to where

**Comment by smaug----** [comment]
I'm rather confused about this issue. TR/ points usually to the latest published spec, but everyone should look at the latest editor's draft.  And https://www.w3.org/TR/pointerevents/ has a link to that.

**Comment by plehegar** [comment]
https://www.w3.org/TR/pointerevents3/ points to ... Level 4.

I need to spend time to untangling this... :-/

**Comment by patrickhlauke** [comment]
sorry, hope i'm not the one who made it worse with recent pushes

**Comment by plehegar** [comment]
For Level 4 to be properly reflected to /TR, I would need:
[[
We will need a Group decision to publish a first public Working Draft 
for level 4 if we want to reflect the gh-pages branch to w3.org/TR . 
]]
[Minutes of 31st July](https://lists.w3.org/Archives/Public/public-pointer-events/2024JulSep/0013.html)

Did we get that?

**Comment by plehegar** [comment]
ok, I fixed https://www.w3.org/TR/pointerevents3/ to link it to pushes in the level3 branch.

I need a pointer to the group decision to publish level4.

And, if we really want everyone should look at the editor's draft, we should change https://www.w3.org/TR/pointerevents/ to point to https://www.w3.org/TR/pointerevents/upcoming/ instead of https://www.w3.org/TR/pointerevents/latest/ .

**Comment by patrickhlauke** [comment]
@plehegar 

> I need a pointer to the group decision to publish level4.

I realised that we don't have a formal "ok, we're going for Level 4" explicit pointer - we seem to have just tacitly agreed it when discussing branching off the CR and carrying on with further work for the next version here

https://www.w3.org/2024/07/31-pointerevents-minutes.html#t02

https://www.w3.org/2024/08/14-pointerevents-minutes.html#t05

Is that sufficient, or should we raise an explicit point about it with votes?

**Comment by plehegar** [comment]
> Is that sufficient, or should we raise an explicit point about it with votes?

I'll link to your GitHub comment :)

**Comment by plehegar** [comment]
The FPWD for Level 4 will be published on Thursday:
1. /TR/pointerevents/ will point to it
2. After Thursday, I'll update the GH variable for the auto-publish token so that it will work.

Once those things are done, I'll close this issue as addressed.

**Comment by plehegar** [comment]
We're all set:
* level3 branch auto-publish at https://www.w3.org/TR/pointerevents3/
* gh-pages branch auto-publish at https://www.w3.org/TR/pointerevents4/
* https://www.w3.org/TR/pointerevents/ points to https://www.w3.org/TR/pointerevents4/

**Comment by patrickhlauke** [comment]
lovely, thank you @plehegar
