### ISSUE TITLE
PREVENT MOUSE EVENT flag is not well defined when multiple pointer types are active

### ISSUE THREAD

**Issue by NavidZ** [w3c/pointerevents#51]
Consider the following sequence of events:
1. pointerdown(type=mouse)
2. pointerdown(type=pen)
3. pointermove(type=mouse)
4. pointer move(type=pen)
5. pointerup(type=mouse)
6. pointerup(type=pen)

If js calls prevent default on the first step what should be the compatibility mouse events?

The way it's defined in the spec now with PREVENT MOUSE EVENT being sort of global, agent should fire one single mouseup on step 6.

I have a feeling that maybe the flag should be per pointer type. So I believe maybe the correct compatibility mouse events in the example above would be sending mousedown, mousemove, and mouseup in steps 2, 4, and 6 instead. Am I right or was there an intention behind defining PREVENT MOUSE EVENT flag global across all pointer types?

**Comment by patrickhlauke** [comment]
It would be my understanding that the flag is per pointer type
