### ISSUE TITLE
Shouldn't dispatch `gotpointercapture` and `lostpointercapture` events if `pointerrawupdate` event is fired without the following `pointermove`?

### ISSUE THREAD

**Issue by masayuki-nakano** [w3c/pointerevents#511]
`pointerawupdate` may be fired more frequently than `pointermove` so that some `pointerrawupdate` event may not be immediately followed by `pointermove` event. Therefore, if `pointerrawupdate` is dispatched but the web app do not listen to it, it looks like that `gotpointercapture` and `lostpointercapture` may be dispatched without any other pointer events.

I think that ["fire a pointer event" section](https://w3c.github.io/pointerevents/#dfn-fire-a-pointer-event) should define they won't be dispatched at before `pointerrawupdate` (at least if it's not followed by `pointermove`).

Or, the spec should mention about that adding a `pointerrawupdate` event listener will change the timing of caputre event.

**Comment by masayuki-nakano** [comment]
Ah, but `pointerrawupdate` does not change the order of pointer boundary events vs. pointer capture events.
> Before firing this event, the user agent SHOULD treat the target as if the pointing device has moved over it from the previousTarget for the purpose of [ensuring event ordering](https://www.w3.org/TR/uievents/#events-mouseevent-event-order) [[UIEVENTS](https://w3c.github.io/pointerevents/#bib-uievents)]. If the needsOverEvent flag is set, a [pointerover](https://w3c.github.io/pointerevents/#dfn-pointerover) event is needed even if the target element is the same.

So, it seems safe to dispatch them even without `pointermove`.

**Comment by smaug----** [comment]
@masayuki-nakano  So we could close this?

**Comment by masayuki-nakano** [comment]
Indeed.
