### ISSUE TITLE
Limit the precision of floating point event fields

### ISSUE THREAD

**Issue by jyasskin** [w3c/pointerevents#517]
There's a history of factory calibration information being used to fingerprint individual devices. I haven't investigated whether this is possible on common pointing devices, but as a precaution, would it make sense to establish a normative limit on the precision of the fields in pointer events, similar to what was done for deviceorientation and accelerometer? See https://github.com/w3c/deviceorientation/pull/86, which limited angle measurements to 0.1 degrees.

**Comment by mustaqahmed** [comment]
Looks like we should be fine with a 0.01 precision in all of [these](https://w3c.github.io/pointerevents/#pointerevent-interface) `double` attributes and the [inherited coordinates](https://drafts.csswg.org/cssom-view/#extensions-to-the-mouseevent-interface).  Or maybe even 0.1 in some cases.  Thoughts?

We don't need to "downgrade" the IDL types to [`float`](https://webidl.spec.whatwg.org/#idl-float), do we?

**Comment by jyasskin** [comment]
I think `float` fields are also vulnerable to this problem, so they should also be limited, and there's no need to consider changing `double`s to `float`s.

**Comment by smaug----** [comment]
We don't want to change any idl types for this. Just need to document that when dealing with trusted events, the precision of all the float and double properties should be limited. Need to be just careful with the wording, since the limit is on the "native"  precision level.

**Comment by flackr** [comment]
@smaug---- I agree, I'd be happy with something non-specific. A similar example is the precision of times in the web-animations spec: https://www.w3.org/TR/web-animations-1/#precision-of-time-values

I think it might be good to say something for the different fields, e.g. something like this:
* For sizes and coordinates, the minimum precision should be precise enough to differentiate physical pixels at the size on screen
* For pressures and other analog values, the minimum precision should allow for at least 256 distinct values to avoid significant banding when used as an output color.
* For angles, the minimum precision should at least be 1 degree

**Comment by smaug----** [comment]
That sounds reasonable to me.

**Comment by patrickhlauke** [comment]
@jyasskin if you have a moment, we've just pushed an addition to the level 3 branch here https://github.com/w3c/pointerevents/pull/533

**Comment by jyasskin** [comment]
That seems sufficient to me. Thanks!

**Comment by patrickhlauke** [comment]
wonderful, thanks for the quick second check. Closing this issue as addressed in https://github.com/w3c/pointerevents/pull/533

**Comment by smaug----** [comment]
I wonder if we can test this. Hopefully we can.
