### ISSUE TITLE
[DOM integration] No state is reset on node removal

### ISSUE THREAD

**Issue by domfarolino** [w3c/pointerevents#526]
Nothing in the specification seems to explicitly reset pointer event state for an element, that would make [`hasPointerCapture()`](https://w3c.github.io/pointerevents/#dom-element-haspointercapture) return false after an element is removed from the DOM, I think. I would expect this specification to hook into [DOM's removing steps](https://dom.spec.whatwg.org/#concept-node-remove-ext) to reset some state when an element that has pointer capture is removed.

We came across this in the process of working on https://github.com/whatwg/dom/pull/1307, and have this test: https://github.com/web-platform-tests/wpt/blob/master/dom/nodes/moveBefore/tentative/pointer-events.html

**Comment by mustaqahmed** [comment]
As per [this text](https://w3c.github.io/pointerevents/#ref-for-dfn-pending-pointer-capture-target-override-7:~:text=When%20the%20pointer%20capture%20target%20override%20is%20no%20longer%20connected%20%5BDOM%5D%2C%20the%20pointer%20capture%20target%20override%20SHOULD%20be%20set%20to%20the%20document.), the document becomes the capture target so `hasPointerCapture()` would still return `true` I believe.

**Comment by smaug----** [comment]
hasPointerCapture() would return false, because of https://w3c.github.io/pointerevents/#dom-element-haspointercapture
The spec is quite clear even though it is not using the removing steps. It explicitly says what happens when element isn't connected anymore. (but the relevant part should probably use MUST, not SHOULD)

**Comment by domfarolino** [comment]
OK, I think I found it. The text here: https://w3c.github.io/pointerevents/#ref-for-dfn-pending-pointer-capture-target-override-8 mentions that the **pending pointer capture target override** should be cleared when it is no longer connected to the DOM, which would make `hasPointerCapture()` return false on the disconnected element, and still true on a `moveBefore()`'d element (since it never becomes disconnected). Thank you! I'll close this issue.
