### ISSUE TITLE
Only people with push access can have issues assigned to them

### ISSUE THREAD

**Issue by RByers** [w3c/pointerevents#55]
It's annoying that users with push access are the only ones who can have issues assigned to them (eg. see isaacs/github#100).  It would help me co-ordinate Google's work if I could assign issues to people  (eg. @navidz, @mustaqahmed, @dtapuska) even though they won't be pushing changes directly.  I propose we just make such people collaborators in the repo and just ask them to continue to rely on editors merging their PRs instead of pushing directly.  @patrickhlauke @shepazu thoughts?

**Comment by patrickhlauke** [comment]
if it's an easy setting to change, i'd be all in favor to change it (having just had a similar issue in another group, where i first had to be made group member manually by an admin)

**Comment by shepazu** [comment]
Okay by me, though I confess I don't know how to do this. If you know 
how and need me to do something, let me know what to do.

Doug

**Comment by patrickhlauke** [comment]
ah, i thought it was something that can be done with a setting, but it seems the only way here is to explicitly add folks as collaborators. so process would be for rick (and anybody else from other orgs/members) to feel free to suggest collaborators to be added, with the understanding that only editors will merge PRs (or give green light for user to merge their own PR). i guess @shepazu or mike cooper will have to be the ones actually adding these users as collaborators. i'd suggest - to avoid firing lots of tiny requests - we gather a list of people and then send one big request to them

**Comment by RByers** [comment]
@shepazu Yep, it's easy for anyone with `pointerevents` admin access.  Just go to the [collaborators setting](https://github.com/w3c/pointerevents/settings/collaboration) and give these people (and probably also @teddink) write access.

**Comment by patrickhlauke** [comment]
has this been done? (not hassling @shepazu, just wondering if this can be closed, as i can't verify it)

**Comment by RByers** [comment]
No, it hasn't.  You can verify by trying to assign an issue to @teddink, @navidz, etc.

**Comment by shepazu** [comment]
Done. Sorry for the delay.

**Comment by RByers** [comment]
Thanks @shepazu.  I see @mustaqahmed now, but not @navidz, @teddink or @dtapuska.  Are they all added?

**Comment by shepazu** [comment]
Yes, I added all of them, but I don't think all of them have yet accepted the invitation.

**Comment by RByers** [comment]
Ah of course, thanks.
