### ISSUE TITLE
Convert spec IDL to "contiguous" style

### ISSUE THREAD

**Issue by RByers** [w3c/pointerevents#58]
ReSpec now generates a warning saying:

> Defining WebIDL in `dl` elements is deprecated. Please use Contiguous IDL instead: https://www.w3.org/respec/guide.html#contiguous-idl

Perhaps it's time to finally rewrite using the preferred syntax?  Note that we looked at this for TE at one point: w3c/touch-events#31.

/cc @NavidZ @mustaqahmed in case either of you are interested in picking this up.

**Comment by patrickhlauke** [comment]
for reference, details for the contiguous IDL have been moved to https://www.w3.org/respec/examples/webidl-contiguous.html
