### ISSUE TITLE
Touch-action isn't flexible enough for direction-specific behavior

### ISSUE THREAD

**Issue by RByers** [w3c/pointerevents#6]
See https://lists.w3.org/Archives/Public/public-pointer-events/2015JanMar/0033.html

**Comment by RByers** [comment]
Landed in df02c702b8e35b646a8ce054dc0f2db2116f5d2e
Tweaked in 8548506a7db4de67fa6b8ca997887fdb6a0c8056

Let's keep the issue open until we have consensus that we feel this is ready to ship though.  We owe the group some demos, etc.

**Comment by patrickhlauke** [comment]
> We owe the group some demos

Is this actually implemented now? Or are we thinking theoretical demos?

**Comment by RByers** [comment]
It's implemented in Chrome behind the enable-experimental-web-platform-features flag.

**Comment by RByers** [comment]
Next step here is to write a demo (eg. of the carousel case interacting reasonably with panning while pinch-zoomed).  @dtapuska, @NavidZ any interest?

**Comment by dtapuska** [comment]
I had written a [carousel](http://dtapuska.github.io/touch-action/carousel.html) before; I guess the viewport isn't scalable.

**Comment by RByers** [comment]
Oh I forgot you wrote that, sorry!  I think it demonstrates the essential point here (a carousel inside something else that scrolls - doesn't really matter if that's a pinch viewport or some other scroller).  

With `pan-right`/`pan-left` support you can swipe all the way to the end of the carousel (49), lift, then drag to scroll the container to the right.  Without `pan-right` and `pan-left` I don't think there's really any way to make the composition scenario work with pointer events.  You have to disallow horizontal panning of the container when over the carousel completely.  This means that when pinch-zoomed in you may be trapped - unable to pan the viewport without zooming out.

@scottgonzalez I'm curious for your take on this sort of nested scrolling scenario.  Seem important to you / jQuery? I know nested scrollers are generally an anti-pattern, but they happen all the time in pinch-zoom scenarios so can't be ignored completely IMHO.

@NavidZ / @mustaqahmed note that this carousel doesn't appear to work correctly in Chrome with pointer event support enabled - want to debug to see if it's a known compat issue?

**Comment by scottgonzalez** [comment]
We don't have any cases within jQuery UI where we would need these values, but I've discussed this with @arschmitz (jQuery Mobile lead) and we both think this would be a useful addition.

**Comment by RByers** [comment]
Here's a [different demo](http://jsbin.com/dahaga) designed to be a ultra-simplistic version of what twitter.com is doing for pull-to-refresh in Chrome via touch events.  To do the same thing with pointer events, you really need `touch-action: pan-down`.

[Video of the effect from twitter](https://rbyers.github.io/twitter-p2r.gif)

**Comment by RByers** [comment]
blink [Intent-to-ship](https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/bcD93CiIJHE).    

I think all that's left for this bug is to add some web platform tests to validate the behavior (both parsing and automated input).  @dtapuska can you own, or find someone else to own that?  It may be simpler to write some new more concise touch-action tests to replace the existing ones, or we can just continue to extend the pattern in the existing ones.

**Comment by RByers** [comment]
Note that we [discussed this feature at the hackathon](https://docs.google.com/document/d/1b8aJOJcGXakstFJslKl87QwvlFHhHwGbQfJwnUTBBHg/edit).   Although it'll probably be over a year before Edge can implement, they're [OK with the design](https://developer.microsoft.com/en-us/microsoft-edge/platform/status/touchactionpanuppandownpanleftpanrightcssproperties).

We noticed a subtle difference with what twitter.com does in Chrome today and what's possible with this feature: if you start at scrollTop=0, pan down, and then pan up you can get the p2r effect to trigger.  It's not clear that that's any better UX than what will be possible via touch-action (where the effect will only trigger if you start by panning up) and it's fairly subtle so we're not worried about it.

**Comment by RByers** [comment]
web-platform-test added in https://github.com/w3c/web-platform-tests/commit/f690b6f2f942de267c560f1066c0fb3225dac980, I think we can now call this done.
