### ISSUE TITLE
Mouse Event compatibility model for touch is incompatible with current practice

### ISSUE THREAD

**Issue by RByers** [w3c/pointerevents#7]
Existing web code expects mouse events for touch only after the end of the event sequence ("gesture based mouse event compatibility").  The model defined by pointer events is incompatible with this.  This is especially problematic on a page that has components which both use touch and pointer events.

IE is already exploring doing this.  See "simplify mouse events for touch" in this [IE blog post](http://blogs.msdn.com/b/ie/archive/2015/02/24/pointer-events-w3c-recommendation-interoperable-touch-and-removing-the-dreaded-300ms-tap-delay.aspx).

**Comment by patrickhlauke** [comment]
For info, I've (as ever) documented the event sequence here http://patrickhlauke.github.io/touch/tests/results/#desktop-touchscreen-events

Windows 8/IE 11: `mousemove > pointerover > mouseover > pointerenter > mouseenter > pointerdown > mousedown > (gotpointercapture) > focus > pointermove > mousemove > pointerup > mouseup > (lostpointercapture) > pointerout > mouseout > pointerleave > mouseleave > click`  (note `click` is at the end, contrary to what the spec says)

Win 10 Technical preview (10049) / Spartan (Edge) - which also supports touch events at the same time `pointerover > pointerenter > pointerdown > touchstart > focus > (gotpointercapture) > pointermove > pointerup > touchend > (lostpointercapture) > mouseover > mouseenter > mousemove > mousedown > mouseup > click > pointerout > pointerleave` (note all the mouse compat events being fired after `pointerup`/`touchend`, as in the touch events model)

So, as a first measure, this modified event sequence (and simplified algorithm) need to be added/amended in the spec (in the normative explanation/algorithm and in the informative boxout)

**Comment by RByers** [comment]
Thanks Patrick!  When we talked to Jacob about this on a call it sounded like they wanted some more implementation experience with this approach first before he really wanted to commit to it.  I'm fine waiting for this (we'll proceed in Chrome implementing the new model and can gain some experience with it ourselves, I have no plans ATM to implement the model as currently spec'd).

**Comment by patrickhlauke** [comment]
Sure, sorry...not trying to jump the gun here...just making sure I put my current knowledge/thoughts "on paper" here :)

**Comment by RByers** [comment]
Not at all - that's perfect, thanks!  Just wanted to avoid you burning a bunch of time potentially trying to come up with a pull request only to have Jacob ask us to wait :-)

**Comment by RByers** [comment]
From 11/3/15 conf call, Edge team says they use the 'gesture' model whenever touch events are enabled (i.e. on mobile), the currently documented model otherwise.

**Comment by patrickhlauke** [comment]
Does this mean that the v2 spec needs to explicitly state that some UAs may choose to NOT follow the event sequence in certain situations? Or is the current wording (making it optional, using MAY, etc) enough https://w3c.github.io/pointerevents/#compatibility-mapping-with-mouse-events ?

**Comment by RByers** [comment]
If the Edge team believes that's the right model for browsers that support touch events, then I think it's the one we should primarily document (I wouldn't event experiment with anything different in blink).  So to me the question is do we update the spec to refer ONLY to that model (possibly with some sort of note indicating that some UAs sometimes use a different model) or do we explicitly describe both models.  Ideally I think we'd settle on a single model we think is best.

**Comment by teddink** [comment]
I can confirm that the Edge team indeed believes that using the click-based (aka "gesture") model when touch events are enabled and the currently documented model otherwise is the best approach for interoperability.

**Comment by RByers** [comment]
On today's call @teddink said it was their intention to have Edge's behavior match this PR but it'll take them some time to try coding it up and understand the full impact in practice.

**Comment by RByers** [comment]
See related tests added in https://github.com/w3c/web-platform-tests/commit/1b243414ac2e98b12bf7f38a65130b015d5f3396

**Comment by RByers** [comment]
Discussed in the call today - getting the wording of this right within the charter of PEWG is difficult.  Since we're talking about a behavior that's present only when `TouchEvent` is supported, let's put the actual definition into the TouchEvent spec instead (w3c/touch-events#70).  Then this issue tracks adding a non-normative note to the PE spec to link to the TouchEvent spec.
