### ISSUE TITLE
Add additional digitizer/pen attributes: barrel pressure (tangential pressure)

### ISSUE THREAD

**Issue by patrickhlauke** [w3c/pointerevents#70]
this issue splits out the discussion around https://github.com/w3c/pointerevents/issues/25#issuecomment-193898076 - adding a barrel pressure / tangential pressure attribute (implemented as a scroll-wheel or similar on airbrush digitizers), maps to HID digitizer 0x31

**Comment by patrickhlauke** [comment]
In the call today (https://www.w3.org/2016/05/25-pointerevents-minutes.html) the question about actual devices that support rotation came up. This Wacom airbrush pen (compatible with Intuos Pro) https://us-store.wacom.com/Product/Airbrush-Pen-black-S01 supports barrel pressure.

**Comment by RByers** [comment]
Looks like MacOS has a standard API for this: [NSEvent tangentialPressure](https://developer.apple.com/library/mac/documentation/Cocoa/Reference/ApplicationKit/Classes/NSEvent_Class/#//apple_ref/occ/instp/NSEvent/tangentialPressure).  This passes my "at least one major OS must have built-in API support test", so I support adding this.
