### ISSUE TITLE
ReSpec error: "A custom SotD paragraph is required for your type of document."

### ISSUE THREAD

**Issue by RByers** [w3c/pointerevents#71]
ReSpec is reporting: "A custom SotD paragraph is required for your type of document".  I don't know if something changed in the spec to trigger this, or if respec has changed to have a new rule.  Regardless we should figure out what we should do to eliminate the error.

**Comment by patrickhlauke** [comment]
caused by https://github.com/w3c/pointerevents/pull/67 most likely. wonder what custom content we should have there though...thoughts?

**Comment by RByers** [comment]
[respec docs](https://www.w3.org/respec/#section) say:

> Required. The "Status of this Document" section. Obviously, you do not need to include the endless reams of boilerplate that that section normally contains: that's generated for you. However, the PubRules require that part of that boilerplate be "a custom paragraph". The content you include in this section is therefore injected as that custom paragraph (you can have several, in fact any markup you want is used). Don't spend too much time putting together the best of your prose for this, it is almost certain that no one will ever read it.

Running the [PubRules checker](http://services.w3.org/xslt?xmlfile=http%3A%2F%2Fservices.w3.org%2Ftidy%2Ftidy%3FdocAddr%3Dhttps%253A%252F%252Fw3c.github.io%252Fpointerevents%252F&xslfile=http%3A%2F%2Fservices.w3.org%2Fxslt%3Fxmlfile%3Dhttp%3A%2F%2Fwww.w3.org%2F2005%2F07%2Fpubrules%253Fuimode%253Dchecker_full%2526year%253D0001%2526docstatus%253Dord-wd-tr%2526rectrack%253Dyes%2526prevrec%253Dnone%2526patpol%253Dw3c%2526normative%253Dyes%2526uri%253Dhttps%25253A%25252F%25252Fw3c.github.io%25252Fpointerevents%25252F%2526filterValues%253D%2526nscheckmanual%253D%2526display%253Dall%2526recursive%253Doff%2526recurse_auth%253Don%2526procrev%253D2005%26xslfile%3Dhttp%3A%2F%2Fwww.w3.org%2F2005%2F09%2Fchecker%2Fframe.xsl%26display%3Dall%26recurse_auth%3Don&uimode=checker_full&filterValues=&year=0001&docstatus=ord-wd-tr&rectrack=yes&prevrec=none&patpol=w3c&normative=yes&doc_uri=https%3A%2F%2Fw3c.github.io%2Fpointerevents%2F&recursive=off&nscheckmanual=&display=all&recurse_auth=on&procrev=2005) (a tool I was previously unaware of) I see lots of different errors, including:

> Error : SOTD not found (note that some tests relying on the SOTD won't be done because of this).

Perhaps our `<span>` tag inside the `<h2>` is throwing it off?

Anyway.  Following this I eventually found [this doc](https://www.w3.org/2001/06/manual/#Status) which says:

> The custom paragraph is very important as it actually contains information! In it, you should explain where a part of the energy of the group has been invested. The custom paragraph should help a reader decide "I really should read this draft." This implies that you shouldn't paste it in from somewhere else. It should be very specific to this document.
> 
> TimBL expressed the goal of the custom paragraph this way, "Don't be afraid of being honest about the relevant techno-political situation." In the custom paragraph, make th case for why someone should read this draft.
> 
> In the custom paragraph, include what you would reply to a Member or colleague who asked you such things as:
> 
> Are we requesting that people implement this specification? If so, where should experience reports be sent?
> Are we requesting people do not implement the specification until a later date? What sort of damage do we expect to inflict on those who do by future changes to the document?
> Does it reflect the consensus of a W3C Working Group? (Pay attention to the authors and acknowledgments.)
> Are there any changes expected?
> Do we maintain a page of background information (e.g., the P3P FAQ [P3PFAQ])?
> For pre-release drafts, state in the status section any limits on redistribution, such as "Member confidential."

So perhaps we should just be honest about what we're trying to achieve with PEL2 here?  Maybe something like:

> This specification is an update to Pointer Events Level 1 which was shipped broadly only by Microsoft IE and Edge.  Level 2 includes features and minor breaking changes designed to enable adoption by blink and to address limitations / concerns that have been raised about the design.

**Comment by patrickhlauke** [comment]
Looks good to me, though I'd also add something about fixing minor bugs/inconsistencies and adding clarifications. Something like:

> This specification is an update to Pointer Events Level 1 which was shipped broadly only by Microsoft Internet Explorer and Edge. Level 2 includes editorial clarifications, new features and minor breaking changes designed to enable wider browser adoption and to address certain limitations and concerns that have been raised about the design.

Would be interested in comments from other WG members on this proposed SotD

**Comment by RByers** [comment]
Your text is better than mine, thanks!

**Comment by teddink** [comment]
A minor point - please make an edit to call the browser "Microsoft Edge" - that is the "official" public name for the browser that Microsoft now ships. We can (and do) all colloquially call it just Edge, but it would be better to have the official name in a spec document.

**Comment by patrickhlauke** [comment]
Expanded the above slightly (to mention the other interoperable/independent implementations in pre-release builds of Firefox/Chrome, to swap emphasis on addressing design criticism rather than wider browser adoption, and to add "Microsoft" to the canonical product name for Edge). Feedback on #74 welcome, but barring any major disagreement keen to push this out later tonight.
