### ISSUE TITLE
Moving "Firing events..." and "Process Pending Pointer Capture"

### ISSUE THREAD

**Issue by patrickhlauke** [w3c/pointerevents#85]
Should "Firing events using the PointerEvent interface" and "Process Pending Pointer Capture" logically come under "5.1 PointerEvent Interface" rather than "5.2 Pointer Event Types"

**Comment by RByers** [comment]
They don't seem to fit super-well in either section IMHO.  Maybe they should be two new sub-sections of section 5?  Regardless they should show up in the table of contents - they're pretty significant sections IMHO.
