### ISSUE TITLE
"Pointer Event Types" misleading/inappropriate section heading?

### ISSUE THREAD

**Issue by patrickhlauke** [w3c/pointerevents#86]
Currently we have "5.2 Pointer Event Types", which has no content other than "List of Pointer Events" and then sibling headings for all events. Would it be more logical to drop "Pointer Event Types" and promote "List of Pointer Events" one hierarchical level up, so that the following headings then come under it?

**Comment by RByers** [comment]
SGTM

**Comment by patrickhlauke** [comment]
Closed via #89
