### ISSUE TITLE
illustration for "twist" ?

### ISSUE THREAD

**Issue by patrickhlauke** [w3c/pointerevents#88]
`tiltX` and `tiltY` have some snazzy illustrations in https://w3c.github.io/pointerevents/#pointerevent-interface - wonder if we could get a similar one for the new `twist` property too? i guess @jacobrossi @teddink might know how the original images were created, and whether it's possible to either get the source images, 3D model, or whatever else may be needed to add new ones?

**Comment by RByers** [comment]
meh.  It's an obscure feature and pretty self explanatory IMHO.  Sure it would be nice though if someone can produce / update the image easily.  But it's not where I'd personally spend my effort.

**Comment by patrickhlauke** [comment]
well i wasn't expecting this to be an onerous thing to create. more for completeness' sake...

**Comment by patrickhlauke** [comment]
randomly... @teddink any idea how the original images were created? 3DSMax, other?

**Comment by teddink** [comment]
Nope - well before my time. @jacobrossi perhaps?

**Comment by jacobrossi** [comment]
Pretty sure it was SketchUp.  Will search for the originals.

**Comment by patrickhlauke** [comment]
though it's super low priority...i've got sketchup all installed and ready to go ;)
