### ISSUE TITLE
repo cleanup?

### ISSUE THREAD

**Issue by patrickhlauke** [w3c/pointerevents#90]
In the interest of keeping the repo lean and mean...do we need to keep `dc.html` and the `publish` folder? I guess they're more a historical curiosity, particularly as we move ahead now with FPWD?

**Comment by patrickhlauke** [comment]
Any thoughts? Or should I just go ahead and remove the above?

**Comment by RByers** [comment]
I have no idea what those were for - part of the publishing process presumably?  Unless @shepazu has a reason we should keep them, I'd say delete them (can always get them from history of course).

**Comment by shepazu** [comment]
👍
