### ISSUE TITLE
Support Event.composed in Pointer Events

### ISSUE THREAD

**Issue by hayatoito** [w3c/pointerevents#91]
The context: w3c/webcomponents#513

Could someone give me advice how we should update Pointer Events specification so it considers Event.composed?

Is a Pull Request a recommended way to reflect the conclusion at w3c/webcomponents#513
?

**Comment by patrickhlauke** [comment]
Yes, a PR (with a bit of explanation in the description) would be great, thanks.

**Comment by hayatoito** [comment]
Thanks. I have sent a PR: https://github.com/w3c/pointerevents/pull/92
