### ISSUE TITLE
strange/interesting results for Wacom Intuos Pro hovering clicks

### ISSUE THREAD

**Issue by patrickhlauke** [w3c/pointerevents#97]
related to https://github.com/w3c/pointerevents/pull/96/files/a08c5e40f4e3fc537eeebe3cf49f12707e083294#r68673045 i've had a little play with the Wacom Intuos Pro and my demo https://patrickhlauke.github.io/touch/tracker/multi-touch-tracker-pointer-hud.html (which now also includes `button` and `buttons` in the HUD display).

remapping the second barrel button (using Wacom's settings app) to be a "Click", whenever you hover the stylus and press the button the pointer turns active, but critically `pressure` is set to 1 (so the button simulates a full-force press of the pen on the digitizer).

![wacom-barrel-click](https://cloud.githubusercontent.com/assets/895831/16410136/fd1e8fee-3d18-11e6-8f7f-14ae5044b3d1.png)

the first barrel button (mapped to right click) seems to emulate an actual _mouse_ right click - rather than the `pen` pointer having `buttons` set to 2, the `mouse` pointer is registered as having its right button pressed.

![wacom-right-click](https://cloud.githubusercontent.com/assets/895831/16410142/0429a22e-3d19-11e6-9ac6-b83e0843131f.png)

i assume this is due to the way the Wacom driver itself interprets these things... /cc @dfleck

**Comment by dfleck** [comment]
“Click” means Left Click.

There’s a reason for the full pressure. If you double click the word Click at the tip of the pen image in the control panel a menu pops up. This allows the tip to be disabled for physically challenged users (tremors causing unwanted tip clicks). They then set a side switch to be the left click (Click). If the tip is disabled then there’s no pressure available, so a Click on a side switch also sets pressure to max for maximum brush effect.

Windows does confusing stuff with barrel buttons (sometimes a barrel switch acts as a right click and sometimes it doesn’t). So there’s both a Right Click option and a Tablet PC Defined or Barrel Button option (depending on the system). 

If you set it to Middle Click you’ll get button 4 for the upper side switch.

Nice demo BTW!

> On Jun 28, 2016, at 2:14 AM, Patrick H. Lauke notifications@github.com wrote:
> 
> related to https://github.com/w3c/pointerevents/pull/96/files/a08c5e40f4e3fc537eeebe3cf49f12707e083294#r68673045 https://github.com/w3c/pointerevents/pull/96/files/a08c5e40f4e3fc537eeebe3cf49f12707e083294#r68673045 i've had a little play with the Wacom Intuos Pro and my demo https://patrickhlauke.github.io/touch/tracker/multi-touch-tracker-pointer-hud.html https://patrickhlauke.github.io/touch/tracker/multi-touch-tracker-pointer-hud.html (which now also includes button and buttons in the HUD display).
> 
> remapping the second barrel button (using Wacom's settings app) to be a "Click", whenever you hover the stylus and press the button the pointer turns active, but critically pressure is set to 1 (so the button simulates a full-force press of the pen on the digitizer).
> 
>  https://cloud.githubusercontent.com/assets/895831/16410136/fd1e8fee-3d18-11e6-8f7f-14ae5044b3d1.png
> the first barrel button (mapped to right click) seems to emulate an actual mouse right click - rather than the pen pointer having buttons set to 2, the mouse pointer is registered as having its right button pressed.
> 
>  https://cloud.githubusercontent.com/assets/895831/16410142/0429a22e-3d19-11e6-9ac6-b83e0843131f.png
> i assume this is due to the way the Wacom driver itself interprets these things... /cc @dfleck https://github.com/dfleck
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub https://github.com/w3c/pointerevents/issues/97, or mute the thread https://github.com/notifications/unsubscribe/ABKnimv5FOlcDTHNgkEbwzShv1cgdfOOks5qQOX4gaJpZM4I_5aJ.

---

"For every fatal shooting, there were roughly three non-fatal shootings. And, folks, this is unacceptable in America. It's just unacceptable. And we're going to do something about it." -- G. W. Bush, 5/14/2001

**Comment by patrickhlauke** [comment]
@dfleck 

> There’s a reason for the full pressure. If you double click the word Click at the tip of the pen image in the control panel a menu pops up. This allows the tip to be disabled for physically challenged users (tremors causing unwanted tip clicks). They then set a side switch to be the left click (Click). If the tip is disabled then there’s no pressure available, so a Click on a side switch also sets pressure to max for maximum brush effect.

Ah, that makes sense.

> Windows does confusing stuff with barrel buttons (sometimes a barrel switch acts as a right click and sometimes it doesn’t). So there’s both a Right Click option and a Tablet PC Defined or Barrel Button option (depending on the system).

Yeah I'm putting this down to the settings/driver and how it's mapped in the OS, and whatever the default are set to. Will have to dig a bit deeper into the various options and document which ones have which effect.

> Nice demo BTW!

I got more where that came from ;) https://patrickhlauke.github.io/touch/ (e.g. https://patrickhlauke.github.io/touch/pen-tracker/ https://www.youtube.com/watch?v=1VlQzagF8PA )

**Comment by patrickhlauke** [comment]
Closing this as it's not necessarily a PE issue, in hindsight.
